const DAY = 86400000
export const toNumber = (value) => {
  if (typeof value === 'number') return Number.isFinite(value) ? value : 0
  if (typeof value !== 'string' || !value.trim()) return 0
  const clean = value.replace(/R\$/gi, '').replace(/\s/g, '')
  const normalized = clean.includes(',') ? clean.replace(/\./g, '').replace(',', '.') : clean
  const number = Number(normalized)
  return Number.isFinite(number) ? number : 0
}
const text = (value) => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toLowerCase()
const date = (value) => { if (!value) return null; const parsed = new Date(`${String(value).slice(0, 10)}T12:00:00`); return Number.isNaN(parsed.getTime()) ? null : parsed }
const signed = (p) => ['true','sim','yes','1'].includes(text(p.contract_signed)) || p.contract_signed === true
export const normalizeResponsibleName = (value) => { const name = text(value); if (name.includes('kleb')) return 'kleber'; if (name.includes('julia')) return 'julia'; if (name.includes('danilo')) return 'danilo'; return name }
export const isClosedProposal = (p) => ['fechada','fechado','aprovado','aprovada','contrato assinado','projeto iniciado'].includes(text(p?.proposal_status))
export const isActiveContract = (p, now = new Date()) => isClosedProposal(p) && signed(p) && (!date(p.contract_end_date) || date(p.contract_end_date) >= new Date(now.getFullYear(), now.getMonth(), now.getDate()))
export const calculateRecurringRevenue = (items, now) => items.filter((p) => isActiveContract(p, now) && toNumber(p.monthly_value) > 0).reduce((s,p) => s + toNumber(p.monthly_value), 0)
export const calculateProjectRevenue = (items) => items.filter(isClosedProposal).reduce((s,p) => s + toNumber(p.setup_value), 0)
export const calculateAgencyGoalProgress = (items, goal, now) => { const current = calculateRecurringRevenue(items, now); return { goal, current, remaining: Math.max(goal-current,0), percentage: goal ? Math.min((current/goal)*100,100) : 0, activeContracts: items.filter((p) => isActiveContract(p,now) && toNumber(p.monthly_value)>0).length } }
export const calculateTeamGoals = (items, members, now) => { const eligible=items.filter((p)=>isActiveContract(p,now)&&toNumber(p.monthly_value)>0); const result=members.map((m)=>{ const revenue=eligible.filter((p)=>normalizeResponsibleName(p.responsible)===m.id).reduce((s,p)=>s+toNumber(p.monthly_value),0); return {...m,revenue,remaining:Math.max(m.goal-revenue,0),percentage:m.goal?Math.min(revenue/m.goal*100,100):0} }); const unassigned=eligible.filter((p)=>!normalizeResponsibleName(p.responsible)).reduce((s,p)=>s+toNumber(p.monthly_value),0); return { members:result, unassigned } }
export const groupRevenueByService = (items, now) => { const map=new Map(); items.filter(isClosedProposal).forEach((p)=>{ const name=p.main_service?.trim()||'Serviço não informado'; const row=map.get(name)||{name,count:0,monthly:0,setup:0}; row.count+=1; row.setup+=toNumber(p.setup_value); if(isActiveContract(p,now)) row.monthly+=toNumber(p.monthly_value); map.set(name,row) }); const total=calculateRecurringRevenue(items,now); return [...map.values()].map((r)=>({...r,share:total?r.monthly/total*100:0})).sort((a,b)=>b.monthly-a.monthly||b.setup-a.setup) }
export const calculateSalesGapScenarios = (remainingGoal, catalog) => remainingGoal<=0?[]:catalog.filter((s)=>s.active&&s.billingType==='recurring'&&toNumber(s.recommendedPrice)>0).map((s)=>({...s,quantity:Math.ceil(remainingGoal/s.recommendedPrice)})).sort((a,b)=>a.quantity-b.quantity||b.recommendedPrice-a.recommendedPrice).slice(0,5)
export const calculateContractedRevenue = (items, now=new Date()) => { const windows=[30,90,180,365]; const eligible=items.filter((p)=>isClosedProposal(p)&&signed(p)&&toNumber(p.monthly_value)>0); const values=Object.fromEntries(windows.map((days)=>[days,0])); eligible.forEach((p)=>{ const end=date(p.contract_end_date); if(!end)return; const start=date(p.contract_start_date)||now; windows.forEach((days)=>{ const limit=new Date(now.getTime()+days*DAY); const from=start>now?start:now; const until=end<limit?end:limit; if(until<from)return; const months=Math.max(1,Math.ceil((until-from)/DAY/30)); values[days]+=months*toNumber(p.monthly_value) }) }); return {values,withoutEndDate:eligible.filter((p)=>!date(p.contract_end_date)).length} }
const termMonths=(value)=>{const match=text(value).match(/(\d+)\s*(mes|meses|mês)/);return match?Number(match[1]):null}
export const groupContractsByDuration = (items, now=new Date()) => { const labels=['Até 3 meses','4 a 6 meses','7 a 12 meses','Mais de 12 meses','Prazo indeterminado','Prazo não informado']; const rows=Object.fromEntries(labels.map((label)=>[label,{label,count:0,revenue:0,share:0}])); items.filter((p)=>isClosedProposal(p)&&signed(p)).forEach((p)=>{const start=date(p.contract_start_date),end=date(p.contract_end_date);let months=start&&end?Math.max(1,Math.ceil((end-start)/DAY/30)):termMonths(p.contract_term);let label;if(months!=null)label=months<=3?labels[0]:months<=6?labels[1]:months<=12?labels[2]:labels[3];else if(/indeterminado|sem vencimento/.test(text(p.contract_term)))label=labels[4];else label=labels[5];rows[label].count++;if(isActiveContract(p,now))rows[label].revenue+=toNumber(p.monthly_value)});const total=Object.values(rows).reduce((s,r)=>s+r.revenue,0);return Object.values(rows).map((r)=>({...r,share:total?r.revenue/total*100:0})) }
export const calculateRevenueRisk = (items, now=new Date()) => { const sums={expired:0,due30:0,due60:0,withoutEnd:0,closedUnsigned:0,signedWithoutLink:0}; items.filter(isClosedProposal).forEach((p)=>{const value=toNumber(p.monthly_value),end=date(p.contract_end_date),isSigned=signed(p);if(!isSigned)sums.closedUnsigned++;if(isSigned&&!p.contract_file_url)sums.signedWithoutLink++;if(isSigned&&!end)sums.withoutEnd++;if(isSigned&&end){const days=Math.ceil((end-now)/DAY);if(days<0)sums.expired+=value;else if(days<=30)sums.due30+=value;else if(days<=60)sums.due60+=value}});return sums }
export const simulateServiceMix = (rows, catalog) => rows.reduce((result,row)=>{const service=catalog.find((s)=>s.id===row.serviceId);const quantity=Math.max(0,Number(row.quantity)||0);if(!service||service.billingType==='percentage')return result;const amount=toNumber(service.recommendedPrice)*quantity;if(service.billingType==='recurring')result.recurring+=amount;else result.oneTime+=amount;return result},{recurring:0,oneTime:0})
