import { toNumber } from './businessMetrics.js'
const norm=(v)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()
const parse=(v)=>{if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?null:d}
const status=(p)=>norm(p.status||p.proposal_status)
const won=(p)=>['won','fechada','aprovado','contrato assinado','projeto iniciado'].includes(status(p))
const lost=(p)=>['lost','perdida'].includes(status(p))
const draft=(p)=>['draft','rascunho'].includes(status(p))
const value=(p)=>toNumber(p.totalValue??p.total_value)||(toNumber(p.setupValue??p.setup_value)+toNumber(p.monthlyValue??p.monthly_value))
export function periodRange(period,now=new Date(),custom={}){const end=new Date(now.getFullYear(),now.getMonth(),now.getDate(),23,59,59);if(period==='all')return {start:null,end:null};if(period==='custom')return {start:parse(custom.start),end:parse(custom.end)};let start;if(period==='month')start=new Date(now.getFullYear(),now.getMonth(),1);if(period==='30')start=new Date(end.getTime()-29*86400000);if(period==='quarter')start=new Date(now.getFullYear(),Math.floor(now.getMonth()/3)*3,1);if(period==='year')start=new Date(now.getFullYear(),0,1);if(period==='12months')start=new Date(now.getFullYear(),now.getMonth()-11,1);return {start,end}}
export function filterBySentAt(items,range){let withoutDate=0;const filtered=items.filter((p)=>{const d=parse(p.sentAt||p.sent_at||p.proposal_sent_date);if(!d){withoutDate++;return !range.start&&!range.end}return (!range.start||d>=range.start)&&(!range.end||d<=range.end)});return {filtered,withoutDate}}
export function calculateCommercialPerformance(items){const result={sent:0,proposedValue:0,setupSent:0,monthlyPotential:0,open:0,negotiating:0,won:0,lost:0,wonValue:0,lostValue:0,withoutResponsible:0,closingDays:[],lossDays:[]};items.forEach((p)=>{const proposed=value(p);if(!draft(p)){result.sent++;result.proposedValue+=proposed;result.setupSent+=toNumber(p.setupValue??p.setup_value);result.monthlyPotential+=toNumber(p.monthlyValue??p.monthly_value)}if(won(p)){result.won++;result.wonValue+=proposed}else if(lost(p)){result.lost++;result.lostValue+=proposed}else{result.open++;if(['negotiating','em negociacao'].includes(status(p)))result.negotiating++}if(!norm(p.responsibleName??p.responsible))result.withoutResponsible++;const sent=parse(p.sentAt||p.sent_at||p.proposal_sent_date);const closed=parse(won(p)?p.closed_at:p.lost_at);if(sent&&closed&&closed>=sent)(won(p)?result.closingDays:result.lossDays).push((closed-sent)/86400000)});const avg=(a)=>a.length?a.reduce((s,n)=>s+n,0)/a.length:0;return {...result,outcomeConversion:result.won+result.lost?result.won/(result.won+result.lost)*100:0,sentConversion:result.sent?result.won/result.sent*100:0,averageSent:result.sent?result.proposedValue/result.sent:0,averageWon:result.won?result.wonValue/result.won:0,averageClosingDays:avg(result.closingDays),averageLossDays:avg(result.lossDays)}}
export function groupCommercialPerformance(items,dimension){const map=new Map();items.forEach((p)=>{let labels;if(dimension==='responsible')labels=[p.responsibleName||p.responsible||'Sem responsável'];else if(dimension==='origin')labels=[p.leadSource||p.lead_source||'Não informada'];else if(dimension==='status')labels=[p.status||p.proposal_status||'Não informado'];else labels=p.services?.length?p.services.map((s)=>s.name):p.proposal_services?.length?p.proposal_services.map((s)=>s.service_name||'Serviço não informado'):[p.mainService||p.main_service||'Serviço não informado'];labels.forEach((label)=>{const list=map.get(label)||[];list.push(p);map.set(label,list)})});return [...map].map(([label,rows])=>({label,...calculateCommercialPerformance(rows)})).sort((a,b)=>b.sent-a.sent)}
