const value=(input)=>Number.isFinite(Number(input))?Number(input):0
export const competenceKey=(input)=>String(input||'').slice(0,7)
export const firstOfMonth=(input)=>`${competenceKey(input)}-01`
export const uniqueFinancialRows=(rows=[])=>[...new Map(rows.filter((row)=>row?.id).map((row)=>[row.id,row])).values()]

export function buildFinancialOverview({receivables=[],payables=[],debts=[],freelance=[],goals=[],plans=[],pipeline=[]},period,{scope='all',requireOpeningBalance=false}={}){
  const allowed=(rowScope)=>scope==='all'||rowScope===scope
  const income=uniqueFinancialRows(receivables).filter((row)=>allowed('business')&&competenceKey(row.reference_month||row.due_date)===period&&row.status!=='cancelled')
  const expenses=uniqueFinancialRows(payables).filter((row)=>allowed(row.expenses?.financial_scope||'business')&&competenceKey(row.reference_month||row.due_date)===period&&row.status!=='cancelled')
  const scopedDebts=debts.filter((row)=>allowed(row.owner_scope||'business')),scopedFreelance=freelance.filter((row)=>allowed(row.scope||'business')),scopedGoals=goals.filter((row)=>allowed(row.scope||'business'))
  const forecastRevenue=income.reduce((sum,row)=>sum+value(row.projected_brl_amount??row.amount),0)
  const receivedRevenue=income.reduce((sum,row)=>sum+value(row.actual_brl_amount??row.received_amount),0)
  const forecastExpense=expenses.reduce((sum,row)=>sum+value(row.amount),0)
  const paidExpense=expenses.reduce((sum,row)=>sum+Math.min(value(row.paid_amount),value(row.amount)),0)
  const byArea=(area)=>expenses.filter((row)=>(row.expenses?.area||row.expenses?.scope)===area).reduce((sum,row)=>sum+Math.min(value(row.paid_amount),value(row.amount)),0)
  const freelanceIncome=scopedFreelance.filter((row)=>competenceKey(row.competence||row.movement_date)===period&&row.type==='income'&&row.status==='received').reduce((sum,row)=>sum+value(row.amount),0)
  const freelanceApplied=scopedFreelance.filter((row)=>competenceKey(row.competence||row.movement_date)===period&&row.type!=='income'&&row.applied&&row.status!=='cancelled').reduce((sum,row)=>sum+value(row.amount),0)
  const planScope=scope==='all'?'business':scope,plan=plans.find((row)=>competenceKey(row.competence)===period&&row.scope===planScope)||{},hasOpeningBalance=plan.opening_balance!==null&&plan.opening_balance!==undefined,openingBalance=hasOpeningBalance?value(plan.opening_balance):null
  const capSpend=expenses.filter((row)=>row.expenses?.impacts_monthly_cap&&(scope==='all'?row.expenses?.financial_scope==='business':row.expenses?.financial_scope===scope)).reduce((sum,row)=>sum+Math.min(value(row.paid_amount),value(row.amount)),0)
  const debtPaid=scopedDebts.flatMap((row)=>row.debt_payments||[]).filter((row)=>competenceKey(row.competence||row.paid_on)===period).reduce((sum,row)=>sum+value(row.amount),0),netReal=receivedRevenue-paidExpense,netProjected=forecastRevenue-forecastExpense
  return{income,expenses,forecastRevenue,receivedRevenue,contractedReceivable:Math.max(forecastRevenue-receivedRevenue,0),forecastExpense,paidExpense,openingBalance,hasOpeningBalance,realBalance:requireOpeningBalance&&!hasOpeningBalance?null:(openingBalance||0)+netReal,projectedBalance:requireOpeningBalance&&!hasOpeningBalance?null:(openingBalance||0)+netProjected,businessExpense:byArea('business'),householdExpense:byArea('household')+byArea('shared'),freelanceBalance:freelanceIncome-freelanceApplied,debtBalance:scopedDebts.reduce((sum,row)=>sum+value(row.current_balance),0),reserveBalance:scopedGoals.reduce((sum,row)=>sum+value(row.current_amount),0),pipelinePotential:scope==='all'||scope==='business'?pipeline.filter((row)=>!['won','lost'].includes(row.stage)).reduce((sum,row)=>sum+value(row.estimated_value),0):0,wonPotential:scope==='all'||scope==='business'?pipeline.filter((row)=>row.stage==='won').reduce((sum,row)=>sum+value(row.estimated_value),0):0,monthlyCap:value(plan.monthly_cap),capSpend,capAvailable:Math.max(value(plan.monthly_cap)-capSpend,0),debtTarget:value(plan.debt_target),debtPaid,reserveTarget:value(plan.reserve_target),otherGoalsTarget:value(plan.other_goals_target)}
}

export function buildFinancialCalendar({receivables=[],payables=[],debts=[],freelance=[],goals=[]},period){
  return[
    ...uniqueFinancialRows(receivables).filter((row)=>competenceKey(row.due_date)===period).map((row)=>({id:`income:${row.id}`,date:row.due_date,kind:row.status==='paid'?'received':'receivable',scope:'business',label:row.clients?.company_name||row.description||'Recebimento',amount:value(row.actual_brl_amount??row.received_amount)||value(row.projected_brl_amount??row.amount),source:row})),
    ...uniqueFinancialRows(payables).filter((row)=>competenceKey(row.due_date)===period).map((row)=>({id:`expense:${row.id}`,date:row.due_date,kind:row.status==='paid'?'expense_paid':'expense_due',scope:row.expenses?.financial_scope||'business',label:row.expenses?.name||'Despesa',amount:value(row.paid_amount)||value(row.amount),source:row})),
    ...debts.filter((row)=>competenceKey(row.due_date)===period&&row.status!=='paid').map((row)=>({id:`debt:${row.id}`,date:row.due_date,kind:'debt',scope:row.owner_scope,label:row.name,amount:value(row.current_balance),source:row})),
    ...freelance.filter((row)=>competenceKey(row.movement_date)===period&&row.status!=='cancelled').map((row)=>({id:`freelance:${row.id}`,date:row.movement_date,kind:'freelance',scope:row.scope,label:row.project_source,amount:value(row.amount),source:row})),
    ...goals.flatMap((goal)=>(goal.financial_goal_movements||[]).filter((row)=>competenceKey(row.competence||row.occurred_on)===period).map((row)=>({id:`goal:${row.id}`,date:row.occurred_on,kind:'reserve',scope:goal.scope||'business',label:goal.name,amount:value(row.amount),source:row}))),
  ].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))
}

export function budgetComparison(budgets=[],payables=[],period){return budgets.filter((row)=>competenceKey(row.competence)===period).map((budget)=>{const actual=payables.filter((row)=>competenceKey(row.reference_month||row.due_date)===period&&row.expenses?.category_id===budget.category_id&&row.status!=='cancelled').reduce((sum,row)=>sum+Math.min(value(row.paid_amount),value(row.amount)),0);return{...budget,actual,balance:value(budget.planned_amount)-actual}})}

export function monthlyClosingPreview(data,period){const overview=buildFinancialOverview(data,period),fixed=data.receivables.filter((row)=>competenceKey(row.reference_month)===period&&(row.revenue_type||'fixed')==='fixed'&&row.status!=='cancelled'),freelance=data.freelance.filter((row)=>competenceKey(row.competence)===period&&row.type==='income'&&row.status==='received'),extra=data.receivables.filter((row)=>competenceKey(row.reference_month)===period&&row.revenue_type==='extra'&&row.status!=='cancelled'),freelanceRevenue=freelance.reduce((s,r)=>s+value(r.amount),0),reserveAdded=data.goals.flatMap((goal)=>goal.financial_goal_movements||[]).filter((row)=>competenceKey(row.competence||row.occurred_on)===period).reduce((sum,row)=>sum+value(row.amount),0),monthResult=overview.receivedRevenue+freelanceRevenue-overview.paidExpense-overview.debtPaid;return{...overview,fixedRevenue:fixed.reduce((s,r)=>s+value(r.projected_brl_amount??r.amount),0),freelanceRevenue,extraRevenue:extra.reduce((s,r)=>s+value(r.projected_brl_amount??r.amount),0),reserveAdded,monthResult,accumulatedBalance:overview.hasOpeningBalance?overview.openingBalance+monthResult:null,allFixedPaid:fixed.every((row)=>row.status==='paid'),withinCap:overview.monthlyCap<=0||overview.capSpend<=overview.monthlyCap,debtTargetMet:overview.debtPaid>=overview.debtTarget}}
