const number=(value)=>value==null?null:Number(value)
const latest=(rows=[])=>[...rows].sort((a,b)=>String(b.uploaded_at||b.created_at).localeCompare(String(a.uploaded_at||a.created_at)))[0]||null
const normalizeService=(service)=>({id:service.id,name:service.service_name||service.name||'Serviço não informado',category:service.service_category||service.category||null,billingType:service.billing_type||service.billingType||null,quantity:number(service.quantity),unitPrice:number(service.unit_price??service.unitPrice),monthlyValue:number(service.monthly_value??service.monthlyValue),oneTimeValue:number(service.one_time_value??service.oneTimeValue)})

export function normalizeProposal(row={}){
  const client=row.clients||row.clientDetails||{},services=(row.proposal_services||row.services||[]).map(normalizeService),documents=row.documents||[],proposalFile=latest(documents.filter((document)=>document.document_type==='proposal')||[])
  return {id:row.id,title:row.title||row.company||row.client_name||'Proposta sem título',proposalNumber:row.proposal_number??row.proposalNumber??null,status:row.status||row.proposal_status||'draft',clientId:row.client_id??row.clientId??null,clientName:client.trade_name||row.client_name||client.company_name||row.company||'Cliente não informado',companyName:client.company_name||row.company||row.client_name||'Empresa não informada',contactName:client.contact_name||row.contact_name||row.client_name||null,responsibleId:row.responsible_id??row.responsibleId??null,responsibleName:row.profiles?.name||row.responsible||row.responsibleName||null,setupValue:number(row.setup_value??row.setupValue),monthlyValue:number(row.monthly_value??row.monthlyValue),totalValue:number(row.total_value??row.totalValue),services,mainService:services[0]?.name||row.main_service||row.mainService||null,sentAt:row.sent_at||row.proposal_sent_date||row.sentAt||null,validUntil:row.valid_until||row.validUntil||null,contractTermMonths:number(row.contract_term_months??row.contractTermMonths),leadSource:row.lead_source||row.origin||row.leadSource||null,notes:row.notes||null,proposalFile,createdAt:row.created_at||row.createdAt||null,updatedAt:row.updated_at||row.updatedAt||null,clientDetails:{...client,phone:client.phone||row.phone||null,email:client.email||row.email||null,instagram:client.instagram||null,website:client.website||null,segment:client.segment||null},documents,history:row.commercial_events||row.history||[],hasContract:Boolean(row.contracts?.length||row.hasContract),deletedAt:row.deleted_at||row.deletedAt||null}
}

export const normalizeProposals=(rows=[])=>rows.map(normalizeProposal)
