export const DEFAULT_TIME_ZONE='America/Sao_Paulo'
export const BUSINESS_HOURS={start:9,end:18}
const DAY=86400000
const pad=(value)=>String(value).padStart(2,'0')
const key=(year,month,day)=>`${year}-${pad(month)}-${pad(day)}`

function easter(year){let a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;return new Date(Date.UTC(year,month-1,day))}
export function nationalHolidays(year){const holidays=new Map([[key(year,1,1),'Confraternização Universal'],[key(year,4,21),'Tiradentes'],[key(year,5,1),'Dia do Trabalho'],[key(year,9,7),'Independência do Brasil'],[key(year,10,12),'Nossa Senhora Aparecida'],[key(year,11,2),'Finados'],[key(year,11,15),'Proclamação da República'],[key(year,11,20),'Dia Nacional de Zumbi e da Consciência Negra'],[key(year,12,25),'Natal']]);const easterDay=easter(year);for(const [offset,name] of [[-48,'Carnaval'],[-47,'Carnaval'],[-2,'Paixão de Cristo'],[60,'Corpus Christi']]){const date=new Date(easterDay.getTime()+offset*DAY);holidays.set(key(date.getUTCFullYear(),date.getUTCMonth()+1,date.getUTCDate()),name)}return holidays}
function parts(now,timeZone){const values=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',weekday:'long'}).formatToParts(now).filter((part)=>part.type!=='literal').map((part)=>[part.type,part.value]));return{year:Number(values.year),month:Number(values.month),day:Number(values.day),hour:Number(values.hour),minute:Number(values.minute),second:Number(values.second),weekdayEnglish:values.weekday,dateKey:`${values.year}-${values.month}-${values.day}`}}
const weekdayNames=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado']
function localDayIndex(year,month,day){return new Date(Date.UTC(year,month-1,day)).getUTCDay()}
function addCalendarDays(value,amount){const date=new Date(Date.UTC(value.year,value.month-1,value.day+amount));return{year:date.getUTCFullYear(),month:date.getUTCMonth()+1,day:date.getUTCDate()}}
export function getTemporalContext(now=new Date(),{timeZone=DEFAULT_TIME_ZONE,businessHours=BUSINESS_HOURS}={}){const value=parts(now,timeZone),dayIndex=localDayIndex(value.year,value.month,value.day),holidayName=nationalHolidays(value.year).get(value.dateKey)||null,isWeekend=dayIndex===0||dayIndex===6,isBusinessDay=!isWeekend&&!holidayName,minutes=value.hour*60+value.minute,startMinutes=businessHours.start*60,endMinutes=businessHours.end*60,isBusinessHours=isBusinessDay&&minutes>=startMinutes&&minutes<endMinutes;let cursor={year:value.year,month:value.month,day:value.day},label='hoje';if(!isBusinessDay||minutes>=endMinutes){do{cursor=addCalendarDays(cursor,1);label='';}while([0,6].includes(localDayIndex(cursor.year,cursor.month,cursor.day))||nationalHolidays(cursor.year).has(key(cursor.year,cursor.month,cursor.day)))}else if(minutes<startMinutes)label='hoje';const nextBusinessDate=key(cursor.year,cursor.month,cursor.day),tomorrow=addCalendarDays(value,1),isMonthEnd=addCalendarDays(value,1).month!==value.month,isMonthStart=value.day===1;return{...value,dayIndex,weekday:weekdayNames[dayIndex],formattedDate:`${pad(value.day)}/${pad(value.month)}/${value.year}`,formattedTime:`${pad(value.hour)}:${pad(value.minute)}`,monthName:new Intl.DateTimeFormat('pt-BR',{timeZone,month:'long'}).format(now),quarter:Math.ceil(value.month/3),holidayName,isHoliday:Boolean(holidayName),isWeekend,isBusinessDay,isBusinessHours,businessStatus:isBusinessHours?'aberto':'encerrado',period:value.hour<5?'madrugada':value.hour<12?'manhã':value.hour<18?'tarde':'noite',greeting:value.hour<5?'Boa madrugada':value.hour<12?'Bom dia':value.hour<18?'Boa tarde':'Boa noite',nextBusinessDate,nextBusinessLabel:label||(nextBusinessDate===key(tomorrow.year,tomorrow.month,tomorrow.day)?'amanhã':`${pad(cursor.day)}/${pad(cursor.month)}`),nextBusinessTime:`${pad(businessHours.start)}:00`,isMonthEnd,isMonthStart,timeZone,businessHours}}
export function temporalPriority(milliseconds){if(milliseconds<=DAY)return{priority:'critical',score:100};if(milliseconds<=3*DAY)return{priority:'high',score:85};if(milliseconds<=15*DAY)return{priority:'medium',score:60};return{priority:'low',score:30}}
export function remainingTime(target,now=new Date()){const milliseconds=new Date(target).getTime()-now.getTime(),absolute=Math.abs(milliseconds);if(absolute<DAY){const hours=Math.max(1,Math.ceil(absolute/3600000));return milliseconds>=0?`em ${hours} hora${hours===1?'':'s'}`:`há ${hours} hora${hours===1?'':'s'}`}const days=Math.max(1,Math.ceil(absolute/DAY));return milliseconds>=0?`em ${days} dia${days===1?'':'s'}`:`há ${days} dia${days===1?'':'s'}`}
export function operationalRecommendation(context,action='cobrança'){if(context.isBusinessHours)return action==='cobrança'?'Realize a cobrança agora.':`Realize esta ação agora: ${action}.`;if(context.isWeekend)return'Organize a próxima semana e programe as ações para o próximo expediente.';if(context.isHoliday)return`Reprograme para o próximo expediente (${context.nextBusinessLabel} às ${context.nextBusinessTime}).`;return action==='cobrança'?`Agende a cobrança para ${context.nextBusinessLabel} às ${context.nextBusinessTime}.`:'Prepare e programe esta ação para o próximo expediente.'}
