import assert from 'node:assert/strict'
import fs from 'node:fs'
const routes=fs.readFileSync(new URL('../src/config/appRoutes.js',import.meta.url),'utf8')
const migration=fs.readFileSync(new URL('../supabase/migrations/202608030001_crm_v2_expense_management.sql',import.meta.url),'utf8')
const repository=fs.readFileSync(new URL('../src/services/data/expensesRepository.js',import.meta.url),'utf8')
const foundation=fs.readFileSync(new URL('../supabase/migrations/202607130001_sprint7_foundation.sql',import.meta.url),'utf8')
const importMigration=fs.readFileSync(new URL('../supabase/migrations/202608030002_financial_import_control.sql',import.meta.url),'utf8')
for(const route of ["finance: '/financeiro'","'/financeiro/contas-a-receber': 'finance'","'/importar': 'documents'"])assert.ok(routes.includes(route),`Rota compatível ausente: ${route}`)
for(const table of ['expense_categories','cost_centers','financial_accounts','expenses','expense_installments'])assert.ok(migration.includes(`public.${table}`),`Tabela ausente: ${table}`)
assert.ok(migration.includes('enable row level security'))
assert.ok(migration.includes('public.current_organization_id()'))
assert.ok(migration.includes('public.can_write()'))
assert.ok(migration.includes('on conflict(organization_id,expense_id,reference_month,installment_number) do nothing'))
assert.match(migration,/foreign key\(organization_id,category_id\)/)
assert.match(migration,/foreign key\(organization_id,expense_id\)/)
assert.match(migration,/create trigger enforce_business_amount/)
assert.match(migration,/create trigger sync_installment_business_amounts/)
assert.match(migration,/revoke all on function public\.generate_expense_installments\(uuid\) from public/)
assert.doesNotMatch(migration,/for all to authenticated/)
assert.match(migration,/for insert to authenticated/)
assert.match(migration,/for update to authenticated/)
assert.match(migration,/expenses_org_deleted_idx/)
assert.match(migration,/expense_installments_expense_idx/)
assert.match(foundation,/current_organization_id\(\)/)
assert.match(foundation,/current_user_role\(\) in\('admin','manager'\)/)
assert.match(repository,/expenses!inner/)
assert.match(repository,/\.is\('expenses\.deleted_at',null\)/)
assert.doesNotMatch(repository,/\.delete\(/)
assert.match(importMigration,/add column if not exists import_key text/)
assert.match(importMigration,/unique index if not exists expenses_org_import_key_idx/)
assert.doesNotMatch(importMigration,/\b(insert|update|delete)\s+(into|public\.|from)/i)
assert.ok(!/\binsert into public\.(expenses|expense_installments)\b/i.test(migration.replace(/insert into public\.expense_installments\([\s\S]*?on conflict\([\s\S]*?;/i,'')),'Migration não deve semear despesas reais')
console.log('CRM V2 routes, RLS and idempotency: ok')
