import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
import {budgetComparison,buildFinancialCalendar,buildFinancialOverview,firstOfMonth,monthlyClosingPreview} from '../src/lib/financialHub.js'
import {parseInternalCommand} from '../supabase/functions/_shared/internalCommandCore.js'

const receivables=[
  {id:'fixed',reference_month:'2026-09-01',due_date:'2026-09-10',amount:3200,received_amount:3200,status:'paid',revenue_type:'fixed',clients:{company_name:'Roove'}},
  {id:'extra',reference_month:'2026-09-01',due_date:'2026-09-20',amount:1000,received_amount:0,status:'pending',revenue_type:'extra',clients:{company_name:'Extra'}},
]
const payables=[
  {id:'mugo',reference_month:'2026-09-01',due_date:'2026-09-08',amount:600,business_amount:600,paid_amount:600,status:'paid',expenses:{name:'Software',area:'business',financial_scope:'business',impacts_monthly_cap:true,category_id:'cat'}},
  {id:'casa',reference_month:'2026-09-01',due_date:'2026-09-12',amount:900,business_amount:0,paid_amount:500,status:'partial',expenses:{name:'Casa',area:'household',financial_scope:'household',impacts_monthly_cap:true,category_id:'home'}},
]
const debts=[{id:'debt',name:'Dívida',owner_scope:'business',initial_amount:2000,current_balance:1500,due_date:'2026-09-25',status:'installments',debt_payments:[{id:'payment',amount:500,competence:'2026-09-01'}]}]
const freelance=[{id:'free',project_source:'Tati',type:'income',status:'received',amount:800,movement_date:'2026-09-15',competence:'2026-09-01',scope:'business'},{id:'allocation',project_source:'Tati',type:'reserve',status:'applied',amount:200,movement_date:'2026-09-16',competence:'2026-09-01',scope:'business',applied:true}]
const goals=[{id:'goal',name:'Reserva',target_amount:5000,current_amount:700,scope:'business'}]
const plans=[{competence:'2026-09-01',scope:'business',monthly_cap:1000,debt_target:500,reserve_target:300,other_goals_target:100}]
const pipeline=[{id:'lead',stage:'qualified',estimated_value:9000},{id:'won',stage:'won',estimated_value:4000}]
const data={receivables,payables,debts,freelance,goals,plans,pipeline,budgets:[]}

test('separa previsto, realizado, Mugô, Casa e pipeline',()=>{const result=buildFinancialOverview(data,'2026-09');assert.equal(result.forecastRevenue,4200);assert.equal(result.receivedRevenue,3200);assert.equal(result.forecastExpense,1500);assert.equal(result.paidExpense,1100);assert.equal(result.businessExpense,600);assert.equal(result.householdExpense,500);assert.equal(result.pipelinePotential,9000);assert.equal(result.realBalance,2100)})
test('Caixa Freela fica isolado do caixa recorrente',()=>{const result=buildFinancialOverview(data,'2026-09');assert.equal(result.freelanceBalance,600);assert.equal(result.receivedRevenue,3200);assert.equal(result.realBalance,2100)})
test('plano mensal, dívidas, metas e orçamento usam movimentos reais',()=>{const result=buildFinancialOverview(data,'2026-09');assert.equal(result.debtBalance,1500);assert.equal(result.debtPaid,500);assert.equal(result.reserveBalance,700);assert.equal(result.capSpend,600);assert.equal(result.capAvailable,400);const budget=budgetComparison([{id:'b',competence:'2026-09-01',category_id:'cat',planned_amount:700}],payables,'2026-09');assert.equal(budget[0].actual,600);assert.equal(budget[0].balance,100)})
test('competência é DATE no primeiro dia e calendário não duplica registros',()=>{assert.equal(firstOfMonth('2026-09-22'),'2026-09-01');const events=buildFinancialCalendar(data,'2026-09');assert.equal(events.length,7);assert.equal(new Set(events.map((item)=>item.id)).size,events.length);assert.ok(events.some((item)=>item.kind==='debt'));assert.ok(events.some((item)=>item.kind==='freelance'))})
test('fechamento calcula indicadores sem misturar pipeline',()=>{const closing=monthlyClosingPreview(data,'2026-09');assert.equal(closing.fixedRevenue,3200);assert.equal(closing.extraRevenue,1000);assert.equal(closing.freelanceRevenue,800);assert.equal(closing.allFixedPaid,true);assert.equal(closing.withinCap,true);assert.equal(closing.debtTargetMet,true);assert.equal(closing.pipelinePotential,9000)})
test('parser financeiro exige confirmação para despesa, recebimento e freela',()=>{const expense=parseInternalCommand('Gastei 106 reais em tráfego');assert.equal(expense.intent,'FINANCIAL_EXPENSE_REQUEST');const receipt=parseInternalCommand('Entrou 3200 da Roove');assert.equal(receipt.intent,'FINANCIAL_RECEIPT_REQUEST');assert.equal(receipt.amount,3200);const freela=parseInternalCommand('Recebi 800 do freela da Tati');assert.equal(freela.intent,'FREELANCE_INCOME_REQUEST');assert.equal(freela.amount,800);assert.equal(parseInternalCommand('sim').intent,'CONFIRM_FINANCIAL')})
test('migration reutiliza fontes canônicas e protege escopo, histórico e fechamento',()=>{const sql=fs.readFileSync('supabase/migrations/202609220003_financial_hub_2026.sql','utf8');for(const term of ['invoice_installments','expenses','expense_installments','financial_debts','debt_payments','freelance_cash_movements','financial_goals','financial_goal_movements','financial_month_closings','financial_monthly_budgets','has_financial_permission','can_view_financial_scope','protect_closed_financial_period','protect_expense_closed_period','protect_debt_balance_history','protect_financial_hub_tenant','register_debt_payment','register_goal_movement','confirm_installment_receipt_internal'])assert.ok(sql.includes(term),term);assert.match(sql,/unique\(organization_id,idempotency_key\)/g);assert.match(sql,/enable row level security/g);assert.match(sql,/finance\.view_private/);assert.match(sql,/service_role/);assert.doesNotMatch(sql,/insert into public\.commercial_opportunities/)})
test('worker mantém ações financeiras idempotentes e confirmadas',()=>{const worker=fs.readFileSync('supabase/functions/task-command-worker/index.ts','utf8');assert.match(worker,/FINANCIAL_RECEIPT_REQUEST/);assert.match(worker,/FREELANCE_INCOME_REQUEST/);assert.match(worker,/status:'confirmation_required'/);assert.match(worker,/whatsapp-freelance-/);assert.match(worker,/confirm_installment_receipt_internal/);assert.match(worker,/resolution_command_event_id/)})
