import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers})
const contractFields=['client_id','proposal_id','contract_number','status','signed','signed_at','start_date','end_date','minimum_term_months','billing_day','setup_value','setup_received_amount','setup_received_at','setup_payment_method','setup_payment_notes','monthly_value','total_value','auto_renew','renewal_status','termination_date','termination_reason','notes','legacy_id']
const installmentFields=['client_id','contract_id','reference_month','installment_number','due_date','amount','status','paid_at','payment_method','manual_confirmation_at','operational_notes']
const pick=(input:Record<string,unknown>,allowed:string[])=>Object.fromEntries(Object.entries(input).filter(([key])=>allowed.includes(key)))

Deno.serve(async(request)=>{if(request.method==='OPTIONS')return new Response('ok',{headers});if(request.method!=='POST')return json({error:'Método não permitido.'},405);try{const authorization=request.headers.get('Authorization');if(!authorization)return json({error:'Sessão necessária.'},401);const client=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:authorization}}});const {data:{user}}=await client.auth.getUser();if(!user)return json({error:'Sessão inválida.'},401);const {data:profile}=await client.from('profiles').select('organization_id,role,active').eq('id',user.id).single();if(!profile?.active||!['admin','manager'].includes(profile.role))return json({error:'Permissão insuficiente.'},403);const body=await request.json();if(!['contract','installment'].includes(body.type)||!body.record||typeof body.record!=='object')return json({error:'Payload inválido.'},400);if(body.type==='contract'){const values=pick(body.record,contractFields),received=Number(values.setup_received_amount||0);values.setup_received_amount=0;values.setup_received_at=null;values.setup_payment_method=null;values.setup_payment_notes=null;const {data,error}=await client.from('contracts').insert({...values,organization_id:profile.organization_id}).select().single();if(error)return json({error:error.message},400);if(received>0){const {data:updated,error:updateError}=await client.from('contracts').update({setup_received_amount:received,setup_received_at:body.record.setup_received_at,setup_payment_method:body.record.setup_payment_method,setup_payment_notes:body.record.setup_payment_notes}).eq('id',data.id).select().single();if(updateError)return json({error:updateError.message},400);return json({data:updated})}return json({data})}const values=pick(body.record,installmentFields),paid=values.status==='paid';if(paid){values.status='pending';values.paid_at=null;values.manual_confirmation_at=null}const {data,error}=await client.from('invoice_installments').insert({...values,organization_id:profile.organization_id,provider:'manual'}).select().single();if(error)return json({error:error.message},400);if(paid){const {data:updated,error:updateError}=await client.from('invoice_installments').update({status:'paid',paid_at:body.record.paid_at,payment_method:body.record.payment_method,manual_confirmation_at:body.record.manual_confirmation_at,operational_notes:body.record.operational_notes}).eq('id',data.id).select().single();return updateError?json({error:updateError.message},400):json({data:updated})}return json({data})}catch{return json({error:'Não foi possível validar a importação manual.'},500)}})
