import {AGENCY_GOALS} from '../../config/agencyGoals.js'
import {buildCausalAnalysis} from '../intelligence/causalAnalysisEngine.js'
import {calculateCommercialPerformance} from '../../lib/commercialMetrics.js'
import {getTemporalContext,operationalRecommendation,temporalPriority} from '../../lib/temporalIntelligence.js'
const DAY=86400000,norm=(v)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),num=(v)=>Number(v||0)
const parsed=(v)=>{if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?null:d}
const active=(c)=>norm(c.status)==='active'&&(c.signed??true),open=(p)=>!['won','lost','cancelled','expired'].includes(norm(p.status||p.proposal_status))
const clientName=(id,clients)=>clients.find((c)=>c.id===id)?.company_name||'Cliente não identificado'
const make=(rule,title,description,{category='Sistema',priority='medium',origin='Mugô Intelligence',clientId=null,contractId=null,proposalId=null,responsibleId=null,link='dashboard',evidence=[],score=30}={})=>({fingerprint:[rule,clientId,contractId,proposalId].filter(Boolean).join(':'),rule,title,description,category,priority,origin,clientId,contractId,proposalId,assignedTeamMemberId:responsibleId,link,evidence,score})
export function generatePulseAlerts(data={},now=new Date()){
 const clients=data.clients||[],contracts=data.contracts||[],installments=data.installments||[],proposals=data.proposals||[],team=data.teamMembers||[],alerts=[],time=getTemporalContext(now)
 const activeContracts=contracts.filter(active),contractById=new Map(contracts.map((c)=>[c.id,c]))
 activeContracts.filter((contract)=>num(contract.setup_value)>0&&num(contract.setup_received_amount)===0&&!installments.some((item)=>item.contract_id===contract.id&&item.installment_type==='setup'&&num(item.received_amount)>0)).forEach((contract)=>alerts.push(make('setup-not-received','Setup não recebido',`O setup de ${clientName(contract.client_id,clients)} ainda não foi recebido.`,{category:'Financeiro',priority:'high',clientId:contract.client_id,contractId:contract.id,responsibleId:contract.responsible_id,link:'finance',score:80,evidence:[{type:'contrato',id:contract.id,setupValue:contract.setup_value}]})))
 installments.forEach((item)=>{const balance=num(item.amount)-num(item.received_amount),due=parsed(item.due_date),contract=contractById.get(item.contract_id);if(balance>0&&due&&due<now&&!['cancelled','refunded'].includes(norm(item.status))){const days=Math.floor((now-due)/DAY);alerts.push(make('overdue-installment',`Cobrança vencida há ${days} dias`,`${clientName(item.client_id,clients)} possui ${balance.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} em atraso. ${operationalRecommendation(time,'cobrança')}`,{category:'Financeiro',priority:days>=30?'critical':'high',clientId:item.client_id,contractId:item.contract_id,responsibleId:contract?.responsible_id,link:'finance',score:days>=30?100:80,evidence:[{type:'parcela',id:item.id,dueDate:item.due_date,amount:item.amount,balance,temporalContext:{at:time.formattedTime,businessHours:time.isBusinessHours}}] }))}if(!item.reference_month)alerts.push(make('missing-competence','Parcela sem competência','Uma parcela financeira não possui competência definida.',{category:'Financeiro',priority:'high',clientId:item.client_id,contractId:item.contract_id,link:'finance',score:75,evidence:[{type:'parcela',id:item.id,amount:item.amount}]}));if(balance<0)alerts.push(make('negative-balance','Saldo financeiro negativo','O valor recebido ultrapassou o valor previsto da parcela.',{category:'Financeiro',priority:'critical',clientId:item.client_id,contractId:item.contract_id,link:'finance',score:95,evidence:[{type:'parcela',id:item.id,amount:item.amount,received:item.received_amount}]}))})
 activeContracts.forEach((contract)=>{const services=contract.contract_services||[],rows=installments.filter((i)=>i.contract_id===contract.id),name=clientName(contract.client_id,clients);if(!rows.length)alerts.push(make('active-without-billing','Contrato ativo sem cobrança',`${name} possui contrato ativo sem parcelas geradas. ${operationalRecommendation(time,'cobrança')}`,{category:'Financeiro',priority:'critical',clientId:contract.client_id,contractId:contract.id,responsibleId:contract.responsible_id,link:'contracts',score:95,evidence:[{type:'contrato',id:contract.id,value:contract.monthly_value}]}));if(!contract.responsible_id)alerts.push(make('contract-without-owner','Contrato sem responsável',`${name} possui contrato ativo sem responsável.`,{category:'Contratos',priority:'high',clientId:contract.client_id,contractId:contract.id,link:'contracts',score:70}));if(!services.length)alerts.push(make('contract-without-services','Contrato ativo sem serviços',`${name} possui contrato ativo sem escopo de serviços.`,{category:'Contratos',priority:'high',clientId:contract.client_id,contractId:contract.id,link:'contracts',score:75}));const end=parsed(contract.end_date);if(end){const days=Math.ceil((end-now)/DAY);if(days<0)alerts.push(make('expired-contract','Contrato expirado',`${name} expirou há ${Math.abs(days)} dias.`,{category:'Contratos',priority:'critical',clientId:contract.client_id,contractId:contract.id,link:'contracts',score:95,evidence:[{type:'contrato',id:contract.id,endDate:contract.end_date}]}));else if(days<=60){const urgency=temporalPriority(end-now);alerts.push(make('expiring-contract','Contrato vencendo',`${name} vence em ${days} dias.`,{category:'Contratos',priority:urgency.priority,clientId:contract.client_id,contractId:contract.id,link:'contracts',score:urgency.score,evidence:[{type:'contrato',id:contract.id,endDate:contract.end_date,value:contract.monthly_value,daysRemaining:days}]}))}}services.forEach((service)=>{const base={category:'Serviços',clientId:contract.client_id,contractId:contract.id,responsibleId:service.delivery_responsible_id,link:'contracts'};if(!service.delivery_responsible_id&&!service.commercial_responsible_id&&!service.support_responsible_id)alerts.push(make(`service-owner-${service.id}`,'Serviço sem responsável',service.service_name||'Serviço contratado sem responsável.',{...base,priority:'high',score:70}));if(!service.service_category)alerts.push(make(`service-category-${service.id}`,'Serviço sem categoria',service.service_name||'Serviço sem categoria.',{...base,priority:'low',score:25}));if(num(service.monthly_value)===0&&num(service.one_time_value)===0)alerts.push(make(`service-value-${service.id}`,'Serviço sem valor',service.service_name||'Serviço sem valor.',{...base,priority:'medium',score:45}))})})
 proposals.forEach((proposal)=>{const sent=parsed(proposal.sentAt||proposal.sent_at||proposal.proposal_sent_date||proposal.created_at),days=sent?Math.floor((now-sent)/DAY):0,base={category:'Comercial',clientId:proposal.client_id,proposalId:proposal.id,responsibleId:proposal.responsible_id,link:'proposals'};if(open(proposal)&&days>14)alerts.push(make('stalled-proposal','Proposta parada',`${proposal.title||'Proposta'} está aberta há ${days} dias.`,{...base,priority:days>30?'high':'medium',score:days>30?75:50,evidence:[{type:'proposta',id:proposal.id,days,sentAt:sent?.toISOString()}]}));if(!proposal.responsible_id)alerts.push(make('proposal-without-owner','Proposta sem responsável',proposal.title||'Proposta sem responsável.',{...base,priority:'medium',score:45}));if(!proposal.client_id)alerts.push(make('proposal-without-client','Proposta sem cliente',proposal.title||'Proposta sem cliente.',{...base,priority:'high',score:70}))})
 const activeClientIds=new Set(activeContracts.map((c)=>c.client_id));clients.filter((c)=>!activeClientIds.has(c.id)).forEach((c)=>alerts.push(make('client-without-contract','Cliente sem contrato',`${c.company_name} não possui contrato ativo.`,{category:'Clientes',priority:'low',clientId:c.id,link:'clients',score:25})))
 const identities=new Map();clients.forEach((c)=>{const key=norm(c.document_number||c.email||c.company_name);if(key)identities.set(key,[...(identities.get(key)||[]),c])});[...identities.values()].filter((r)=>r.length>1).forEach((rows)=>alerts.push(make('possible-duplicate','Possível cliente duplicado',`${rows.length} cadastros compartilham a mesma identidade.`,{category:'Clientes',priority:'high',clientId:rows[0].id,link:'clients',score:75,evidence:rows.map((c)=>({type:'cliente',id:c.id,name:c.company_name}))})))
 const workload=new Map();activeContracts.flatMap((c)=>(c.contract_services||[])).forEach((s)=>{if(s.delivery_responsible_id)workload.set(s.delivery_responsible_id,(workload.get(s.delivery_responsible_id)||0)+1)});const loads=[...workload.values()],average=loads.length?loads.reduce((a,b)=>a+b,0)/loads.length:0;team.forEach((member)=>{const count=workload.get(member.id)||0;if(count===0)alerts.push(make('member-without-tasks','Responsável sem tarefas',`${member.name} não possui entregas ativas.`,{category:'Equipe',priority:'informational',responsibleId:member.id,link:'team',score:10}));if(count>=Math.max(10,average*1.5))alerts.push(make('overloaded-member','Responsável sobrecarregado',`${member.name} possui ${count} entregas ativas.`,{category:'Equipe',priority:'high',responsibleId:member.id,link:'team',score:75,evidence:[{type:'responsavel',id:member.id,deliveries:count,teamAverage:average}]}))})
 const mrr=activeContracts.reduce((s,c)=>s+num(c.monthly_value),0);if(mrr<AGENCY_GOALS.monthlyAgencyGoal)alerts.push(make('revenue-below-goal','Receita abaixo da meta',`O MRR está ${(100-mrr/AGENCY_GOALS.monthlyAgencyGoal*100).toFixed(1)}% abaixo da meta mensal.`,{category:'Intelligence',priority:mrr/AGENCY_GOALS.monthlyAgencyGoal<.7?'high':'medium',link:'intelligence',score:65,evidence:[{type:'dashboard',mrr,goal:AGENCY_GOALS.monthlyAgencyGoal}]}))
 const perf=calculateCommercialPerformance(proposals);if(perf.sent>=5&&perf.outcomeConversion<20)alerts.push(make('low-conversion','Taxa de conversão em atenção',`A conversão por desfecho está em ${perf.outcomeConversion.toFixed(1)}%.`,{category:'Comercial',priority:'medium',link:'performance',score:50,evidence:[{type:'dashboard',won:perf.won,lost:perf.lost,conversion:perf.outcomeConversion}]}))
 buildCausalAnalysis(data,now).forEach((finding)=>{if(finding.id==='revenue-drop')alerts.push(make('forecast-revenue-drop','Previsão de queda de receita',finding.statement,{category:'Intelligence',priority:'high',link:'intelligence',score:85,evidence:finding.evidence.map((value)=>({type:'evidencia',value}))}))})
 return [...new Map(alerts.map((alert)=>[alert.fingerprint,alert])).values()].sort((a,b)=>b.score-a.score)
}
export function pulseSummary(alerts=[]){const activeAlerts=alerts.filter((a)=>!['resolved','ignored'].includes(a.status)&&(!a.snoozed_until||new Date(a.snoozed_until)<=new Date()));const counts={critical:0,high:0,medium:0,low:0,informational:0};activeAlerts.forEach((a)=>{counts[a.priority]=(counts[a.priority]||0)+1});const health=(category)=>Math.max(0,100-activeAlerts.filter((a)=>category.includes(a.category)).reduce((sum,a)=>sum+Math.min(a.score||0,30),0));return{counts,total:activeAlerts.length,scores:{financial:health(['Financeiro']),commercial:health(['Comercial','Clientes']),operational:health(['Operação','Serviços','Contratos']),team:health(['Equipe']),general:Math.round((health(['Financeiro'])+health(['Comercial','Clientes'])+health(['Operação','Serviços','Contratos'])+health(['Equipe']))/4)}}}
