import {
  BookUser,
  Bot,
  ClipboardCheck,
  CalendarDays,
  CalendarRange,
  Columns3,
  CreditCard,
  FileText,
  Inbox,
  LayoutDashboard,
  MessageCircle,
  Plug,
  ReceiptText,
  Settings2,
  History,
  ListTodo,
  Users,
  WalletCards,
} from "lucide-react";

export const NAVIGATION_GROUPS = [
  {
    id: "overview",
    label: "Operação",
    links: [
      { id: "operations-today", label: "Meu Dia", icon: CalendarDays, supabaseOnly: true, roles: ['admin','manager','operations','commercial'] },
      { id: "operations-week", label: "Semana", icon: CalendarRange, supabaseOnly: true, roles: ['admin','manager','operations','commercial'] },
      { id: "operations-calendar", label: "Calendário", icon: CalendarDays, supabaseOnly: true, roles: ['admin','manager','operations','commercial'] },
      { id: "operations-backlog", label: "Backlog", icon: ListTodo, supabaseOnly: true, roles: ['admin','manager','operations','commercial'] },
      { id: "operations-history", label: "Histórico", icon: History, supabaseOnly: true, roles: ['admin','manager','operations','commercial'] },
      { id: "inbox", label: "Caixa de entrada", icon: Inbox, supabaseOnly: true },
      { id: "collections", label: "Cobranças", icon: ReceiptText, supabaseOnly: true, roles: ['admin','manager','finance'] },
      { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
    ],
  },
  {
    id: "crm",
    label: "CRM",
    links: [
      { id: "commercial", label: "Comercial", icon: Columns3, supabaseOnly: true },
      { id: "clients", label: "Clientes", icon: Users },
      { id: "contacts", label: "Contatos", icon: BookUser, supabaseOnly: true },
      { id: "contracts", label: "Contratos", icon: ClipboardCheck },
    ],
  },
  {
    id: "communication",
    label: "Comunicação",
    links: [
      { id: "automations", label: "Automações", icon: Bot, supabaseOnly: true },
      { id: "templates", label: "Templates", icon: FileText, supabaseOnly: true },
      {
        id: "whatsapp",
        label: "WhatsApp",
        icon: MessageCircle,
        supabaseOnly: true,
      },
    ],
  },
  {
    id: "finance",
    label: "Financeiro",
    roles: ['admin','manager','finance'],
    links: [
      { id: "finance-summary", label: "Visão Geral", icon: WalletCards },
      { id: "finance-month", label: "Calendário Financeiro", icon: CalendarDays },
      { id: "finance", label: "Receitas", icon: ReceiptText },
      { id: "accounts-payable", label: "Despesas", icon: CreditCard },
      { id: "financial-debts", label: "Dívidas", icon: ReceiptText },
      { id: "freelance-cash", label: "Caixa Freela", icon: WalletCards },
      { id: "financial-goals", label: "Metas & Reservas", icon: CalendarRange },
      { id: "monthly-closing", label: "Fechamento Mensal", icon: ClipboardCheck },
    ],
  },
  {
    id: "administration",
    label: "Administração",
    links: [
      { id: "team", label: "Equipe", icon: Users, supabaseOnly: true, adminOnly: true },
      { id: "integrations", label: "Integrações", icon: Plug, adminOnly: true },
      {
        id: "organization-settings",
        label: "Configurações",
        icon: Settings2,
        adminOnly: true,
      },
    ],
  },
];
