import {useEffect,useState} from 'react'
import {RefreshCw,Trash2} from 'lucide-react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {getProposalDeletionImpact,listDeletedProposals,permanentlyDeleteProposal,restoreProposal} from '../services/data/proposalsRepository'
import {contractErrorMessage,getContractDeletionImpact,listArchivedContracts,permanentlyDeleteContract,restoreContract} from '../services/data/contractsRepository'
import {PermanentDeletionModal} from './PermanentDeletionModal'
import {useAuth} from '../contexts/AuthContext'

export function CommercialTrashPage(){
  const {canWrite,isAdmin}=useAuth(),[scope,setScope]=useState('proposals'),[proposals,setProposals]=useState([]),[contracts,setContracts]=useState([]),[deletion,setDeletion]=useState(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const load=async()=>{try{const [proposalRows,contractRows]=await Promise.all([listDeletedProposals(),listArchivedContracts()]);setProposals(proposalRows);setContracts(contractRows)}catch(cause){setError(contractErrorMessage(cause))}}
  useEffect(()=>{Promise.all([listDeletedProposals(),listArchivedContracts()]).then(([proposalRows,contractRows])=>{setProposals(proposalRows);setContracts(contractRows)}).catch((cause)=>setError(contractErrorMessage(cause)))},[])
  async function restoreProposalRow(row){setLoading(true);try{await restoreProposal(row);setMessage('Proposta restaurada.');await load()}catch(cause){setError(cause.message)}finally{setLoading(false)}}
  async function restoreContractRow(row){setLoading(true);try{await restoreContract(row.id);setMessage('Contrato restaurado.');await load()}catch(cause){setError(contractErrorMessage(cause))}finally{setLoading(false)}}
  async function prepareProposal(row){setLoading(true);try{setDeletion({type:'proposal',entity:row,impact:await getProposalDeletionImpact(row)})}catch(cause){setError(cause.message)}finally{setLoading(false)}}
  async function prepareContract(row){setLoading(true);try{setDeletion({type:'contract',entity:row,impact:await getContractDeletionImpact(row.id)})}catch(cause){setError(contractErrorMessage(cause))}finally{setLoading(false)}}
  async function remove(){setLoading(true);try{if(deletion.type==='proposal')await permanentlyDeleteProposal(deletion.entity);else await permanentlyDeleteContract(deletion.entity.id);setMessage(`${deletion.type==='proposal'?'Proposta':'Contrato'} excluído permanentemente.`);setDeletion(null);await load()}catch(cause){setError(deletion.type==='contract'?contractErrorMessage(cause):cause.message)}finally{setLoading(false)}}
  const rows=scope==='proposals'?proposals:contracts
  return <div><PageHeader eyebrow="Comercial" title="Lixeira comercial" description="Itens arquivados permanecem recuperáveis até uma exclusão administrativa protegida."/>{message&&<FeedbackMessage type="success">{message}</FeedbackMessage>}{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}<nav className="contract-scope-tabs" aria-label="Tipo de registro"><button className={scope==='proposals'?'active':''} onClick={()=>setScope('proposals')}>Propostas</button><button className={scope==='contracts'?'active':''} onClick={()=>setScope('contracts')}>Contratos</button></nav><div className="table-scroll"><table className="proposal-list-table"><thead><tr><th>{scope==='proposals'?'Proposta':'Contrato'}</th><th>Cliente</th><th>Arquivado em</th><th>Ações</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td>{scope==='proposals'?row.title:row.contractNumber}</td><td>{scope==='proposals'?row.companyName:row.clientName}</td><td>{new Date(row.deletedAt||row.deleted_at).toLocaleString('pt-BR')}</td><td><div className="row-actions">{canWrite&&<button className="button secondary" disabled={loading} onClick={()=>scope==='proposals'?restoreProposalRow(row):restoreContractRow(row)}><RefreshCw size={14}/>Restaurar</button>}{isAdmin&&<button className="button secondary danger-text" disabled={loading} onClick={()=>scope==='proposals'?prepareProposal(row):prepareContract(row)}><Trash2 size={14}/>Excluir permanentemente</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan="4">Nenhum item arquivado.</td></tr>}</tbody></table></div>{deletion&&<PermanentDeletionModal entityName={deletion.type==='proposal'?deletion.entity.title:deletion.entity.clientName||deletion.entity.contractNumber} impact={deletion.impact} blockedMessage={deletion.type==='proposal'?'Esta proposta está vinculada a um contrato e não pode ser excluída permanentemente. Arquive-a.':'Este contrato possui recebimentos confirmados e não pode ser excluído permanentemente.'} loading={loading} onClose={()=>setDeletion(null)} onConfirm={remove}/>}</div>
}
