import { useMemo } from 'react'

const labels={company_name:'Empresa',trade_name:'Nome comercial',contact_name:'Contato',document_number:'CPF ou CNPJ',email:'E-mail',phone:'Telefone',website:'Site',instagram:'Instagram',segment:'Segmento',billing_contact_name:'Contato financeiro',billing_contact_email:'E-mail financeiro',billing_contact_phone:'Telefone financeiro',billing_contact_role:'Cargo do contato financeiro',proposal_number:'Número da proposta',title:'Título',status:'Status',sent_at:'Data de envio',valid_until:'Validade',setup_value:'Setup',monthly_value:'Valor mensal',total_value:'Valor total',contract_term_months:'Prazo do contrato em meses',responsible:'Responsável',lead_source:'Origem do lead',notes:'Observações',contract_number:'Número do contrato',signed:'Assinado',signed_at:'Data de assinatura',start_date:'Início',end_date:'Fim',minimum_term_months:'Permanência mínima em meses',billing_day:'Dia de cobrança',auto_renew:'Renovação automática',renewal_status:'Status da renovação',termination_date:'Data de encerramento',termination_reason:'Motivo do encerramento',setup_received_amount:'Setup recebido',setup_received_at:'Data do recebimento do setup',setup_payment_method:'Forma de pagamento do setup',installment_plan:'Parcelamento',payment_method:'Forma de pagamento',payment_due_rule:'Regra de vencimento',service_name:'Serviço',service_category:'Categoria',billing_type:'Tipo de cobrança',quantity:'Quantidade',unit_price:'Valor unitário',one_time_value:'Valor único',duration_months:'Duração em meses',minimum_term:'Permanência mínima',cancellation_notice_days:'Aviso prévio em dias',early_termination_penalty:'Multa de rescisão',late_fee_percent:'Multa por atraso (%)',monthly_interest_percent:'Juros mensais (%)',adjustment_index:'Índice de reajuste',adjustment_percent:'Reajuste (%)',renewal_rule:'Regra de renovação'}
const sensitive=new Set(['status','setup_value','monthly_value','total_value','sent_at','valid_until','signed','signed_at','start_date','end_date','billing_day','setup_received_amount','setup_received_at'])
const values=new Set(['setup_value','monthly_value','total_value','unit_price','one_time_value','quantity'])
const dates=new Set(['sent_at','valid_until','signed_at','start_date','end_date','termination_date','setup_received_at'])
const confidence=(number)=>number>=.85?['Alta','high']:number>=.6?['Média','medium']:['Baixa','low']

const proposalStatuses={draft:'Rascunho',sent:'Enviada',viewed:'Visualizada',negotiating:'Em negociação',won:'Ganha',lost:'Perdida',expired:'Expirada',cancelled:'Cancelada'}
const contractStatuses={draft:'Rascunho',pending_signature:'Aguardando assinatura',active:'Ativo',expired:'Vencido',terminated:'Encerrado',cancelled:'Cancelado'}
function Field({name,field,onChange,statusKind}){
  const [confidenceLabel,level]=confidence(Number(field?.confidence||0)),value=field?.value??''
  const statusOptions=statusKind==='proposal'?proposalStatuses:contractStatuses
  const input=name==='status'&&statusKind?<select value={value} onChange={(event)=>onChange(event.target.value)}><option value="">Campo não identificado</option>{Object.entries(statusOptions).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>:typeof value==='boolean'?<select value={String(value)} onChange={(event)=>onChange(event.target.value==='true')}><option value="true">Sim</option><option value="false">Não</option></select>:<input type={typeof value==='number'?'number':dates.has(name)?'date':'text'} step={typeof value==='number'?'0.01':undefined} value={value} placeholder="Campo não identificado" onChange={(event)=>onChange(typeof value==='number'&&event.target.value!==''?Number(event.target.value):event.target.value)}/>
  return <label className={`extraction-field confidence-${level}${field?.needsReview||sensitive.has(name)?' needs-review':''}`}><span>{labels[name]||name}<em>Confiança {confidenceLabel}</em></span>{input}<small>{field?.sourceExcerpt||'Nenhum trecho de origem identificado.'}</small></label>
}

function Section({title,data,onChange,filter,statusKind}){
  const entries=Object.entries(data||{}).filter(([name])=>!filter||filter(name))
  if(!entries.length)return null
  return <section className="review-section"><h3>{title}</h3><div className="review-fields">{entries.map(([name,field])=><Field key={name} name={name} field={field} statusKind={statusKind} onChange={(value)=>onChange(name,value)}/>)}</div></section>
}

export function CommercialDocumentReview({analysis,result,reviewed,onReviewedChange,duplicates,clientAction,setClientAction,clientId,setClientId,entityAction,setEntityAction,entityId,setEntityId,confirmations,setConfirmations,onConfirm,onCancel,saving}){
  const isProposal=result.documentType==='proposal'
  const isOther=result.documentType==='other'
  const typeLabel={proposal:'Proposta',signed_contract:'Contrato assinado',unsigned_contract:'Contrato sem assinatura',amendment:'Aditivo',other:'Outro'}[result.documentType]
  const update=(section,name,value,index)=>onReviewedChange((current)=>{const next=structuredClone(current);const target=index==null?next[section]:next[section][index];target[name]={...target[name],value,needsReview:false};return next})
  const clientOptions=duplicates.clientMatches||[],entityOptions=duplicates.entityMatches||[]
  const requiredConfirmations=useMemo(()=>[['status','Status'],['values','Valores'],['dates','Datas'],['signature','Assinatura'],['setup_received','Setup recebido'],['billing_day','Dia de cobrança'],['total_value','Total do contrato']],[])
  return <div className="commercial-review"><section className="dashboard-panel review-document"><div><span className="eyebrow">Documento</span><h2>Revisar dados extraídos</h2><p>{analysis.file_name} · {typeLabel}</p></div><span className={`confidence-summary confidence-${confidence(result.confidence)[1]}`}>Confiança {confidence(result.confidence)[0]} · {Math.round(result.confidence*100)}%</span></section>
    <Section title="Cliente" data={reviewed.client} onChange={(name,value)=>update('client',name,value)}/>
    {!isOther&&<><Section title={isProposal?'Proposta':'Contrato'} data={isProposal?reviewed.proposal:reviewed.contract} statusKind={isProposal?'proposal':'contract'} filter={(name)=>!values.has(name)&&!dates.has(name)} onChange={(name,value)=>update(isProposal?'proposal':'contract',name,value)}/><Section title="Valores" data={isProposal?reviewed.proposal:reviewed.contract} filter={(name)=>values.has(name)} onChange={(name,value)=>update(isProposal?'proposal':'contract',name,value)}/><Section title="Datas" data={isProposal?reviewed.proposal:reviewed.contract} filter={(name)=>dates.has(name)} onChange={(name,value)=>update(isProposal?'proposal':'contract',name,value)}/><section className="review-section"><h3>Serviços</h3>{reviewed.services?.map((service,index)=><div className="review-service" key={index}><strong>Serviço {index+1}</strong><div className="review-fields">{Object.entries(service).map(([name,field])=><Field key={name} name={name} field={field} onChange={(value)=>update('services',name,value,index)}/>)}</div></div>)}{!reviewed.services?.length&&<p>Campo não identificado.</p>}</section>{!isProposal&&<><Section title="Financeiro" data={reviewed.financial} onChange={(name,value)=>update('financial',name,value)}/><Section title="Cláusulas" data={reviewed.clauses} onChange={(name,value)=>update('clauses',name,value)}/></>}</>}
    <section className="review-section review-warnings"><h3>Avisos</h3>{[...(result.warnings||[]),...(result.missingFields||[]).map((item)=>`Campo ausente: ${item}`),...(result.conflicts||[])].map((item,index)=><p key={index}>{item}</p>)}{!result.warnings?.length&&!result.missingFields?.length&&!result.conflicts?.length&&<p>Nenhum aviso identificado.</p>}</section>
    <section className="review-section"><h3>Duplicidades</h3><p><strong>{duplicates.classification==='sem conflito'?'Sem conflito':duplicates.classification==='duplicidade confirmada'?'Duplicidade confirmada':'Possível duplicidade'}</strong></p>{duplicates.files?.map((row)=><p key={`${row.item.id}-${row.reasons[0]}`}>Arquivo existente: {row.item.file_name} — {row.reasons.join(', ')}</p>)}<fieldset><legend>Cliente</legend><label><input type="radio" checked={clientAction==='create'} onChange={()=>{setClientAction('create');setClientId('')}}/> Criar novo</label>{clientOptions.map((row)=><label key={row.item.id}><input type="radio" checked={clientAction==='link'&&clientId===row.item.id} onChange={()=>{setClientAction('link');setClientId(row.item.id)}}/> Vincular a {row.item.company_name} — {row.reasons.join(', ')}</label>)}</fieldset>{!isOther&&<fieldset><legend>{isProposal?'Proposta':'Contrato'}</legend><label><input type="radio" checked={entityAction==='create'} onChange={()=>{setEntityAction('create');setEntityId('')}}/> Criar novo</label>{entityOptions.map((row)=><label key={row.item.id}><input type="radio" checked={entityAction==='link'&&entityId===row.item.id} onChange={()=>{setEntityAction('link');setEntityId(row.item.id)}}/> Vincular ao registro existente — {row.reasons.join(', ')}</label>)}<label><input type="radio" checked={entityAction==='cancel'} onChange={()=>setEntityAction('cancel')}/> Cancelar importação</label></fieldset>}</section>
    <section className="review-section sensitive-confirmations"><h3>Confirmações obrigatórias</h3><p>Revise e confirme explicitamente os campos sensíveis. Nenhum pagamento ou parcela será criado.</p>{requiredConfirmations.map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(confirmations[key])} onChange={(event)=>setConfirmations({...confirmations,[key]:event.target.checked})}/> Confirmo a revisão de: {label}</label>)}</section>
    <div className="review-actions"><button className="button secondary" type="button" onClick={onCancel} disabled={saving}>Cancelar</button><button className="button" type="button" onClick={onConfirm} disabled={saving||entityAction==='cancel'}>{saving?'Confirmando…':'Confirmar importação'}</button></div>
  </div>
}
