import { useMemo,useState } from 'react'
import { ChevronDown } from 'lucide-react'
import { DOCUMENT_TYPE_LABELS,confirmationsForDocument,humanizeTechnicalValue,monthlyValueComposition,validateReview } from '../lib/commercialDocumentReview'

const labels={company_name:'Empresa',trade_name:'Nome comercial',contact_name:'Contato',document_number:'CNPJ ou CPF',email:'E-mail',phone:'Telefone',website:'Site',instagram:'Instagram',segment:'Segmento',billing_contact_name:'Contato financeiro',billing_contact_email:'E-mail financeiro',billing_contact_phone:'Telefone financeiro',billing_contact_role:'Cargo financeiro',proposal_number:'Número da proposta',title:'Título',status:'Status',sent_at:'Data de envio',valid_until:'Validade',setup_value:'Setup',monthly_value:'Valor mensal',total_value:'Valor total',contract_term_months:'Prazo em meses',responsible:'Responsável',lead_source:'Origem do lead',notes:'Observações',contract_number:'Número do contrato',signed:'Assinado',signed_at:'Data de assinatura',start_date:'Início',end_date:'Fim',minimum_term_months:'Permanência mínima em meses',billing_day:'Dia de cobrança',auto_renew:'Renovação automática',renewal_status:'Status da renovação',termination_date:'Data de encerramento',termination_reason:'Motivo do encerramento',setup_received_amount:'Setup recebido',setup_received_at:'Data do recebimento',setup_payment_method:'Forma de pagamento do setup',installment_plan:'Parcelamento',payment_method:'Forma de pagamento',payment_due_rule:'Regra de vencimento',service_name:'Serviço',service_category:'Categoria',billing_type:'Tipo de cobrança',quantity:'Quantidade',unit_price:'Valor unitário',one_time_value:'Valor único',duration_months:'Duração em meses',minimum_term:'Permanência mínima',cancellation_notice_days:'Aviso prévio em dias',early_termination_penalty:'Multa de rescisão',late_fee_percent:'Multa por atraso (%)',monthly_interest_percent:'Juros mensais (%)',adjustment_index:'Índice de reajuste',adjustment_percent:'Reajuste (%)',renewal_rule:'Regra de renovação'}
const values=new Set(['setup_value','monthly_value','total_value','unit_price','one_time_value','quantity'])
const dates=new Set(['sent_at','valid_until','signed_at','start_date','end_date','termination_date','setup_received_at'])
const booleans=new Set(['signed','auto_renew'])
const numbers=new Set([...values,'contract_term_months','minimum_term_months','billing_day','duration_months','cancellation_notice_days','late_fee_percent','monthly_interest_percent','adjustment_percent','setup_received_amount'])
const proposalStatuses={draft:'Rascunho',sent:'Enviada',viewed:'Visualizada',negotiating:'Em negociação',won:'Ganha',lost:'Perdida',expired:'Expirada',cancelled:'Cancelada'}
const contractStatuses={draft:'Rascunho',pending_signature:'Aguardando assinatura',active:'Ativo',expired:'Vencido',terminated:'Encerrado',cancelled:'Cancelado'}
const billingTypes={one_time:'Pagamento único',monthly:'Mensal',recurring:'Recorrente',included:'Incluso',project:'Projeto',hybrid:'Híbrido'}
const categories={'social media':'Social Media','mídia paga e site':'Mídia paga e ajustes no site','branding e ativações':'Branding e ativações','relatórios e business review':'Relatórios e análise executiva',onboarding:'Onboarding'}
const confidence=(number)=>number>=.85?['Alta','high']:number>=.6?['Média','medium']:['Baixa','low']
const money=(value)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)

function Accordion({title,children,defaultOpen=true,badge}){return <details className="review-accordion" defaultOpen={defaultOpen}><summary><span>{title}</span>{badge&&<small>{badge}</small>}<ChevronDown size={16}/></summary><div className="review-accordion-content">{children}</div></details>}

function Field({name,field,onChange,statusKind}){
  const [confidenceLabel,level]=confidence(Number(field?.confidence||0)),value=field?.value??''
  let input
  if(name==='status'&&statusKind){const options=statusKind==='proposal'?proposalStatuses:contractStatuses;input=<select value={value} onChange={(event)=>onChange(event.target.value)}><option value="">Sem status identificado</option>{Object.entries(options).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}
  else if(name==='billing_type')input=<select value={value} onChange={(event)=>onChange(event.target.value)}><option value="">Não informado</option>{Object.entries(billingTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>
  else if(name==='service_category'&&value){const options={...categories,[value]:humanizeTechnicalValue(value)};input=<select value={value} onChange={(event)=>onChange(event.target.value)}>{Object.entries(options).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}
  else if(booleans.has(name))input=<select value={value===''?'':String(value)} onChange={(event)=>onChange(event.target.value===''?null:event.target.value==='true')}><option value="">Não identificado</option><option value="true">Sim</option><option value="false">Não</option></select>
  else input=<input type={numbers.has(name)?'number':dates.has(name)?'date':'text'} step={numbers.has(name)?'0.01':undefined} value={value} onChange={(event)=>onChange(numbers.has(name)&&event.target.value!==''?Number(event.target.value):event.target.value)}/>
  return <label className={`extraction-field confidence-${level}${field?.needsReview?' needs-review':''}`}><span>{labels[name]||name}<em>Confiança {confidenceLabel}</em></span>{input}{field?.valueOrigin&&values.has(name)&&<small className="value-origin">{field.valueOrigin==='explicit'?'Valor informado no documento':field.valueOrigin==='calculated'?'Valor calculado pelos serviços':'Campo não identificado'}</small>}{field?.sourceExcerpt&&<details className="source-excerpt"><summary>Ver trecho do documento</summary><p>{field.sourceExcerpt}</p></details>}</label>
}

function FieldsSection({title,data,onChange,filter,statusKind,defaultOpen=false}){
  const [showMissing,setShowMissing]=useState(false),entries=Object.entries(data||{}).filter(([name])=>!filter||filter(name)),missing=entries.filter(([,field])=>field?.value==null||field.value===''),found=entries.filter(([,field])=>field?.value!=null&&field.value!=='')
  const low=found.some(([,field])=>Number(field.confidence)<.6),open=defaultOpen||low||missing.length>0
  return <Accordion title={title} defaultOpen={open} badge={low?'Revisar':undefined}><div className="review-fields">{[...found,...(showMissing?missing:[])].map(([name,field])=><Field key={name} name={name} field={field} statusKind={statusKind} onChange={(value)=>onChange(name,value)}/>)}</div>{missing.length>0&&<div className="missing-fields"><strong>Campos não encontrados no documento</strong><p>{missing.map(([name])=>labels[name]||name).join(' · ')}</p><button type="button" className="button secondary small" onClick={()=>setShowMissing(!showMissing)}>{showMissing?'Ocultar campos':'Preencher agora'}</button></div>}</Accordion>
}

function DuplicateReview({duplicates,isOther,isProposal,clientAction,setClientAction,clientId,setClientId,entityAction,setEntityAction,entityId,setEntityId,relatedProposals,relatedProposalId,setRelatedProposalId}){
  return <Accordion title="Duplicidades" defaultOpen={duplicates.classification!=='sem conflito'} badge={duplicates.classification}><p><strong>{duplicates.classification==='sem conflito'?'Sem conflito':duplicates.classification==='duplicidade confirmada'?'Duplicidade confirmada':'Possível duplicidade'}</strong></p>{duplicates.files?.map((row)=><p key={`${row.item.id}-${row.reasons[0]}`}>{row.item.file_name} — {row.reasons.join(', ')}</p>)}<fieldset><legend>Cliente</legend><label><input type="radio" checked={clientAction==='create'} onChange={()=>{setClientAction('create');setClientId('')}}/> Criar novo</label>{duplicates.clientMatches?.map((row)=><label key={row.item.id}><input type="radio" checked={clientAction==='link'&&clientId===row.item.id} onChange={()=>{setClientAction('link');setClientId(row.item.id)}}/> Vincular a {row.item.company_name} — {row.reasons.join(', ')}</label>)}</fieldset>{!isOther&&<fieldset><legend>{isProposal?'Proposta':'Contrato'}</legend><label><input type="radio" checked={entityAction==='create'} onChange={()=>{setEntityAction('create');setEntityId('')}}/> Criar novo</label>{duplicates.entityMatches?.map((row)=><label key={row.item.id}><input type="radio" checked={entityAction==='link'&&entityId===row.item.id} onChange={()=>{setEntityAction('link');setEntityId(row.item.id)}}/> Vincular ao registro existente — {row.reasons.join(', ')}</label>)}</fieldset>}{!isOther&&!isProposal&&entityAction==='create'&&<label className="related-proposal">Proposta relacionada<select value={relatedProposalId} onChange={(event)=>setRelatedProposalId(event.target.value)}><option value="">Sem proposta relacionada</option>{relatedProposals.map((proposal)=><option key={proposal.id} value={proposal.id}>{proposal.title||'Sem título'}</option>)}</select></label>}</Accordion>
}

export function CommercialDocumentReview({analysis,result,reviewed,onReviewedChange,onDocumentTypeChange,duplicates,clientAction,setClientAction,clientId,setClientId,entityAction,setEntityAction,entityId,setEntityId,relatedProposalId,setRelatedProposalId,confirmations,setConfirmations,onConfirm,onCancel,saving,importStage}){
  const type=result.documentType,isProposal=type==='proposal',isOther=type==='other',isAmendment=type==='amendment',isContract=['signed_contract','unsigned_contract'].includes(type)
  const update=(section,name,value,index)=>onReviewedChange((current)=>{const next=structuredClone(current),target=index==null?next[section]:next[section][index];target[name]={...target[name],value,needsReview:false};return next})
  const confirmationRows=useMemo(()=>confirmationsForDocument(type),[type]),composition=monthlyValueComposition(reviewed)
  const validation=validateReview({type,reviewed,clientAction,clientId,entityAction,entityId,confirmations})
  const confirmAll=()=>setConfirmations(Object.fromEntries(confirmationRows.map(([key])=>[key,true])))
  const actionLabel=isProposal?'Confirmar e importar proposta':isContract?'Confirmar e importar contrato':isAmendment?'Confirmar e vincular aditivo':'Salvar documento'
  const proposalData=reviewed.proposal||{},contractData=reviewed.contract||{}
  return <div className="commercial-review" aria-label={`Revisão de ${analysis.file_name}`}><div className="review-main-column">
    <FieldsSection title="Cliente" data={reviewed.client} defaultOpen onChange={(name,value)=>update('client',name,value)}/>
    {isProposal&&<><FieldsSection title="Dados da proposta" data={proposalData} statusKind="proposal" defaultOpen filter={(name)=>!values.has(name)&&!dates.has(name)&&name!=='notes'} onChange={(name,value)=>update('proposal',name,value)}/><FieldsSection title="Valores" data={proposalData} filter={(name)=>values.has(name)} onChange={(name,value)=>update('proposal',name,value)}/><FieldsSection title="Datas" data={proposalData} filter={(name)=>dates.has(name)} onChange={(name,value)=>update('proposal',name,value)}/></>}
    {(isContract||isAmendment)&&<><FieldsSection title={isAmendment?'Campos alterados':'Contrato'} data={contractData} statusKind="contract" defaultOpen filter={(name)=>!values.has(name)&&!dates.has(name)&&name!=='notes'} onChange={(name,value)=>update('contract',name,value)}/><FieldsSection title={isAmendment?'Novos valores':'Valores'} data={contractData} filter={(name)=>values.has(name)} onChange={(name,value)=>update('contract',name,value)}/><FieldsSection title={isAmendment?'Novo prazo':'Vigência'} data={contractData} filter={(name)=>dates.has(name)} onChange={(name,value)=>update('contract',name,value)}/></>}
    {!isOther&&<Accordion title={isAmendment?'Novos serviços':'Serviços'} defaultOpen><div className="review-services">{reviewed.services?.map((service,index)=><article className="review-service" key={index}><strong>Serviço {index+1}</strong><div className="review-fields">{Object.entries(service).filter(([,field])=>field?.value!=null&&field.value!=='').map(([name,field])=><Field key={name} name={name} field={field} onChange={(value)=>update('services',name,value,index)}/>)}</div></article>)}</div>{!reviewed.services?.length&&<p>Nenhum serviço identificado.</p>}</Accordion>}
    {composition.calculated>0&&composition.origin==='calculated'&&<section className="monthly-composition"><strong>Valor mensal calculado pela soma dos serviços recorrentes.</strong>{composition.services.map((service,index)=><p key={service.name}>{index?'+ ':''}{service.name}: {money(service.value)}</p>)}<b>= {money(composition.calculated)}/mês</b></section>}
    {isContract&&<><FieldsSection title="Financeiro contratual" data={reviewed.financial} onChange={(name,value)=>update('financial',name,value)}/><FieldsSection title="Cláusulas" data={reviewed.clauses} onChange={(name,value)=>update('clauses',name,value)}/></>}
    <FieldsSection title="Observações" data={isProposal?proposalData:contractData} filter={(name)=>name==='notes'} onChange={(name,value)=>update(isProposal?'proposal':'contract',name,value)}/>
  </div><aside className="review-side-column"><section className="review-summary"><span className="eyebrow">Classificação</span><h2>Documento identificado como: {DOCUMENT_TYPE_LABELS[type]}</h2><label>Alterar tipo do documento<select value={type} onChange={(event)=>onDocumentTypeChange(event.target.value)}>{Object.entries(DOCUMENT_TYPE_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><span className={`confidence-summary confidence-${confidence(result.documentTypeConfidence??result.confidence)[1]}`}>Confiança {confidence(result.documentTypeConfidence??result.confidence)[0]} · {Math.round((result.documentTypeConfidence??result.confidence)*100)}%</span>{result.classificationReasons?.map((reason)=><p key={reason}>{reason}</p>)}</section>
    <Accordion title="Avisos" defaultOpen={(result.warnings?.length||result.classificationWarnings?.length)>0}>{[...(result.classificationWarnings||[]),...(result.warnings||[]),...(result.conflicts||[])].map((warning)=><p key={warning}>{warning}</p>)}{!result.warnings?.length&&!result.classificationWarnings?.length&&!result.conflicts?.length&&<p>Nenhum aviso identificado.</p>}<div className="missing-fields"><strong>Campos não encontrados no documento</strong><p>{result.missingFields?.join(' · ')||'Nenhum.'}</p></div></Accordion>
    <DuplicateReview duplicates={duplicates} isOther={isOther} isProposal={isProposal} clientAction={clientAction} setClientAction={setClientAction} clientId={clientId} setClientId={setClientId} entityAction={entityAction} setEntityAction={setEntityAction} entityId={entityId} setEntityId={setEntityId} relatedProposals={duplicates.relatedProposals||[]} relatedProposalId={relatedProposalId} setRelatedProposalId={setRelatedProposalId}/>
    <Accordion title="Confirmações" defaultOpen badge={!validation.valid?'Pendente':'Pronto'}><div className="sensitive-confirmations">{confirmationRows.map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(confirmations[key])} onChange={(event)=>setConfirmations({...confirmations,[key]:event.target.checked})}/>{label}</label>)}<button type="button" className="button secondary small" disabled={validation.missing.some((item)=>item!=='Confirmações obrigatórias')} onClick={confirmAll}>Confirmar todos os campos revisados</button>{!validation.valid&&<p>Falta revisar: {validation.missing.join(', ')}.</p>}</div></Accordion>
    <div className="import-readiness" aria-live="polite"><strong>{saving?importStage:'Pronto para importar'}</strong></div>
    <div className="review-actions"><button className="button secondary" type="button" onClick={onCancel} disabled={saving}>Cancelar</button><button className="button" type="button" onClick={onConfirm} disabled={saving||!validation.valid}>{saving?'Importando…':actionLabel}</button></div>
  </aside></div>
}
