import {useEffect,useState} from 'react'
import {previewContractInstallments} from '../services/data/contractsRepository'
const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function ContractBillingPreviewModal({contract,onClose,onConfirm}){
  const [includeHistory,setIncludeHistory]=useState(false),[preview,setPreview]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  useEffect(()=>{previewContractInstallments(contract.id,includeHistory).then(setPreview).catch((cause)=>setError(cause.message)).finally(()=>setLoading(false))},[contract.id,includeHistory])
  function changeHistory(checked){setLoading(true);setError('');setIncludeHistory(checked)}
  return <div className="modal-overlay" role="presentation"><section className="setup-payment-modal" role="dialog" aria-modal="true" aria-labelledby="billing-preview-title"><h2 id="billing-preview-title">Ativar contrato e gerar cobranças</h2>{error&&<p className="feedback-message error">{error}</p>}{loading&&<p>Calculando cobranças…</p>}{preview&&<><dl><div><dt>Cliente</dt><dd>{contract.clients?.company_name}</dd></div><div><dt>Contrato</dt><dd>{contract.contract_number||'Sem número'}</dd></div><div><dt>Mensalidade</dt><dd>{money(preview.monthlyValue)}</dd></div><div><dt>Data inicial</dt><dd>{preview.startDate}</dd></div><div><dt>Data final</dt><dd>{preview.endDate||'Sem data final'}</dd></div><div><dt>Prazo</dt><dd>{preview.termMonths?`${preview.termMonths} meses`:'Próximas 3 cobranças'}</dd></div><div><dt>Dia de cobrança</dt><dd>{preview.billingDay}</dd></div><div><dt>Quantidade</dt><dd>{preview.installmentCount} parcelas</dd></div><div><dt>Primeiro vencimento</dt><dd>{preview.firstDueDate||'Nenhuma cobrança futura'}</dd></div><div><dt>Último vencimento</dt><dd>{preview.lastDueDate||'Nenhuma cobrança futura'}</dd></div><div><dt>Valor total previsto</dt><dd>{money(preview.totalExpected)}</dd></div></dl>{preview.hasHistorical&&<label className="strong-confirm"><input type="checkbox" checked={includeHistory} onChange={(event)=>changeHistory(event.target.checked)}/>Incluir também as competências históricas anteriores a este mês.</label>}</>}<footer><button className="button secondary" onClick={onClose}>Cancelar</button><button className="button" disabled={!preview||loading||preview.installmentCount===0} onClick={()=>onConfirm(includeHistory)}>Confirmar ativação e geração</button></footer></section></div>
}
