import {useEffect,useState} from 'react'
import {previewContractInstallments} from '../services/data/contractsRepository'
const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function ContractBillingPreviewModal({contract,onClose,onConfirm}){
  const [includeHistory,setIncludeHistory]=useState(false),[preview,setPreview]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[confirming,setConfirming]=useState(false)
  useEffect(()=>{previewContractInstallments(contract.id,includeHistory).then(setPreview).catch((cause)=>setError(cause.message)).finally(()=>setLoading(false))},[contract.id,includeHistory])
  function changeHistory(checked){setLoading(true);setError('');setIncludeHistory(checked)}
  async function confirm(){if(confirming)return;setConfirming(true);setError('');try{await onConfirm(includeHistory)}catch(cause){setError(cause.message);setConfirming(false)}}
  const hasHistory=preview?.hasHistorical
  return <div className="modal-overlay" role="presentation"><section className="setup-payment-modal" role="dialog" aria-modal="true" aria-labelledby="billing-preview-title"><h2 id="billing-preview-title">{preview?.alreadyActive?'Gerar competências faltantes':'Ativar contrato e gerar cobranças'}</h2>{error&&<p className="feedback-message error">{error}</p>}{loading&&<p>Calculando cobranças…</p>}{preview&&<><dl><div><dt>Cliente</dt><dd>{contract.clients?.company_name}</dd></div><div><dt>Contrato</dt><dd>{contract.contract_number||'Sem número'}</dd></div><div><dt>Setup</dt><dd>{money(preview.setupValue)}</dd></div><div><dt>Mensalidade</dt><dd>{money(preview.monthlyValue)}</dd></div><div><dt>Competências</dt><dd>{preview.firstCompetence||'—'} → {preview.lastCompetence||'—'}</dd></div><div><dt>Quantidade mensal</dt><dd>{preview.installmentCount} parcelas</dd></div><div><dt>Vencidas</dt><dd>{preview.overdueCount}</dd></div><div><dt>Futuras</dt><dd>{preview.futureCount}</dd></div><div><dt>Valor total previsto</dt><dd>{money(preview.totalExpected)}</dd></div></dl>{hasHistory&&<label className="strong-confirm"><input type="checkbox" checked={includeHistory} onChange={(event)=>changeHistory(event.target.checked)}/>Incluir também as competências históricas anteriores a este mês.</label>}</>}<footer><button className="button secondary" disabled={confirming} onClick={onClose}>Cancelar</button><button className="button" disabled={!preview||loading||confirming||preview.installmentCount===0} onClick={confirm}>{confirming?'Processando…':preview?.alreadyActive?'Gerar faltantes':'Confirmar ativação e geração'}</button></footer></section></div>
}
