import { useMemo, useState } from 'react'
import { PageHeader } from './PageHeader'
import { AGENCY_GOALS } from '../config/agencyGoals'
import { SERVICE_CATALOG } from '../config/serviceCatalog'
import { calculateAgencyGoalProgress, calculateContractedRevenue, calculateProjectRevenue, calculateTeamGoals, groupRevenueByService, calculateSalesGapScenarios, groupContractsByDuration, calculateRevenueRisk, simulateServiceMix } from '../lib/businessMetrics'
import { calculateFinancialSummary } from '../lib/financialMetrics'
import {ServiceResponsibilityMetrics} from './ServiceResponsibilityMetrics'
import {BillingDueMetrics} from './BillingDueMetrics'
import {NowCard} from './NowCard'

const money=(value)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)
const Progress=({value,label})=><div className="goal-progress" role="progressbar" aria-label={label} aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(value)}><span style={{width:`${Math.min(value,100)}%`}} /></div>
const Stat=({label,value,note})=><article className="business-stat"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>

function Simulator(){const [rows,setRows]=useState([{serviceId:SERVICE_CATALOG[0].id,quantity:1}]);const totals=simulateServiceMix(rows,SERVICE_CATALOG);const update=(i,key,value)=>setRows((current)=>current.map((row,index)=>index===i?{...row,[key]:value}:row));return <section className="dashboard-panel business-section"><header><div><h2>Simulador de combinação</h2><p>Simulação visual. Não altera propostas nem os números reais.</p></div><button className="button secondary small" type="button" onClick={()=>setRows([{serviceId:SERVICE_CATALOG[0].id,quantity:1}])}>Limpar simulação</button></header><div className="simulator-rows">{rows.map((row,i)=><div className="simulator-row" key={i}><label>Serviço<select value={row.serviceId} onChange={(e)=>update(i,'serviceId',e.target.value)}>{SERVICE_CATALOG.filter((s)=>s.billingType!=='percentage').map((s)=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Quantidade<input type="number" min="1" value={row.quantity} onChange={(e)=>update(i,'quantity',e.target.value)} /></label></div>)}</div><button className="button secondary small" type="button" onClick={()=>setRows((r)=>[...r,{serviceId:SERVICE_CATALOG[0].id,quantity:1}])}>Adicionar serviço</button><div className="simulator-totals"><Stat label="Impacto recorrente" value={money(totals.recurring)} /><Stat label="Impacto pontual" value={money(totals.oneTime)} /></div></section>}

export function Dashboard({proposals,contracts=[],installments=[],teamMembers=[]}){const metrics=useMemo(()=>{const now=new Date(),goalMembers=teamMembers.map((member)=>({id:member.id,name:member.name,goal:AGENCY_GOALS.individualMonthlyGoal}));return {goal:calculateAgencyGoalProgress(proposals,AGENCY_GOALS.monthlyAgencyGoal,now),team:calculateTeamGoals(proposals,goalMembers,now),project:calculateProjectRevenue(proposals),services:groupRevenueByService(proposals,now),projection:calculateContractedRevenue(proposals,now),duration:groupContractsByDuration(proposals,now),risk:calculateRevenueRisk(proposals,now),financial:calculateFinancialSummary(contracts,installments)}},[proposals,contracts,installments,teamMembers]);const scenarios=calculateSalesGapScenarios(metrics.goal.remaining,SERVICE_CATALOG);return <div className="dashboard-page business-dashboard">
<PageHeader eyebrow="Mugô Business Intelligence" title="Gestão comercial e inteligência de receita" description="Metas, composição de receita e leitura contratual usando exclusivamente os dados comerciais atuais." />
<NowCard />
<BillingDueMetrics installments={installments}/>
<ServiceResponsibilityMetrics contracts={contracts}/>
<section className="goal-hero"><div><span>Meta mensal da Mugô</span><h2>{money(metrics.goal.current)}</h2><p>de {money(metrics.goal.goal)} — Meta base mensal da equipe</p><Progress value={metrics.goal.percentage} label="Progresso da meta mensal" /></div><div className="goal-facts"><Stat label="Atingido" value={`${metrics.goal.percentage.toFixed(1)}%`} /><Stat label="Valor restante" value={money(metrics.goal.remaining)} /><Stat label="Contratos recorrentes ativos" value={metrics.goal.activeContracts} /></div></section>
<section className="business-grid two"><Stat label="Receita recorrente mensal" value={money(metrics.goal.current)} note="A recorrência sustenta a operação mensal." /><Stat label="Receita de implantação e projetos" value={money(metrics.project)} note="Projetos e implantações representam receita pontual." /></section>
<section className="dashboard-panel business-section"><header><div><h2>Recebimentos</h2><p>Setup contratado e recebido são separados. Total em aberto = setup pendente + mensalidades pendentes ou vencidas.</p></div></header><div className="financial-kpi-grid">{[['Setup contratado',metrics.financial.setupContracted],['Setup recebido',metrics.financial.setupReceived],['Setup pendente',metrics.financial.setupPending],['Mensalidades recebidas',metrics.financial.monthlyReceived],['Mensalidades pendentes',metrics.financial.monthlyPending],['Total recebido',metrics.financial.totalReceived],['Total em aberto',metrics.financial.totalOpen]].map(([label,value])=><Stat key={label} label={label} value={money(value)} />)}</div></section>
<section className="dashboard-panel business-section"><header><div><h2>Meta por integrante</h2><p>Atribuição pelo campo responsável, sem redistribuição automática.</p></div></header><div className="team-grid">{metrics.team.members.map((m)=><article className="team-card" key={m.id}><span>{m.name}</span><strong>{money(m.revenue)}</strong><small>{m.percentage.toFixed(1)}% de {money(m.goal)} · faltam {money(m.remaining)}</small><Progress value={m.percentage} label={`Meta de ${m.name}`} /></article>)}</div><p className="data-note">Receita sem responsável definido: <strong>{money(metrics.team.unassigned)}</strong></p></section>
<section className="dashboard-panel business-section"><header><div><h2>Receita por serviço</h2><p>Dados históricos mantêm os nomes registrados em cada proposta.</p></div></header><div className="table-scroll"><table className="report-table"><thead><tr><th>Serviço</th><th>Qtd.</th><th>Mensal</th><th>Setup</th><th>Participação</th></tr></thead><tbody>{metrics.services.map((r)=><tr key={r.name}><td>{r.name}</td><td>{r.count}</td><td>{money(r.monthly)}</td><td>{money(r.setup)}</td><td>{r.share.toFixed(1)}%</td></tr>)}{!metrics.services.length&&<tr><td colSpan="5">Nenhuma receita fechada disponível.</td></tr>}</tbody></table></div></section>
<section className="business-grid two"><div className="dashboard-panel business-section"><header><div><h2>O que falta vender</h2><p>Uma forma de alcançar a meta seria…</p></div></header>{metrics.goal.remaining===0?<p className="data-note">A meta base já foi atingida.</p>:<ul className="scenario-list">{scenarios.map((s)=><li key={s.id}><strong>{s.quantity} contratos de {s.name}</strong><span>{money(s.recommendedPrice)} recomendados por contrato</span></li>)}</ul>}<p className="data-note">Cenários simples, não previsões.</p></div><Simulator /></section>
<section className="dashboard-panel business-section"><header><div><h2>Receita contratada</h2><p>Mensalidades dentro da vigência conhecida, aproximadas em ciclos de 30 dias.</p></div></header><div className="projection-grid">{[30,90,180,365].map((d)=><Stat key={d} label={`Próximos ${d} dias`} value={money(metrics.projection.values[d])} />)}</div><p className="data-note">{metrics.projection.withoutEndDate} contratos ativos sem data final informada. Eles contam somente na receita mensal atual e não nas projeções futuras.</p></section>
<section className="business-grid two"><div className="dashboard-panel business-section"><header><div><h2>Duração dos contratos</h2><p>Datas válidas têm prioridade; prazo textual reconhecível é usado como apoio.</p></div></header><ul className="duration-list">{metrics.duration.map((r)=><li key={r.label}><span>{r.label}<small>{r.count} contrato(s)</small></span><strong>{money(r.revenue)} · {r.share.toFixed(1)}%</strong></li>)}</ul></div><div className="dashboard-panel business-section"><header><div><h2>Receita em atenção</h2><p>Painel informativo, sem tarefas ou lembretes.</p></div></header><ul className="risk-list"><li><span>Receita mensal já vencida</span><strong>{money(metrics.risk.expired)}</strong></li><li><span>Vencendo em até 30 dias</span><strong>{money(metrics.risk.due30)}</strong></li><li><span>Vencendo em 31 a 60 dias</span><strong>{money(metrics.risk.due60)}</strong></li><li><span>Ativos sem data final</span><strong>{metrics.risk.withoutEnd}</strong></li><li><span>Fechados sem assinatura</span><strong>{metrics.risk.closedUnsigned}</strong></li><li><span>Assinados sem link</span><strong>{metrics.risk.signedWithoutLink}</strong></li></ul></div></section>
</div>}
