import {useMemo} from 'react'
import {PageHeader} from './PageHeader'
import {calculateFinancialSummary} from '../lib/financialMetrics'

const money=(value)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)
const Stat=({label,value,note})=><article className="business-stat"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>
const CURRENT_MONTH=new Date().toISOString().slice(0,7),WEEK_LIMIT=new Date(new Date().getTime()+7*86400000)
export function Dashboard({proposals=[],contracts=[],installments=[],tasks=[]}){
  const metrics=useMemo(()=>{const activeContracts=contracts.filter((item)=>item.status==='active'),openProposals=proposals.filter((item)=>!['won','lost','expired','cancelled','Fechada','Perdida'].includes(item.status||item.proposal_status)),received=installments.filter((item)=>String(item.manual_confirmation_at||item.paid_at||'').startsWith(CURRENT_MONTH)).reduce((sum,item)=>sum+Number(item.received_amount||0),0),overdue=installments.filter((item)=>item.status==='overdue'&&Number(item.amount||0)>Number(item.received_amount||0)),financial=calculateFinancialSummary(contracts,installments),commercialAssigned=new Set(contracts.map((item)=>item.responsible_id).filter(Boolean)).size,deliveryAssigned=new Set(contracts.flatMap((item)=>item.contract_services||[]).map((item)=>item.delivery_responsible_id).filter(Boolean)).size,financialAssigned=new Set(contracts.map((item)=>item.financial_responsible_id).filter(Boolean)).size,unassigned=activeContracts.filter((item)=>!item.responsible_id).length;return{activeContracts,openProposals,received,overdue,financial,commercialAssigned,deliveryAssigned,financialAssigned,unassigned,tasks:tasks.filter((item)=>item.status!=='completed'&&item.due_date&&new Date(item.due_date)<=WEEK_LIMIT).length,clients:new Set(proposals.map((item)=>item.clientId||item.client_id).filter(Boolean)).size}},[proposals,contracts,installments,tasks])
  return <div className="dashboard-page business-dashboard"><PageHeader eyebrow="Operação da Mugô" title="Painel" description="Visão direta do fluxo entre clientes, propostas, contratos e recebimentos."/><section className="dashboard-core-metrics"><Stat label="Receita recorrente ativa" value={money(metrics.activeContracts.reduce((sum,item)=>sum+Number(item.monthly_value||0),0))}/><Stat label="Receita recebida no mês" value={money(metrics.received)}/><Stat label="Propostas em aberto" value={metrics.openProposals.length}/><Stat label="Contratos ativos" value={metrics.activeContracts.length}/><Stat label="Parcelas atrasadas" value={metrics.overdue.length}/><Stat label="Tarefas da semana" value={tasks.length?metrics.tasks:'Não configurado'} note={!tasks.length?'Disponível após ativar tarefas operacionais.':null}/></section><section className="dashboard-panel crm-flow-panel"><header><div><h2>Fluxo comercial</h2><p>Cada etapa reutiliza os dados da anterior.</p></div></header><div className="crm-flow"><article><span>Clientes</span><strong>{metrics.clients}</strong></article><i>→</i><article><span>Propostas</span><strong>{proposals.length}</strong></article><i>→</i><article><span>Contratos</span><strong>{contracts.length}</strong></article><i>→</i><article><span>Receita recebida</span><strong>{money(metrics.financial.totalReceived)}</strong></article></div></section><section className="dashboard-panel"><header><div><h2>Responsabilidades da equipe</h2><p>Quantidade de responsáveis identificados nos registros atuais.</p></div></header><div className="dashboard-responsibilities"><Stat label="Comercial" value={metrics.commercialAssigned}/><Stat label="Entrega" value={metrics.deliveryAssigned}/><Stat label="Financeiro" value={metrics.financialAssigned||'Não configurado'}/><Stat label="Contratos sem responsável" value={metrics.unassigned}/></div></section></div>
}
