import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, CircleOff, Database, ShieldCheck } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { createExpense, createMissingFinancialLookups, findExpenseByImportKey, listExpenseLookups, listExpenses } from '../services/data/expensesRepository'
import { FeedbackMessage } from './FeedbackMessage'
import { PageHeader } from './PageHeader'
import { findFinancialImportMatch, normalizeFinancialName, validateFinancialImportRow } from '../lib/financialImport'

const categories=['Inteligência artificial','Design','Infraestrutura','Hospedagem','E-mail e armazenamento','Desenvolvimento','Equipe','Prestadores','Marketing','Impostos e taxas','Contabilidade','Telefonia','Internet','Transporte','Equipamentos','Domínios','Outros']
const costCenters=['Tecnologia','Operação','Comercial','Marketing','Administrativo','Financeiro','Pessoas','Projetos','Diretoria','Pessoal','Compartilhado']
const informed=[
  ['supabase','Supabase',null,'Infraestrutura','Danilo'],['chatgpt-danilo','ChatGPT Danilo',120,'Inteligência artificial','Danilo'],
  ['chatgpt-mugo','ChatGPT Mugô',120,'Inteligência artificial','Mugô'],['canva','Canva',40,'Design','Mugô'],
  ['claude','Claude',null,'Inteligência artificial','Danilo'],['duda','Duda',1000,'Equipe','Natureza a validar'],
  ['wanderson','Wanderson',700,'Equipe','Natureza a validar'],['google-workspace','Google Drive / Google Workspace',null,'E-mail e armazenamento','Mugô'],
].map(([key,name,amount,category,responsible])=>({key:`mugo-v1:${key}`,name,amount:amount??'',category,responsible,due_day:'',start_date:'',scope:'business',business_percentage:100,recurrence_type:'monthly',ignored:false}))
const personal=['Aluguel','Luz','Internet','Celular','Celular Kleber','Carro','Gasolina','Mercado','Faculdade','Saúde','Pets','Compromissos pessoais'].map((name,index)=>({key:`personal-v1:${index+1}`,name,amount:'',category:'Outros',responsible:'',due_day:'',start_date:'',scope:'personal',business_percentage:0,recurrence_type:'monthly',ignored:false}))
function ReviewTable({rows,setRows,lookups,existing,onImport,canWrite}){
  const categoryNames=lookups.categories.map((item)=>item.name)
  function change(index,key,value){setRows((current)=>current.map((row,rowIndex)=>rowIndex===index?{...row,[key]:value}:row))}
  return <div className="import-review-list">{rows.map((row,index)=>{const match=findFinancialImportMatch(row,existing),category=lookups.categories.find((item)=>normalizeFinancialName(item.name)===normalizeFinancialName(row.category)),validation=validateFinancialImportRow(row,{categoryExists:Boolean(category)}),ready=validation.valid&&!match&&!row.ignored;return <article className={`import-review-card${row.ignored?' ignored':''}`} key={row.key}><header><div><strong>{row.name}</strong><small>{match?`Correspondência: ${match.name} (${match.status})`:'Nenhuma correspondência importada'}</small></div>{match?<CheckCircle2 size={20}/>:row.ignored?<CircleOff size={20}/>:null}</header><div className="import-review-fields"><label>Valor informado<input type="number" min="0.01" step="0.01" value={row.amount} onChange={event=>change(index,'amount',event.target.value)} placeholder="Pendente"/></label><label>Vencimento<input type="number" min="1" max="31" value={row.due_day} onChange={event=>change(index,'due_day',event.target.value)} placeholder="Dia"/></label><label>Início<input type="date" value={row.start_date} onChange={event=>change(index,'start_date',event.target.value)}/></label><label>Categoria<select value={row.category} onChange={event=>change(index,'category',event.target.value)}><option value="">Selecionar</option>{[...new Set([...categoryNames,row.category].filter(Boolean))].map((name)=><option key={name}>{name}</option>)}</select></label><label>Escopo<select value={row.scope} onChange={event=>change(index,'scope',event.target.value)}><option value="business">Empresarial</option><option value="personal">Pessoal</option><option value="shared">Compartilhado</option><option value="pending_review">Pendente de revisão</option></select></label>{row.scope==='shared'&&<label>Percentual Mugô<input type="number" min="0.01" max="100" step="0.01" value={row.business_percentage} onChange={event=>change(index,'business_percentage',event.target.value)}/></label>}<label>Pago por / responsável<input value={row.responsible} onChange={event=>change(index,'responsible',event.target.value)}/></label></div><footer><span>{match?'Já existente — bloqueado':row.ignored?'Ignorado nesta revisão':validation.errors[0]||'Pronto para confirmação'}</span>{canWrite&&!match&&<><button type="button" className="button secondary small" onClick={()=>change(index,'ignored',!row.ignored)}>{row.ignored?'Reconsiderar':'Ignorar'}</button><button type="button" className="button small" disabled={!ready} onClick={()=>onImport(row,category)}>Confirmar importação</button></>}</footer></article>})}</div>
}

export function FinancialImportPage(){const {canWrite}=useAuth(),[lookups,setLookups]=useState({categories:[],costCenters:[],accounts:[]}),[existing,setExisting]=useState([]),[businessRows,setBusinessRows]=useState(informed),[personalRows,setPersonalRows]=useState(personal),[section,setSection]=useState('business'),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[gate,setGate]=useState(false)
  async function load(){setLoading(true);setError('');try{const [lookupRows,expenseRows]=await Promise.all([listExpenseLookups(),listExpenses()]);await findExpenseByImportKey('mugo-v1:environment-check');setLookups(lookupRows);setExisting(expenseRows);setGate(true)}catch(cause){setGate(false);setError(/import_key/i.test(cause.message||'')?'A migration de controle de importação ainda não foi aplicada. A importação permanece bloqueada.':'Não foi possível validar as tabelas financeiras com a sessão atual. Execute o SQL de validação no Supabase antes de importar.')}finally{setLoading(false)}}
  useEffect(()=>{const timer=window.setTimeout(()=>load(),0);return()=>window.clearTimeout(timer)},[])
  const missing=useMemo(()=>({categories:categories.filter((name)=>!lookups.categories.some((item)=>normalizeFinancialName(item.name)===normalizeFinancialName(name))),costCenters:costCenters.filter((name)=>!lookups.costCenters.some((item)=>normalizeFinancialName(item.name)===normalizeFinancialName(name)))}),[lookups])
  async function prepareMasters(){if(!window.confirm(`Criar ${missing.categories.length} categoria(s) e ${missing.costCenters.length} centro(s) ausentes nesta organização?`))return;try{await createMissingFinancialLookups('expense_categories',categories);await createMissingFinancialLookups('cost_centers',costCenters);setMessage('Dados mestres preparados sem duplicar nomes existentes.');await load()}catch(cause){setError(cause.message||'Não foi possível preparar os dados mestres.')}}
  async function importRow(row,category){if(!gate||!window.confirm(`Importar “${row.name}” como pendente de validação? Esta ação cria a despesa e sua primeira parcela.`))return;setError('');try{const duplicate=await findExpenseByImportKey(row.key);if(duplicate)throw new Error('Este registro já foi importado. A operação repetida foi bloqueada.');const percentage=row.scope==='business'?100:row.scope==='shared'?Number(row.business_percentage):0;await createExpense({import_key:row.key,name:row.name,supplier_name:row.name,responsible_name:row.responsible||null,total_amount:Number(row.amount),scope:row.scope,business_percentage:percentage,recurrence_type:'monthly',due_day:Number(row.due_day),start_date:row.start_date,installment_count:1,status:'draft',validated:false,category_id:category.id,cost_center_id:null,financial_account_id:null,notes:'Importado pela revisão financeira V2; requer validação antes de uso contábil.'});setMessage(`${row.name} importado como pendente de validação.`);await load()}catch(cause){setError(cause.code==='23505'?'Este registro já existe. Nenhuma duplicidade foi criada.':cause.message||'Não foi possível importar o registro.')}}
  return <div><PageHeader eyebrow="Administração" title="Importação financeira" description="Revisão controlada, individual e idempotente das contas informadas."/>{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{message&&<FeedbackMessage type="success">{message}</FeedbackMessage>}<section className="migration-gate"><ShieldCheck size={22}/><div><strong>{gate?'Estrutura acessível pela sessão autenticada':'Importação bloqueada'}</strong><span>{gate?'RLS continuará sendo a barreira de organização e permissão.':'Confirme a validação pós-migration e a migration de controle de importação.'}</span></div></section><section className="master-data-panel dashboard-panel"><header><div><h2>Dados mestres sugeridos</h2><p>{missing.categories.length} categorias e {missing.costCenters.length} centros de custo ainda não correspondidos.</p></div>{canWrite&&gate&&<button className="button" disabled={loading||(!missing.categories.length&&!missing.costCenters.length)} onClick={prepareMasters}><Database size={16}/>Revisar e criar ausentes</button>}</header><details><summary>Categorias sugeridas</summary><p>{categories.join(' · ')}</p></details><details><summary>Centros de custo sugeridos</summary><p>{costCenters.join(' · ')}</p></details><p className="data-note">Contas financeiras não são presumidas: banco, instituição e saldo permanecem para cadastro manual.</p></section><nav className="section-tabs"><button className={section==='business'?'active':''} onClick={()=>setSection('business')}>Contas da Mugô</button><button className={section==='personal'?'active':''} onClick={()=>setSection('personal')}>Controle pessoal e compartilhado</button></nav>{section==='business'?<ReviewTable rows={businessRows} setRows={setBusinessRows} lookups={lookups} existing={existing} onImport={importRow} canWrite={canWrite&&gate}/>:<><FeedbackMessage type="info">Itens pessoais não entram no resultado da Mugô. Cartão é meio de pagamento; poupança é transferência ou reserva. Nenhum destes itens possui valor ou vencimento confirmado.</FeedbackMessage><ReviewTable rows={personalRows} setRows={setPersonalRows} lookups={lookups} existing={existing} onImport={importRow} canWrite={canWrite&&gate}/></>}</div>}
