import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,ArrowRight} from 'lucide-react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {listInstallments} from '../services/data/financeRepository'
import {listExpenseInstallments} from '../services/data/expensesRepository'
import {listFinancialHubRecords} from '../services/data/financialHubRepository'
import {buildFinancialCalendar} from '../lib/financialHub'
import {isoInSaoPaulo,monthBounds,monthGrid,startOfWeek,weekDays} from '../lib/operationalCalendar'
import {useAuth} from '../contexts/AuthContext'

const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const labels={today:'Hoje',week:'Semana',month:'Mês'}
export function FinancialCalendarPage({view='today'}){
  const {canAccessFinance,canViewHouseholdFinance}=useAuth(),today=isoInSaoPaulo(),[anchor,setAnchor]=useState(today),[income,setIncome]=useState([]),[expenses,setExpenses]=useState([]),[hub,setHub]=useState({debts:[],freelance:[]}),[scope,setScope]=useState('all'),[selected,setSelected]=useState(null),[error,setError]=useState('')
  useEffect(()=>{if(!canAccessFinance)return;Promise.all([listInstallments(),listExpenseInstallments(),listFinancialHubRecords()]).then(([receivables,payables,records])=>{setIncome(receivables);setExpenses(payables);setHub(records)}).catch((cause)=>setError(cause.message))},[canAccessFinance])
  const range=useMemo(()=>view==='today'?{start:anchor,end:anchor}:view==='week'?{start:startOfWeek(anchor),end:weekDays(anchor)[6]}:monthBounds(anchor),[view,anchor])
  const incoming=income.filter((item)=>item.due_date>=range.start&&item.due_date<=range.end),outgoing=expenses.filter((item)=>item.due_date>=range.start&&item.due_date<=range.end),received=incoming.filter((item)=>item.status==='paid').reduce((sum,item)=>sum+Number(item.received_amount||item.amount||0),0),expected=incoming.filter((item)=>item.status!=='paid').reduce((sum,item)=>sum+Number(item.amount||0),0),paid=outgoing.filter((item)=>item.status==='paid').reduce((sum,item)=>sum+Number(item.paid_amount||item.amount||0),0),due=outgoing.filter((item)=>item.status!=='paid').reduce((sum,item)=>sum+Number(item.business_amount||0),0)
  const period=anchor.slice(0,7),calendar=buildFinancialCalendar({receivables:income,payables:expenses,debts:hub.debts,freelance:hub.freelance},period).filter((item)=>scope==='all'||scope==='business'&&item.scope==='business'||scope==='household'&&item.scope==='household'),byDay=calendar.reduce((result,item)=>{(result[item.date]??=[]).push(item);return result},{})
  function move(amount){const date=new Date(`${anchor}T12:00:00Z`);if(view==='month')date.setUTCMonth(date.getUTCMonth()+amount,1);else date.setUTCDate(date.getUTCDate()+amount*(view==='week'?7:1));setAnchor(date.toISOString().slice(0,10))}
  if(!canAccessFinance)return <FeedbackMessage type="error">Seu perfil não possui acesso aos dados financeiros.</FeedbackMessage>
  return <div className="financial-calendar"><PageHeader eyebrow="Financeiro" title={`Financeiro · ${labels[view]}`} description="Receitas, despesas, dívidas e freelas reais. Pipeline permanece separado."/>{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}<div className="calendar-toolbar"><button onClick={()=>move(-1)}><ArrowLeft size={15}/></button><strong>{range.start===range.end?range.start:`${range.start} — ${range.end}`}</strong><button onClick={()=>setAnchor(today)}>Hoje</button><button onClick={()=>move(1)}><ArrowRight size={15}/></button></div>{view==='month'&&<nav className="today-filters"><button className={scope==='all'?'active':''} onClick={()=>setScope('all')}>Tudo</button><button className={scope==='business'?'active':''} onClick={()=>setScope('business')}>Mugô</button>{canViewHouseholdFinance&&<button className={scope==='household'?'active':''} onClick={()=>setScope('household')}>Casa</button>}</nav>}<section className="operation-metrics"><article><strong>{money(received)}</strong><span>Recebido</span></article><article><strong>{money(expected)}</strong><span>Entradas previstas</span></article><article><strong>{money(paid)}</strong><span>Despesas pagas</span></article><article><strong>{money(due)}</strong><span>Saídas previstas</span></article></section>{view==='month'?<section className="month-grid financial-month-grid">{monthGrid(anchor).map((day)=>{const rows=byDay[day]||[];return <button className={day.slice(0,7)!==period?'outside':''} key={day} onClick={()=>setSelected(day)}><strong>{Number(day.slice(-2))}</strong>{rows.slice(0,3).map((item)=><span className={item.kind} key={item.id}>{item.label} · {money(item.amount)}</span>)}{rows.length>3&&<small>+{rows.length-3}</small>}</button>})}</section>:<div className="financial-calendar-columns"><section><h2>Entradas</h2>{incoming.map((item)=><article key={item.id}><div><strong>{item.clients?.company_name||'Recebimento'}</strong><small>{item.due_date} · {item.status}</small></div><b>{money(item.amount)}</b></article>)}{!incoming.length&&<p>Nenhuma entrada no período.</p>}</section><section><h2>Saídas</h2>{outgoing.map((item)=><article key={item.id}><div><strong>{item.expenses?.name||'Despesa'}</strong><small>{item.due_date} · {item.status}</small></div><b>{money(item.business_amount)}</b></article>)}{!outgoing.length&&<p>Nenhuma saída no período.</p>}</section></div>}{selected&&<><button className="drawer-backdrop" aria-label="Fechar" onClick={()=>setSelected(null)}/><aside className="operation-day-drawer"><header><div><small>Movimentos do dia</small><h2>{selected}</h2></div><button onClick={()=>setSelected(null)}>×</button></header>{(byDay[selected]||[]).map((item)=><article className="operation-task" key={item.id}><h3>{item.label}</h3><p>{item.kind} · {item.scope}</p><strong>{money(item.amount)}</strong></article>)}</aside></>}<FeedbackMessage type="info">Pipeline potencial continua no Comercial e não compõe estes totais.</FeedbackMessage></div>
}
