/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from 'react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {runFinancialReconciliation} from '../services/data/operationsRepository'
import {confirmRuahGimports,listRecurringReconciliation,refreshOverdueReceivables} from '../services/data/financialHubRepository'
import {useAuth} from '../contexts/AuthContext'

const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function FinancialReconciliationPage(){
  const {isAdmin}=useAuth(),[data,setData]=useState(null),[recurring,setRecurring]=useState({queue:[],candidates:[]}),[candidate,setCandidate]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  async function run(){setLoading(true);setError('');try{const [reconciliation,recurringRows]=await Promise.all([runFinancialReconciliation(),listRecurringReconciliation()]);setData(reconciliation);setRecurring(recurringRows)}catch(cause){setError(cause.message)}finally{setLoading(false)}}
  async function linkRuah(){const [clientId,contractId]=candidate.split(':');if(!clientId||!contractId||!window.confirm('Confirmar vínculo administrativo Ruah → GIMPORTS SPLITS?'))return;setLoading(true);setError('');try{await confirmRuahGimports(clientId,contractId);setMessage('Vínculo Ruah → GIMPORTS SPLITS confirmado. O contrato existente foi preservado e o dia de cobrança ajustado para 05.');await run()}catch(cause){setError(cause.message);setLoading(false)}}
  async function refreshOverdue(){setLoading(true);setError('');try{const count=await refreshOverdueReceivables();setMessage(`${count} parcela(s) pendente(s), vencida(s) e sem recebimento foram classificadas como overdue.`);await run()}catch(cause){setError(cause.message);setLoading(false)}}
  useEffect(()=>{run()},[])
  const ruah=recurring.queue.find((row)=>row.reconciliation_key==='recurring:ruah'),latina=recurring.queue.find((row)=>row.reconciliation_key==='recurring:latina'),cafifa=recurring.queue.find((row)=>row.reconciliation_key==='contract-review:cafifa-end-date')
  return <div className="operations-page"><PageHeader eyebrow="Financeiro" title="Reconciliação" description="Compara Contratos → Parcelas → Recebimentos → Dashboard → KPIs." actions={<button className="button" onClick={run} disabled={loading}>{loading?'Comparando…':'Reconciliar agora'}</button>}/>{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{message&&<FeedbackMessage type="success">{message}</FeedbackMessage>}<div className="health-grid">{Object.entries(data?.totals||{}).map(([key,value])=><article key={key}><span>{key}</span><strong>{money(value)}</strong></article>)}</div><section className="dashboard-panel"><h2>Diferenças encontradas</h2><div className="audit-checks">{(data?.checks||[]).map((check)=><article className={`audit-check ${check.status}`} key={check.key}><span>{check.status==='ok'?'✔':'⚠'}</span><div><strong>{check.label}</strong><small>{check.detail}</small></div></article>)}</div></section><section className="dashboard-panel"><h2>Receitas que exigem revisão</h2>{cafifa&&<article className="audit-check warning"><span>⚠</span><div><strong>CAFIFA / Santo Circuito sem data final</strong><small>{cafifa.notes}</small></div></article>}{latina&&<article className="audit-check warning"><span>⚠</span><div><strong>Latina · EUR {latina.payload?.original_amount}</strong><small>Sem vínculo inequívoco e sem câmbio informado. Nenhum valor BRL será criado automaticamente.</small></div></article>}{ruah&&<article className="audit-check warning"><span>⚠</span><div><strong>Ruah · vencimento dia 05</strong><small>{ruah.notes}</small>{isAdmin&&ruah.status==='pending_mapping'&&<div className="page-actions"><select aria-label="Cliente e contrato GIMPORTS" value={candidate} onChange={(event)=>setCandidate(event.target.value)}><option value="">Selecione o contrato existente</option>{recurring.candidates.flatMap((client)=>(client.contracts||[]).map((contract)=><option key={contract.id} value={`${client.id}:${contract.id}`}>{client.trade_name||client.company_name} · {money(contract.monthly_value)}</option>))}</select><button className="button" disabled={!candidate||loading} onClick={linkRuah}>Vincular Ruah ao cliente existente GIMPORTS SPLITS</button></div>}</div></article>}{!cafifa&&!latina&&!ruah&&<p>Nenhuma receita aguardando reconciliação.</p>}</section>{isAdmin&&<div className="page-actions"><button className="button secondary" disabled={loading} onClick={refreshOverdue}>Atualizar vencidos com segurança</button></div>}</div>
}
