import {useEffect,useMemo,useState} from 'react'
import {CheckCircle2,Clock3} from 'lucide-react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {confirmInstallmentReceipt,listInstallments,recordBillingPrepared} from '../services/data/financeRepository'
import {listContracts} from '../services/data/contractsRepository'
import {getOrganizationSettings} from '../services/data/settingsRepository'
import {useAuth} from '../contexts/AuthContext'
import {errorPresentation} from '../lib/userError'
import {calculateFinancialSummary,setupStatus} from '../lib/financialMetrics'
import {effectiveInstallmentStatus,installmentBalance} from '../lib/contractBilling'
import {buildMonthlyBillingMessage,buildSetupBillingMessage,isValidBrazilianPhone} from '../lib/whatsapp'
import {InstallmentPaymentModal} from './InstallmentPaymentModal'
import {WhatsAppReviewModal} from './WhatsAppReviewModal'
import {calculateRevenueDistribution,formatRevenueDistribution,revenueForPeriod} from '../services/finance/revenueDistribution'
const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),dayMs=86400000
const paymentLabel={pix:'PIX',transfer:'Transferência',ted:'TED',cash:'Dinheiro',card:'Cartão',other:'Outro'}
export function FinancePage(){
  const {canWrite,isAdmin}=useAuth(),[items,setItems]=useState([]),[contracts,setContracts]=useState([]),[settings,setSettings]=useState({}),[tab,setTab]=useState('receivable'),[distributionMode,setDistributionMode]=useState('realized'),[distributionPeriod,setDistributionPeriod]=useState(()=>new Date().toISOString().slice(0,7)),[payment,setPayment]=useState(null),[whatsapp,setWhatsapp]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null)
  const load=()=>Promise.all([listInstallments(),listContracts()]).then(([rows,contractRows])=>{setItems(rows);setContracts(contractRows)}).catch((cause)=>setError(errorPresentation(cause,'Não foi possível carregar o financeiro.',{operation:'listar',entity:'financeiro'}))).finally(()=>setLoading(false))
  useEffect(()=>{load();getOrganizationSettings().then(setSettings).catch((cause)=>setError(errorPresentation(cause,'As configurações de cobrança não puderam ser carregadas.',{operation:'carregar',entity:'configurações'})))},[])
  const totals=useMemo(()=>calculateFinancialSummary(contracts,items),[contracts,items]),open=items.filter((item)=>installmentBalance(item)>0&&!['cancelled','refunded','failed'].includes(effectiveInstallmentStatus(item))),received=items.filter((item)=>Number(item.received_amount)>0).sort((a,b)=>String(b.manual_confirmation_at||b.paid_at).localeCompare(String(a.manual_confirmation_at||a.paid_at))),activeContracts=contracts.filter((contract)=>contract.status==='active'),mrr=activeContracts.reduce((sum,contract)=>sum+Number(contract.monthly_value||0),0),contracted=totals.totalExpected,setupByContract=useMemo(()=>new Map(contracts.map((contract)=>[contract.id,calculateFinancialSummary([contract],items.filter((item)=>item.contract_id===contract.id))])),[contracts,items])
  const distribution=calculateRevenueDistribution(revenueForPeriod(items,distributionPeriod,distributionMode)),formattedDistribution=formatRevenueDistribution(distribution),realized=distributionMode==='realized'
  async function savePayment(values){try{await confirmInstallmentReceipt(payment.id,values);setPayment(null);await load()}catch(cause){setError(errorPresentation(cause,'Não foi possível registrar o recebimento.',{operation:'confirmar recebimento',entity:'parcela',id:payment.id}));throw cause}}
  function prepare(item){const client=item.clients||{},phone=isValidBrazilianPhone(client.billing_contact_phone)?client.billing_contact_phone:client.phone;if(!isValidBrazilianPhone(phone)){setError({friendly:'O cliente não possui telefone financeiro ou principal válido.',technical:{entity:'cliente',id:item.client_id}});return}const balance=installmentBalance(item),isSetup=item.installment_type==='setup',name=client.billing_contact_name||client.contact_name||client.company_name,message=isSetup?buildSetupBillingMessage({name,setupTotal:money(item.amount),setupReceived:money(item.received_amount),setupPending:money(balance),dueDate:item.due_date,pixKey:settings.pix_key,bankName:settings.bank_name}):buildMonthlyBillingMessage({name,reference:item.reference_month,value:money(balance),dueDate:item.due_date,pixKey:settings.pix_key,bankName:settings.bank_name,overdue:effectiveInstallmentStatus(item)==='overdue'});setWhatsapp({client:client.company_name,phone,type:isSetup?'Setup':'Mensalidade',contract:item.contracts?.contract_number,reference:item.reference_month,value:money(balance),dueDate:item.due_date,pixKey:settings.pix_key,bankName:settings.bank_name,message,clientId:item.client_id,contractId:item.contract_id})}
  const actions=(item)=><div className="row-actions">{canWrite&&<button className="button small" onClick={()=>setPayment(item)}>Confirmar recebimento</button>}{installmentBalance(item)>0&&<button className="button secondary small" onClick={()=>prepare(item)}>WhatsApp</button>}{isAdmin&&Number(item.received_amount)>0&&<button className="button secondary small" onClick={()=>setPayment(item)}>Corrigir</button>}</div>
  return <div className="finance-page"><PageHeader eyebrow="Operação financeira" title="Financeiro" description="Previsão contratual e recebimentos confirmados manualmente."/>{error&&<FeedbackMessage type="error" details={error.technical}>{error.friendly}</FeedbackMessage>}{!loading&&<RevenueDistributionSection mode={distributionMode} setMode={setDistributionMode} period={distributionPeriod} setPeriod={setDistributionPeriod} distribution={distribution} formatted={formattedDistribution} realized={realized}/>}<nav className="finance-tabs" aria-label="Seções do financeiro">{[['receivable','A receber'],['received','Recebidas'],['setups','Setups'],['consolidated','Consolidado']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{loading?<section className="dashboard-panel page-skeleton">Carregando financeiro…</section>:<>
    {tab==='receivable'&&<section className="finance-card-grid">{open.map((item)=>{const days=Math.ceil((new Date(`${item.due_date}T12:00:00`)-new Date())/dayMs),status=effectiveInstallmentStatus(item);return <article className={`finance-operation-card ${status}`} key={item.id}><header><div><h2>{item.clients?.company_name||'Cliente não informado'}</h2><p>{item.contracts?.contract_number||'Contrato sem número'}</p></div><Clock3 size={20}/></header><dl><div><dt>Competência</dt><dd>{item.reference_month}</dd></div><div><dt>Valor</dt><dd>{money(installmentBalance(item))}</dd></div><div><dt>Vencimento</dt><dd>{item.due_date}</dd></div><div><dt>Prazo</dt><dd>{days<0?`${Math.abs(days)} dias em atraso`:days===0?'Vence hoje':`${days} dias restantes`}</dd></div></dl><InstallmentDistributionDetails item={item}/>{actions(item)}</article>})}{!open.length&&<div className="empty-state"><h2>Nenhuma parcela em aberto</h2><p>As cobranças geradas aparecerão aqui.</p></div>}</section>}
    {tab==='received'&&<section className="finance-card-grid">{received.map((item)=><article className="finance-operation-card paid" key={item.id}><header><div><h2>{item.clients?.company_name}</h2><p>{item.reference_month}</p></div><CheckCircle2 size={20}/></header><dl><div><dt>Data</dt><dd>{String(item.manual_confirmation_at||item.paid_at).slice(0,10)}</dd></div><div><dt>Forma</dt><dd>{paymentLabel[item.payment_method]||'Não informada'}</dd></div><div><dt>Valor</dt><dd>{money(item.received_amount)}</dd></div><div><dt>Confirmado por</dt><dd>{item.manual_confirmation_by?'Usuário autenticado':'Não informado'}</dd></div></dl><InstallmentDistributionDetails item={item}/>{isAdmin&&actions(item)}</article>)}</section>}
    {tab==='setups'&&<section className="finance-card-grid">{contracts.filter((contract)=>setupByContract.get(contract.id)?.setupContracted>0||setupByContract.get(contract.id)?.setupReceived>0).map((contract)=>{const setup=setupByContract.get(contract.id);return <article className="finance-operation-card" key={contract.id}><h2>{contract.clients?.company_name||'Cliente não informado'}</h2><p>{contract.contract_number||'Contrato sem número'}</p><dl><div><dt>Contratado</dt><dd>{money(setup.setupContracted)}</dd></div><div><dt>Recebido</dt><dd>{money(setup.setupReceived)}</dd></div><div><dt>Pendente</dt><dd>{money(setup.setupPending)}</dd></div><div><dt>Status</dt><dd>{setupStatus({setup_value:setup.setupContracted,setup_received_amount:setup.setupReceived})}</dd></div></dl>{setup.legacySetupCount>0&&<small className="data-note">Registro legado pendente de normalização.</small>}</article>})}{!contracts.some((contract)=>setupByContract.get(contract.id)?.setupContracted>0||setupByContract.get(contract.id)?.setupReceived>0)&&<div className="empty-state"><h2>Nenhum setup contratado</h2><p>Os setups gerados nos contratos aparecerão aqui.</p></div>}</section>}
    {tab==='consolidated'&&<section className="financial-kpi-grid"><article className="business-stat"><span>Receita contratada</span><strong>{money(contracted)}</strong></article><article className="business-stat"><span>Receita recebida</span><strong>{money(totals.totalReceived)}</strong></article><article className="business-stat"><span>Receita em aberto</span><strong>{money(totals.totalOpen)}</strong></article><article className="business-stat"><span>MRR</span><strong>{money(mrr)}</strong></article><article className="business-stat"><span>Setup contratado</span><strong>{money(totals.setupContracted)}</strong></article><article className="business-stat"><span>Total recebido</span><strong>{money(totals.totalReceived)}</strong></article></section>}
  </>}{payment&&<InstallmentPaymentModal item={payment} onClose={()=>setPayment(null)} onSave={savePayment}/>} {whatsapp&&<WhatsAppReviewModal data={whatsapp} onClose={()=>setWhatsapp(null)} onConfirm={({phone})=>recordBillingPrepared({clientId:whatsapp.clientId,contractId:whatsapp.contractId,description:`Cobrança revisada para ${phone}.`,newValue:{type:'installment',value:whatsapp.value,reference:whatsapp.reference,phone}})}/>}</div>
}

function InstallmentDistributionDetails({item}){
  const formatted=formatRevenueDistribution(calculateRevenueDistribution(item.amount))
  return <details className="installment-distribution"><summary>Referência gerencial da parcela</summary><dl><div><dt>Valor bruto da parcela</dt><dd>{formatted.gross}</dd></div><div><dt>Reserva Mugô — 10%</dt><dd>{formatted.reserve}</dd></div><div><dt>Valor líquido disponível</dt><dd>{formatted.available}</dd></div><div><dt>Referência por pessoa</dt><dd>{formatted.perPerson}</dd></div></dl><small>Referência gerencial; a parcela original não é alterada.</small></details>
}

function RevenueDistributionSection({mode,setMode,period,setPeriod,distribution,formatted,realized}){
  const labels=realized?['Receita recebida','Reserva necessária sobre recebidos','Disponível realizado','Disponível realizado por pessoa']:['Receita prevista','Reserva prevista','Disponível previsto','Disponível previsto por pessoa']
  return <section className="revenue-distribution"><header><div><span>Planejamento gerencial</span><h2>Distribuição da receita Mugô</h2><p>Reserva única destinada a notas fiscais, tributos, contabilidade, investimentos e segurança de caixa.</p></div><div className="distribution-controls"><label>Período<input type="month" value={period} onChange={(event)=>setPeriod(event.target.value)}/></label><div className="distribution-mode" aria-label="Visão da distribuição">{[['realized','Realizado'],['forecast','Previsto']].map(([id,label])=><button type="button" key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}>{label}</button>)}</div></div></header><div className="revenue-distribution-grid">{[[labels[0],formatted.gross,'Antes da reserva financeira.','gross'],[labels[1],formatted.reserve,'Notas fiscais, contabilidade, investimentos e caixa.','reserve'],[labels[2],formatted.available,'Saldo disponível após a reserva.','available'],[labels[3],formatted.perPerson,'Divisão igual entre três pessoas.','person']].map(([label,value,help,tone])=><article className={tone} key={label}><span>{label}</span><strong>{value}</strong><small>{help}</small>{tone==='person'&&<b>3 pessoas</b>}</article>)}</div><div className="revenue-division-detail"><div><h3>Divisão mensal da Mugô</h3><dl><div><dt>{labels[0]}</dt><dd>{formatted.gross}</dd></div><div><dt>(−) Reserva Mugô — 10%</dt><dd>{formatted.reserve}</dd></div><div><dt>(=) Receita disponível</dt><dd>{formatted.available}</dd></div><div><dt>Dividido por</dt><dd>{distribution.members} pessoas</dd></div><div className="division-result"><dt>Disponível por pessoa</dt><dd>{formatted.perPerson}</dd></div></dl>{distribution.remainderCents>0&&<p className="cent-remainder">Restam {formatted.remainder} preservados no saldo gerencial após a divisão inteira em centavos.</p>}<p>A reserva é descontada antes da divisão entre as três pessoas.</p></div><div className="reserve-ratio" aria-label="10% reservado e 90% disponível"><div><span style={{width:'10%'}}>10%</span><span style={{width:'90%'}}>90%</span></div><p><b>10% reservado</b><b>90% disponível</b></p></div></div></section>
}
