import { useEffect,useState } from 'react'
import { PageHeader } from './PageHeader'
import { FeedbackMessage } from './FeedbackMessage'
import { CommercialDocumentReview } from './CommercialDocumentReview'
import { dataProvider } from '../lib/supabase/client'
import { useAuth } from '../contexts/AuthContext'
import { analyzeCommercialDocument,cancelCommercialDocument,confirmCommercialDocumentImport,findCommercialDuplicates,stageCommercialDocument } from '../services/data/commercialDocumentImportService'

export function ImportDocumentPage(){
  const {canWrite}=useAuth(),[file,setFile]=useState(null),[analysis,setAnalysis]=useState(null),[result,setResult]=useState(null),[reviewed,setReviewed]=useState(null),[duplicates,setDuplicates]=useState(null),[phase,setPhase]=useState('idle'),[message,setMessage]=useState(''),[progress,setProgress]=useState(0),[clientAction,setClientAction]=useState('create'),[clientId,setClientId]=useState(''),[entityAction,setEntityAction]=useState('create'),[entityId,setEntityId]=useState(''),[confirmations,setConfirmations]=useState({})
  useEffect(()=>{const warn=(event)=>{if(analysis&&phase!=='success'){event.preventDefault();event.returnValue='Há uma análise de documento em andamento.'}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[analysis,phase])
  async function start(){let staged=null;setMessage('');setPhase('uploading');setProgress(10);try{staged=await stageCommercialDocument(file);setAnalysis(staged);setProgress(40);setPhase('analyzing');const extracted=await analyzeCommercialDocument(staged.id);setProgress(80);if(!extracted.extractedData){setResult(extracted);setPhase('limited');return}const conflicts=await findCommercialDuplicates(extracted,staged);setResult(extracted);setReviewed(structuredClone(extracted.extractedData));setDuplicates(conflicts);if(conflicts.clientMatches[0]){setClientAction('link');setClientId(conflicts.clientMatches[0].item.id)}setProgress(100);setPhase('review')}catch(error){setMessage(error.message);setPhase(staged?'failed':'idle')}}
  async function retry(){if(!analysis)return;setMessage('');setPhase('analyzing');try{const extracted=await analyzeCommercialDocument(analysis.id);if(!extracted.extractedData){setResult(extracted);setPhase('limited');return}const conflicts=await findCommercialDuplicates(extracted,analysis);setResult(extracted);setReviewed(structuredClone(extracted.extractedData));setDuplicates(conflicts);setPhase('review')}catch(error){setMessage(error.message);setPhase('failed')}}
  async function cancel(){try{if(analysis)await cancelCommercialDocument(analysis)}finally{setFile(null);setAnalysis(null);setResult(null);setReviewed(null);setDuplicates(null);setConfirmations({});setProgress(0);setPhase('idle');setMessage('Importação cancelada e arquivo temporário excluído.')}}
  async function confirm(){setPhase('saving');setMessage('');try{await confirmCommercialDocumentImport({analysis,result,reviewed,clientAction,clientId,entityAction,entityId,confirmations});setPhase('success');setMessage('Documento importado após revisão humana. Nenhum pagamento ou parcela foi criado.')}catch(error){setMessage(error.message);setPhase('review')}}
  const busy=['uploading','analyzing','saving'].includes(phase)
  return <div><PageHeader eyebrow="Documentos" title="Analisar documento" description="Extração estruturada com revisão humana obrigatória antes de qualquer gravação comercial."/>{dataProvider==='legacy'?<FeedbackMessage type="info">A análise inteligente requer o provider Supabase.</FeedbackMessage>:!canWrite?<FeedbackMessage type="error">Somente administradores e gestores podem analisar documentos.</FeedbackMessage>:<>{message&&<FeedbackMessage type={phase==='success'||message.includes('cancelada')?'success':'error'}>{message}</FeedbackMessage>}{['idle','uploading','analyzing','saving','failed','limited','success'].includes(phase)&&<section className="dashboard-panel import-document intelligent-import"><label>Arquivo comercial<input type="file" accept=".pdf,.doc,.docx" disabled={busy||Boolean(analysis)} onChange={(event)=>setFile(event.target.files?.[0]||null)}/></label><p>PDF, DOC ou DOCX, até 20 MB. O tipo será classificado automaticamente.</p>{busy&&<div className="upload-progress" aria-live="polite"><progress max="100" value={progress}/><strong>{phase==='uploading'?'Enviando arquivo…':phase==='analyzing'?'Analisando documento':'Confirmando importação…'}</strong></div>}{result?.warnings?.map((warning)=><FeedbackMessage type="info" key={warning}>{warning}</FeedbackMessage>)}<div className="row-actions">{phase==='idle'&&<button className="button" disabled={!file} onClick={start}>Analisar documento</button>}{['failed','limited'].includes(phase)&&<button className="button" onClick={retry}>Tentar novamente</button>}{analysis&&phase!=='success'&&<button className="button secondary" onClick={cancel} disabled={busy}>Cancelar</button>}{phase==='success'&&<button className="button" onClick={()=>{setFile(null);setAnalysis(null);setResult(null);setPhase('idle');setMessage('')}}>Analisar outro documento</button>}</div></section>}{phase==='review'&&<CommercialDocumentReview analysis={analysis} result={result} reviewed={reviewed} onReviewedChange={setReviewed} duplicates={duplicates} clientAction={clientAction} setClientAction={setClientAction} clientId={clientId} setClientId={setClientId} entityAction={entityAction} setEntityAction={setEntityAction} entityId={entityId} setEntityId={setEntityId} confirmations={confirmations} setConfirmations={setConfirmations} onConfirm={confirm} onCancel={cancel} saving={false}/>}</>}</div>
}
