import { useEffect,useState } from 'react'
import { PageHeader } from './PageHeader'
import { FeedbackMessage } from './FeedbackMessage'
import { CommercialDocumentReview } from './CommercialDocumentReview'
import { dataProvider } from '../lib/supabase/client'
import { useAuth } from '../contexts/AuthContext'
import { analyzeCommercialDocument,cancelCommercialDocument,confirmCommercialDocumentImport,findCommercialDuplicates,stageCommercialDocument } from '../services/data/commercialDocumentImportService'

const emptyState={file:null,analysis:null,result:null,reviewed:null,duplicates:null}

export function ImportDocumentPage({onImported}){
  const {canWrite}=useAuth(),[flow,setFlow]=useState(emptyState),[phase,setPhase]=useState('idle'),[message,setMessage]=useState(''),[progress,setProgress]=useState(0),[importStage,setImportStage]=useState('Pronto para importar'),[clientAction,setClientAction]=useState('create'),[clientId,setClientId]=useState(''),[entityAction,setEntityAction]=useState('create'),[entityId,setEntityId]=useState(''),[relatedProposalId,setRelatedProposalId]=useState(''),[confirmations,setConfirmations]=useState({})
  const {file,analysis,result,reviewed,duplicates}=flow
  useEffect(()=>{const warn=(event)=>{if(analysis&&phase!=='success'){event.preventDefault();event.returnValue='Há uma análise de documento em andamento.'}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[analysis,phase])
  const prepareReview=async(extracted,staged)=>{if(!extracted.extractedData){setFlow((current)=>({...current,result:extracted}));setPhase('limited');return}const conflicts=await findCommercialDuplicates(extracted,staged);setFlow((current)=>({...current,result:extracted,reviewed:structuredClone(extracted.extractedData),duplicates:conflicts}));if(conflicts.clientMatches[0]){setClientAction('link');setClientId(conflicts.clientMatches[0].item.id)}setProgress(100);setPhase('review')}
  async function start(){let staged=null;setMessage('');setPhase('uploading');setProgress(10);try{staged=await stageCommercialDocument(file);setFlow((current)=>({...current,analysis:staged}));setProgress(40);setPhase('analyzing');const extracted=await analyzeCommercialDocument(staged.id);setProgress(80);await prepareReview(extracted,staged)}catch(error){setMessage(error.message);setPhase(staged?'failed':'idle')}}
  async function retry(){if(!analysis)return;setMessage('');setPhase('analyzing');try{await prepareReview(await analyzeCommercialDocument(analysis.id),analysis)}catch(error){setMessage(error.message);setPhase('failed')}}
  async function cancel(){try{if(analysis)await cancelCommercialDocument(analysis)}finally{setFlow(emptyState);setConfirmations({});setProgress(0);setPhase('idle');setMessage('Importação cancelada e arquivo temporário excluído.')}}
  async function changeDocumentType(documentType){const next={...result,documentType,classificationWarnings:[...(result.classificationWarnings||[]),'Tipo alterado manualmente durante a revisão.']};setConfirmations({});setEntityAction(documentType==='amendment'?'link':'create');setEntityId('');setFlow((current)=>({...current,result:next,duplicates:{...current.duplicates,classification:'sem conflito',entityMatches:[]}}));try{const conflicts=await findCommercialDuplicates(next,analysis);setFlow((current)=>({...current,duplicates:conflicts}))}catch{setMessage('O tipo foi alterado, mas as duplicidades precisam ser revisadas novamente.')}}
  async function confirm(){setPhase('saving');setMessage('');setImportStage('Pronto para importar');try{const imported=await confirmCommercialDocumentImport({analysis,result,reviewed,clientAction,clientId,entityAction,entityId,relatedProposalId,confirmations,onProgress:setImportStage});setPhase('success');setMessage(imported.partial?'Importação parcialmente concluída. Os registros foram criados, mas o status da análise precisa ser revisado.':'Importação concluída. Nenhuma parcela ou pagamento foi criado.');await onImported?.({...imported,documentType:result.documentType})}catch(error){setMessage(`${error.message}${error.stage?` Etapa: ${error.stage}.`:''}`);setImportStage(error.partial?'Importação parcialmente concluída':'Falha na importação');setPhase('review')}}
  const busy=['uploading','analyzing','saving'].includes(phase)
  return <div><PageHeader eyebrow="Documentos" title="Analisar documento" description="Extração estruturada com revisão humana obrigatória antes de qualquer gravação comercial."/>{dataProvider==='legacy'?<FeedbackMessage type="info">A análise inteligente requer o provider Supabase.</FeedbackMessage>:!canWrite?<FeedbackMessage type="error">Somente administradores e gestores podem analisar documentos.</FeedbackMessage>:<>{message&&<FeedbackMessage type={phase==='success'||message.includes('cancelada')?'success':'error'}>{message}</FeedbackMessage>}{['idle','uploading','analyzing','failed','limited','success'].includes(phase)&&<section className="dashboard-panel import-document intelligent-import"><label>Arquivo comercial<input type="file" accept=".pdf,.doc,.docx" disabled={busy||Boolean(analysis)} onChange={(event)=>setFlow((current)=>({...current,file:event.target.files?.[0]||null}))}/></label><p>PDF, DOC ou DOCX, até 20 MB. O tipo será classificado automaticamente.</p>{busy&&<div className="upload-progress" aria-live="polite"><progress max="100" value={progress}/><strong>{phase==='uploading'?'Enviando arquivo…':'Analisando documento'}</strong></div>}{result?.warnings?.map((warning)=><FeedbackMessage type="info" key={warning}>{warning}</FeedbackMessage>)}<div className="row-actions">{phase==='idle'&&<button className="button" disabled={!file} onClick={start}>Analisar documento</button>}{['failed','limited'].includes(phase)&&<button className="button" onClick={retry}>Tentar novamente</button>}{analysis&&phase!=='success'&&<button className="button secondary" onClick={cancel} disabled={busy}>Cancelar</button>}{phase==='success'&&<button className="button" onClick={()=>{setFlow(emptyState);setPhase('idle');setMessage('')}}>Analisar outro documento</button>}</div></section>}{['review','saving'].includes(phase)&&reviewed&&<CommercialDocumentReview analysis={analysis} result={result} reviewed={reviewed} onReviewedChange={(updater)=>setFlow((current)=>({...current,reviewed:typeof updater==='function'?updater(current.reviewed):updater}))} onDocumentTypeChange={changeDocumentType} duplicates={duplicates} clientAction={clientAction} setClientAction={setClientAction} clientId={clientId} setClientId={setClientId} entityAction={entityAction} setEntityAction={setEntityAction} entityId={entityId} setEntityId={setEntityId} relatedProposalId={relatedProposalId} setRelatedProposalId={setRelatedProposalId} confirmations={confirmations} setConfirmations={setConfirmations} onConfirm={confirm} onCancel={cancel} saving={phase==='saving'} importStage={importStage}/>}</>}</div>
}
