import {useEffect,useState} from 'react'
import {Archive,ArrowLeft,ArrowRight,CalendarDays,CheckCircle2,Clock3,MessageCircle,Play,Plus,Users} from 'lucide-react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {addTaskObservation,archiveTask,createTask,getOperationalSummary,listOperationalEvents,listTasks,taskShortId,updateTask} from '../services/data/tasksRepository'
import {addIsoDays,groupByDate,isoInSaoPaulo,monthGrid,operationMetrics,projectTasks,weekDays} from '../lib/operationalCalendar'
import {useAuth} from '../contexts/AuthContext'

const labels={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'}
const dayNames=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo']
const viewCopy={today:['Meu Dia','Prioridades, atendimentos e próximos passos em uma visão prática.'],week:['Semana','Planeje a carga da equipe sem duplicar tarefas.'],month:['Calendário','Tarefas e eventos operacionais no mês.'],backlog:['Backlog','Tarefas sem data, prontas para priorizar e planejar.'],history:['Histórico','Registro estruturado da operação para acompanhamento e retrospectivas.']}
const empty=(date='')=>({title:'',assigned_to:'',due_date:date,due_time:'',priority:'medium',task_type:'general',notes:'',tags:[]})
const displayDate=(iso,options={day:'2-digit',month:'short'})=>new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',...options}).format(new Date(`${iso}T12:00:00Z`))

function TaskCard({item,canOperate,onEdit,onMutate,onObserve,onArchive,onNavigate}){
  const related=item.clients?.company_name||item.commercial_opportunities?.name||item.proposals?.title||item.contracts?.contract_number||'Interna'
  return <article className={`operation-task ${item.status}`}><header><span className={`task-priority ${item.priority}`}>{labels[item.priority]}</span><code>{taskShortId(item.id)}</code>{item.due_time&&<time>{item.due_time.slice(0,5)}</time>}</header><h3>{item.title}</h3><p>{related}{item.tags?.length?` · ${item.tags.join(' · ')}`:''}</p><footer>{item.client_id&&<button onClick={()=>onNavigate('clients')}>Cliente</button>}{item.commercial_opportunities?.conversation_id&&<button onClick={()=>onNavigate('inbox')}><MessageCircle size={13}/> Conversa</button>}{canOperate&&item.status==='pending'&&<button onClick={()=>onMutate(item,{status:'in_progress'})}><Play size={13}/> Iniciar</button>}{canOperate&&item.status!=='completed'&&<button onClick={()=>onMutate(item,{status:'completed'})}><CheckCircle2 size={13}/> Concluir</button>}{canOperate&&<button onClick={()=>onEdit(item)}>Reagendar</button>}{canOperate&&<button onClick={()=>onObserve(item)}>Observação</button>}{canOperate&&<button aria-label="Arquivar tarefa" onClick={()=>onArchive(item)}><Archive size={13}/></button>}</footer></article>
}

export function OperationsHubPage({view='today',teamMembers=[],onNavigate=()=>{}}){
  const {canOperate,canAccessFinance}=useAuth(),today=isoInSaoPaulo(),[anchor,setAnchor]=useState(today),[tasks,setTasks]=useState({available:true,items:[]}),[events,setEvents]=useState({available:true,items:[]}),[summary,setSummary]=useState({}),[editing,setEditing]=useState(null),[form,setForm]=useState(empty(today)),[selectedDay,setSelectedDay]=useState(null),[error,setError]=useState('')
  const load=()=>Promise.all([listTasks(),listOperationalEvents(),getOperationalSummary()]).then(([taskRows,eventRows,operational])=>{setTasks(taskRows);setEvents(eventRows);setSummary(operational)}).catch((cause)=>setError(cause.message))
  useEffect(()=>{load()},[])
  const projected=projectTasks(tasks.items,{view,anchor}),groups=groupByDate(projected),metrics=operationMetrics(projected,today)
  const title=viewCopy[view]||viewCopy.today
  async function mutate(item,patch){setError('');try{await updateTask(item.id,patch);await load()}catch(cause){setError(cause.message)}}
  function edit(item){setEditing(item.id);setForm({title:item.title||'',assigned_to:item.assigned_to||'',due_date:item.due_date||'',due_time:item.due_time||'',priority:item.priority||'medium',task_type:item.task_type||'general',notes:item.notes||'',tags:item.tags||[]})}
  function create(date=view==='backlog'?'':anchor){setEditing('new');setForm(empty(date))}
  async function submit(event){event.preventDefault();try{const payload={...form,tags:Array.isArray(form.tags)?form.tags:String(form.tags).split(',').map((tag)=>tag.trim()).filter(Boolean),assigned_to:form.assigned_to||null,due_date:form.due_date||null};if(editing==='new')await createTask(payload);else await updateTask(editing,payload);setEditing(null);await load()}catch(cause){setError(cause.message)}}
  async function observe(item){const body=window.prompt('Observação para o histórico da tarefa:');if(body)try{await addTaskObservation(item,body);await load()}catch(cause){setError(cause.message)}}
  async function archive(item){if(window.confirm(`Arquivar “${item.title}”?`))try{await archiveTask(item.id);await load()}catch(cause){setError(cause.message)}}
  const nav=(amount)=>{setSelectedDay(null);if(view!=='month'){setAnchor(addIsoDays(anchor,amount*7));return}const date=new Date(`${anchor}T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()+amount,1);setAnchor(date.toISOString().slice(0,10))}
  return <div className="operations-hub-page"><PageHeader eyebrow="Central Operacional Mugô" title={title[0]} description={title[1]} actions={canOperate&&<button className="button" onClick={()=>create()}><Plus size={15}/> Nova tarefa</button>}/>
    {error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{!tasks.available&&<FeedbackMessage type="info">Aplique a migration da Central Operacional para liberar esta visão.</FeedbackMessage>}
    {['week','month'].includes(view)&&<div className="calendar-toolbar"><button onClick={()=>nav(-1)} aria-label="Anterior"><ArrowLeft size={15}/></button><strong>{view==='week'?`${displayDate(weekDays(anchor)[0])} — ${displayDate(weekDays(anchor)[6])}`:displayDate(anchor,{month:'long',year:'numeric'})}</strong><button onClick={()=>setAnchor(today)}>Hoje</button><button onClick={()=>nav(1)} aria-label="Próximo"><ArrowRight size={15}/></button></div>}
    {view!=='history'&&<section className="operation-metrics"><article><strong>{metrics.total}</strong><span>Tarefas</span></article><article><strong>{metrics.completed}</strong><span>Concluídas</span></article><article><strong>{metrics.pending}</strong><span>Pendentes</span></article><article><strong>{metrics.overdue}</strong><span>Atrasadas</span></article></section>}
    {view==='today'&&<><section className="operations-snapshot"><button onClick={()=>onNavigate('inbox')}><MessageCircle/><div><small>Atendimento</small><strong>{summary.unread||0} não lidas</strong><span>{summary.waitingHuman||0} aguardando humano</span></div><ArrowRight/></button><button onClick={()=>onNavigate('commercial')}><Users/><div><small>Comercial</small><strong>{summary.hotLeads||0} leads em atenção</strong><span>{summary.newLeads||0} novos</span></div><ArrowRight/></button>{canAccessFinance&&<button onClick={()=>onNavigate('finance-today')}><Clock3/><div><small>Financeiro</small><strong>{summary.pendingCharges||0} pendências</strong><span>{summary.overdueCharges||0} vencidas</span></div><ArrowRight/></button>}<article><CalendarDays/><div><small>Atividades</small><strong>{events.items.slice(0,5).length} recentes</strong><span>decisões, observações e entregas</span></div></article></section><section className="day-sections"><div><h2>Atrasadas</h2>{projected.filter((task)=>task.due_date<today&&task.status!=='completed').map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate}/>)}</div><div><h2>Hoje</h2>{projected.filter((task)=>task.due_date===today).map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate}/>)}</div></section></>}
    {view==='week'&&<><section className="week-board">{weekDays(anchor).map((day,index)=><div className={day===today?'today':''} key={day}><header><strong>{dayNames[index]}</strong><span>{displayDate(day)}</span></header>{(groups[day]||[]).map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate}/>)}</div>)}</section><section className="team-load">{teamMembers.map((member)=><span key={member.id}><b>{member.name}</b>{projected.filter((task)=>task.assigned_to===member.id&&task.status!=='completed').length} pendentes</span>)}</section></>}
    {view==='month'&&<section className="month-grid">{monthGrid(anchor).map((day)=>{const outside=day.slice(0,7)!==anchor.slice(0,7),rows=groups[day]||[];return <button className={`${outside?'outside ':''}${day===today?'today':''}`} key={day} onClick={()=>setSelectedDay(day)}><strong>{Number(day.slice(-2))}</strong>{rows.slice(0,3).map((item)=><span key={item.id}>{item.due_time?.slice(0,5)||'•'} {item.title}</span>)}{rows.length>3&&<small>+{rows.length-3} itens</small>}</button>})}</section>}
    {view==='backlog'&&<section className="backlog-list">{projected.map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate}/>)}{!projected.length&&<p className="empty-state">Backlog em dia. Nenhuma tarefa sem data.</p>}</section>}
    {view==='history'&&<section className="operational-history">{events.items.map((event)=><article key={event.id}><span className="history-dot"/><div><header><strong>{event.title}</strong><time>{new Date(event.occurred_at).toLocaleString('pt-BR')}</time></header><p>{event.description||event.crm_tasks?.title||event.clients?.company_name||'Registro operacional'}</p><small>{event.team_members?.name||'Sistema'} · {event.event_type.replaceAll('_',' ')}</small></div></article>)}{!events.items.length&&<p className="empty-state">Nenhuma atividade registrada.</p>}</section>}
    {selectedDay&&<><button className="drawer-backdrop" aria-label="Fechar" onClick={()=>setSelectedDay(null)}/><aside className="operation-day-drawer"><header><div><small>Agenda do dia</small><h2>{displayDate(selectedDay,{weekday:'long',day:'2-digit',month:'long'})}</h2></div><button onClick={()=>setSelectedDay(null)}>×</button></header><button className="button" onClick={()=>create(selectedDay)}><Plus size={14}/> Criar tarefa</button>{(groups[selectedDay]||[]).map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate}/>)}</aside></>}
    {editing&&<div className="modal-overlay"><section className="task-form-modal" role="dialog" aria-modal="true"><h2>{editing==='new'?'Nova tarefa':'Editar tarefa'}</h2><form onSubmit={submit}><label>Título<input required value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})}/></label><label>Responsável<select value={form.assigned_to} onChange={(event)=>setForm({...form,assigned_to:event.target.value})}><option value="">Sem responsável</option>{teamMembers.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><div className="task-form-row"><label>Data<input type="date" value={form.due_date||''} onChange={(event)=>setForm({...form,due_date:event.target.value})}/></label><label>Horário<input type="time" value={form.due_time||''} onChange={(event)=>setForm({...form,due_time:event.target.value})}/></label></div><div className="task-form-row"><label>Prioridade<select value={form.priority} onChange={(event)=>setForm({...form,priority:event.target.value})}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Tipo<select value={form.task_type} onChange={(event)=>setForm({...form,task_type:event.target.value})}><option value="general">Tarefa</option><option value="follow_up">Follow-up</option><option value="meeting">Reunião</option><option value="delivery">Entrega</option><option value="activity">Atividade</option></select></label></div><label>Tags<input value={Array.isArray(form.tags)?form.tags.join(', '):form.tags} onChange={(event)=>setForm({...form,tags:event.target.value})} placeholder="site, cliente"/></label><label>Notas<textarea rows="4" value={form.notes} onChange={(event)=>setForm({...form,notes:event.target.value})}/></label><footer><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="button">Salvar</button></footer></form></section></div>}
  </div>
}
