import {useEffect,useState} from 'react'
import {Archive,ArrowLeft,ArrowRight,CalendarDays,CheckCircle2,Clock3,MessageCircle,Play,Plus,Users} from 'lucide-react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {addTaskObservation,archiveTask,createTask,getOperationalSettings,getOperationalSummary,listOperationalEvents,listTasks,recordOperationalEvent,taskShortId,updateTask} from '../services/data/tasksRepository'
import {addIsoDays,groupByDate,isHistoricalTask,isoInSaoPaulo,monthGrid,operationMetrics,projectTasks,summarizeOperationHours,taskCategoryScope,weekDays} from '../lib/operationalCalendar'
import {useAuth} from '../contexts/AuthContext'

const labels={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'}
const dayNames=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo']
const viewCopy={today:['Meu Dia','Rotina, trabalho, atendimento, comercial e financeiro em uma visão prática.'],week:['Semana','Planeje a carga da equipe sem duplicar tarefas.'],month:['Calendário','Tarefas, rotina e compromissos no mês.'],backlog:['Backlog','Tarefas sem data, prontas para priorizar e planejar.'],history:['Concluídos','Tarefas concluídas na mesma fonte operacional.']}
const categories=['Trabalho','Laura','Família','Júlia + Kleber','Treino','Estudo','Casa','Alimentação','Tempo livre','Cliente','Comercial','Administrativo','Financeiro','Desenvolvimento','Conteúdo','Tráfego','Design','Atendimento']
const empty=(date='')=>({title:'',assigned_to:'',due_date:date,due_time:'',end_time:'',priority:'medium',task_type:'general',category:'Trabalho',planned_hours:'',worked_hours:'',fixed:false,notes:'',tags:[]})
const displayDate=(iso,options={day:'2-digit',month:'short'})=>new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',...options}).format(new Date(`${iso}T12:00:00Z`))
// created_at é um timestamptz real (quando a tarefa entrou no CRM) — diferente de due_date/due_time
// (prazo). Sempre em America/Sao_Paulo, nunca UTC.
const formatRegisteredAt=(createdAt)=>{
  if(!createdAt)return null
  const date=new Date(createdAt)
  const datePart=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric'}).format(date)
  const timePart=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(date)
  return `${datePart} às ${timePart}`
}

function TaskCard({item,canOperate,onEdit,onMutate,onObserve,onArchive,onNavigate,onHours,operationalStartDate}){
  const related=item.clients?.company_name||item.commercial_opportunities?.name||item.proposals?.title||item.contracts?.contract_number||'Interna'
  return <article className={`operation-task ${item.status}`}><header><span className={`task-priority ${item.priority}`}>{labels[item.priority]}</span>{isHistoricalTask(item,operationalStartDate)&&<span className="task-priority">Histórico anterior à virada</span>}<code>{taskShortId(item.id)}</code>{item.due_time&&<time>{item.due_time.slice(0,5)}{item.ends_at?`–${new Date(item.ends_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`:''}</time>}</header><h3>{item.title}</h3><p>{item.category||'Trabalho'} · {related}{item.tags?.length?` · ${item.tags.join(' · ')}`:''}</p>{(item.planned_hours||item.worked_hours)&&<small>{Number(item.planned_hours||0)}h planejadas · {Number(item.worked_hours||0)}h realizadas{item.fixed?' · Fixo':''}</small>}{item.created_at&&<small className="task-registered-at">Registrada em {formatRegisteredAt(item.created_at)}</small>}<footer>{item.client_id&&<button onClick={()=>onNavigate('clients')}>Cliente</button>}{item.commercial_opportunities?.conversation_id&&<button onClick={()=>onNavigate('inbox')}><MessageCircle size={13}/> Conversa</button>}{canOperate&&item.status==='pending'&&<button onClick={()=>onMutate(item,{status:'in_progress',starts_at:item.starts_at||new Date().toISOString()})}><Play size={13}/> Iniciar</button>}{canOperate&&item.status!=='completed'&&<button onClick={()=>onMutate(item,{status:'completed',ends_at:new Date().toISOString()})}><CheckCircle2 size={13}/> Concluir</button>}{canOperate&&<button onClick={()=>onHours(item)}>Horas</button>}{canOperate&&<button onClick={()=>onEdit(item)}>Reagendar</button>}{canOperate&&<button onClick={()=>onObserve(item)}>Observação</button>}{canOperate&&<button aria-label="Arquivar tarefa" onClick={()=>onArchive(item)}><Archive size={13}/></button>}</footer></article>
}

export function OperationsHubPage({view='today',teamMembers=[],onNavigate=()=>{}}){
  const {canOperate,canAccessFinance}=useAuth(),today=isoInSaoPaulo(),[anchor,setAnchor]=useState(today),[tasks,setTasks]=useState({available:true,items:[]}),[events,setEvents]=useState({available:true,items:[]}),[summary,setSummary]=useState({}),[settings,setSettings]=useState({weekly_target_hours:35}),[calendarFilter,setCalendarFilter]=useState('all'),[editing,setEditing]=useState(null),[form,setForm]=useState(empty(today)),[selectedDay,setSelectedDay]=useState(null),[error,setError]=useState('')
  const load=()=>Promise.all([listTasks(),listOperationalEvents(),getOperationalSummary(),getOperationalSettings()]).then(([taskRows,eventRows,operational,operationalSettings])=>{setTasks(taskRows);setEvents(eventRows);setSummary(operational);setSettings(operationalSettings)}).catch((cause)=>setError(cause.message))
  useEffect(()=>{load()},[])
  const cutover=settings.operational_start_date||'2026-09-24',projected=projectTasks(tasks.items,{view,anchor,operationalStartDate:cutover}),visibleProjected=['week','month'].includes(view)&&calendarFilter!=='all'?projected.filter(item=>taskCategoryScope(item)===calendarFilter):projected,groups=groupByDate(visibleProjected),metrics=operationMetrics(visibleProjected,today),hours=summarizeOperationHours(visibleProjected,view==='week'?settings.weekly_target_hours:0),currentTasks=tasks.items.filter(item=>!isHistoricalTask(item,cutover)),todayHours=summarizeOperationHours(currentTasks.filter(item=>item.due_date===today),0),weekRange=weekDays(anchor),weekTasks=projectTasks(tasks.items,{view:'week',anchor,operationalStartDate:cutover}).filter(item=>calendarFilter==='all'||taskCategoryScope(item)===calendarFilter),weekHours=summarizeOperationHours(weekTasks,settings.weekly_target_hours),currentEvents=events.items.filter(event=>String(event.occurred_at||'').slice(0,10)>=cutover),recordedToday=currentEvents.filter(event=>event.event_type==='time_recorded'&&isoInSaoPaulo(new Date(event.occurred_at))===today).reduce((sum,event)=>sum+Number(event.metadata?.hours||0),0),recordedWeek=currentEvents.filter(event=>{const date=isoInSaoPaulo(new Date(event.occurred_at));return event.event_type==='time_recorded'&&date>=weekRange[0]&&date<=weekRange[6]}).reduce((sum,event)=>sum+Number(event.metadata?.hours||0),0),weeklyWorked=weekHours.worked+recordedWeek,dailyWorked=todayHours.worked+recordedToday,weekProgress=weekHours.target?Math.min(weeklyWorked/weekHours.target*100,100):0
  const title=viewCopy[view]||viewCopy.today
  async function mutate(item,patch){setError('');try{await updateTask(item.id,patch);await load()}catch(cause){setError(cause.message)}}
  function edit(item){setEditing(item.id);setForm({title:item.title||'',assigned_to:item.assigned_to||'',due_date:item.due_date||'',due_time:item.due_time||'',end_time:item.ends_at?new Date(item.ends_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'',priority:item.priority||'medium',task_type:item.task_type||'general',category:item.category||'Trabalho',planned_hours:item.planned_hours??'',worked_hours:item.worked_hours??'',fixed:Boolean(item.fixed),notes:item.notes||'',tags:item.tags||[]})}
  function create(date=view==='backlog'?'':anchor){setEditing('new');setForm(empty(date))}
  async function submit(event){event.preventDefault();try{const startsAt=form.due_date&&form.due_time?`${form.due_date}T${form.due_time}:00-03:00`:null,endsAt=form.due_date&&form.end_time?`${form.due_date}T${form.end_time}:00-03:00`:null,values={...form};delete values.end_time;const payload={...values,starts_at:startsAt,ends_at:endsAt,planned_hours:form.planned_hours===''?null:Number(form.planned_hours),worked_hours:form.worked_hours===''?null:Number(form.worked_hours),tags:Array.isArray(form.tags)?form.tags:String(form.tags).split(',').map((tag)=>tag.trim()).filter(Boolean),assigned_to:form.assigned_to||null,due_date:form.due_date||null};if(editing==='new')await createTask(payload);else await updateTask(editing,payload);setEditing(null);await load()}catch(cause){setError(cause.message)}}
  async function observe(item){const body=window.prompt('Observação para o histórico da tarefa:');if(body)try{await addTaskObservation(item,body);await load()}catch(cause){setError(cause.message)}}
  async function registerHours(item){const raw=window.prompt('Quantas horas foram realizadas?',String(item.worked_hours||''));if(raw===null)return;const value=Number(String(raw).replace(',','.'));if(!Number.isFinite(value)||value<0){setError('Informe uma quantidade válida de horas.');return}await mutate(item,{worked_hours:value})}
  async function quickHours(){const raw=window.prompt('Quantas horas você trabalhou hoje?');if(raw===null)return;const value=Number(String(raw).replace(',','.'));if(!Number.isFinite(value)||value<=0){setError('Informe uma quantidade válida de horas.');return}await recordOperationalEvent({event_type:'time_recorded',title:'Horas registradas',description:`${value}h trabalhadas`,metadata:{hours:value}});await load()}
  async function quickDecision(){const description=window.prompt('Qual decisão deseja registrar?');if(!description?.trim())return;await recordOperationalEvent({event_type:'decision_recorded',title:'Decisão registrada',description:description.trim()});await load()}
  async function archive(item){if(window.confirm(`Arquivar “${item.title}”?`))try{await archiveTask(item.id);await load()}catch(cause){setError(cause.message)}}
  const nav=(amount)=>{setSelectedDay(null);if(view!=='month'){setAnchor(addIsoDays(anchor,amount*7));return}const date=new Date(`${anchor}T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()+amount,1);setAnchor(date.toISOString().slice(0,10))}
  return <div className="operations-hub-page"><PageHeader eyebrow="Central Operacional Mugô" title={title[0]} description={title[1]} actions={canOperate&&<button className="button" onClick={()=>create()}><Plus size={15}/> Nova tarefa</button>}/>
    {error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{!tasks.available&&<FeedbackMessage type="info">Aplique a migration da Central Operacional para liberar esta visão.</FeedbackMessage>}
    {['week','month'].includes(view)&&<div className="calendar-toolbar"><button onClick={()=>nav(-1)} aria-label="Anterior"><ArrowLeft size={15}/></button><strong>{view==='week'?`${displayDate(weekDays(anchor)[0])} — ${displayDate(weekDays(anchor)[6])}`:displayDate(anchor,{month:'long',year:'numeric'})}</strong><button onClick={()=>setAnchor(today)}>Hoje</button><button onClick={()=>nav(1)} aria-label="Próximo"><ArrowRight size={15}/></button></div>}
    {view==='today'?<><section className="operation-metrics"><article><strong>{today}</strong><span>Hoje</span></article><article><strong>{todayHours.planned.toFixed(1)}h</strong><span>Horas planejadas</span></article><article><strong>{dailyWorked.toFixed(1)}h</strong><span>Horas realizadas</span></article><article><strong>{(dailyWorked-todayHours.planned).toFixed(1)}h</strong><span>Saldo do dia</span></article><article><strong>{weekProgress.toFixed(0)}%</strong><span>Meta semanal · {settings.weekly_target_hours}h</span></article></section><nav className="today-filters" aria-label="Ações rápidas"><button onClick={()=>create(today)}>Nova tarefa</button><button onClick={quickHours}>Registrar horas</button>{canAccessFinance&&<><button onClick={()=>onNavigate('accounts-payable')}>Registrar gasto</button><button onClick={()=>onNavigate('finance')}>Registrar recebimento</button></>}<button onClick={()=>onNavigate('nova')}>Criar proposta</button><button onClick={quickDecision}>Anotar decisão</button></nav></>:view==='week'?<section className="operation-metrics"><article><strong>{hours.target.toFixed(1)}h</strong><span>Meta semanal</span></article><article><strong>{hours.planned.toFixed(1)}h</strong><span>Planejadas</span></article><article><strong>{weeklyWorked.toFixed(1)}h</strong><span>Realizadas · {weekProgress.toFixed(0)}%</span></article><article><strong>{Math.max(hours.target-weeklyWorked,0).toFixed(1)}h</strong><span>Restantes</span></article><article><strong>{metrics.completed}</strong><span>Concluídas</span></article><article><strong>{metrics.pending}</strong><span>Pendentes</span></article></section>:view!=='history'&&<section className="operation-metrics"><article><strong>{metrics.total}</strong><span>Tarefas</span></article><article><strong>{metrics.completed}</strong><span>Concluídas</span></article><article><strong>{metrics.pending}</strong><span>Pendentes</span></article><article><strong>{metrics.overdue}</strong><span>Atrasadas</span></article></section>}
    {view==='today'&&<><section className="operations-snapshot"><button onClick={()=>onNavigate('inbox')}><MessageCircle/><div><small>Atendimento</small><strong>{summary.unread||0} não lidas</strong><span>{summary.waitingHuman||0} aguardando humano</span></div><ArrowRight/></button><button onClick={()=>onNavigate('commercial')}><Users/><div><small>Comercial</small><strong>{summary.hotLeads||0} clientes em atenção</strong><span>{summary.newLeads||0} novos</span></div><ArrowRight/></button>{canAccessFinance&&<button onClick={()=>onNavigate('finance-today')}><Clock3/><div><small>Financeiro</small><strong>{summary.pendingCharges||0} cobranças para ação</strong><span>{summary.overdueCharges||0} vencidas</span></div><ArrowRight/></button>}<article><CalendarDays/><div><small>Atividades recentes</small><strong>{currentEvents.slice(0,5).length} registros</strong><span>decisões, observações e entregas</span></div></article></section><section className="day-sections"><div><h2>Atrasadas</h2>{projected.filter((task)=>task.due_date<today&&task.status!=='completed').map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours}/>)}</div><div><h2>Rotina</h2>{projected.filter((task)=>task.due_date===today&&(task.fixed||taskCategoryScope(task)==='personal')).map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours}/>)}</div><div><h2>Tarefas e compromissos</h2>{projected.filter((task)=>task.due_date===today&&!task.fixed&&taskCategoryScope(task)!=='personal').map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours}/>)}</div><div><h2>Atividades recentes</h2>{currentEvents.slice(0,5).map(event=><article className="operation-task" key={event.id}><h3>{event.title}</h3><p>{event.description||'Registro operacional'}</p><small>{new Date(event.occurred_at).toLocaleString('pt-BR')}</small></article>)}</div></section></>}
    {['week','month'].includes(view)&&<nav className="today-filters" aria-label="Filtrar calendário">{[['all','Tudo'],['work','Trabalho'],['personal','Pessoal'],['clients','Cliente'],['financial','Financeiro']].map(([id,label])=><button className={calendarFilter===id?'active':''} key={id} onClick={()=>setCalendarFilter(id)}>{label}</button>)}</nav>}
    {view==='week'&&<><section className="week-board">{weekDays(anchor).map((day,index)=><div className={day===today?'today':''} key={day}><header><strong>{dayNames[index]}</strong><span>{displayDate(day)}</span></header>{(groups[day]||[]).map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours} operationalStartDate={cutover}/>)}</div>)}</section><section className="backlog-list"><h2>Tarefas sem data</h2>{projectTasks(tasks.items,{view:'backlog',operationalStartDate:cutover}).filter(item=>calendarFilter==='all'||taskCategoryScope(item)===calendarFilter).map(item=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours} operationalStartDate={cutover}/>)}</section><section className="team-load">{teamMembers.map((member)=><span key={member.id}><b>{member.name}</b>{visibleProjected.filter((task)=>task.assigned_to===member.id&&task.status!=='completed').length} pendentes</span>)}</section></>}
    {view==='month'&&<section className="month-grid">{monthGrid(anchor).map((day)=>{const outside=day.slice(0,7)!==anchor.slice(0,7),rows=groups[day]||[];return <button className={`${outside?'outside ':''}${day===today?'today':''}`} key={day} onClick={()=>setSelectedDay(day)}><strong>{Number(day.slice(-2))}</strong>{rows.length>0&&<span>{rows.length} {rows.length===1?'item':'itens'}</span>}{rows.length>0&&<small>{[...new Set(rows.map(taskCategoryScope))].slice(0,2).join(' · ')}</small>}</button>})}</section>}
    {view==='backlog'&&<section className="backlog-list">{projected.map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours}/>)}{!projected.length&&<p className="empty-state">Backlog em dia. Nenhuma tarefa sem data.</p>}</section>}
    {view==='history'&&<section className="backlog-list">{projected.map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours} operationalStartDate={cutover}/>)}{!projected.length&&<p className="empty-state">Nenhuma tarefa concluída ou anterior à virada.</p>}</section>}
    {selectedDay&&<><button className="drawer-backdrop" aria-label="Fechar" onClick={()=>setSelectedDay(null)}/><aside className="operation-day-drawer"><header><div><small>Agenda do dia</small><h2>{displayDate(selectedDay,{weekday:'long',day:'2-digit',month:'long'})}</h2></div><button onClick={()=>setSelectedDay(null)}>×</button></header><button className="button" onClick={()=>create(selectedDay)}><Plus size={14}/> Criar tarefa</button>{(groups[selectedDay]||[]).map((item)=><TaskCard key={item.id} item={item} canOperate={canOperate} onEdit={edit} onMutate={mutate} onObserve={observe} onArchive={archive} onNavigate={onNavigate} onHours={registerHours}/>)}</aside></>}
    {editing&&<div className="modal-overlay"><section className="task-form-modal" role="dialog" aria-modal="true"><h2>{editing==='new'?'Nova tarefa':'Editar tarefa'}</h2><form onSubmit={submit}><label>Título<input required value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})}/></label><label>Responsável<select value={form.assigned_to} onChange={(event)=>setForm({...form,assigned_to:event.target.value})}><option value="">Sem responsável</option>{teamMembers.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><div className="task-form-row"><label>Categoria<select value={form.category} onChange={(event)=>setForm({...form,category:event.target.value})}>{categories.map(category=><option value={category} key={category}>{category}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={form.fixed} onChange={(event)=>setForm({...form,fixed:event.target.checked})}/> Recorrente/fixo</label></div><div className="task-form-row"><label>Data<input type="date" value={form.due_date||''} onChange={(event)=>setForm({...form,due_date:event.target.value})}/></label><label>Início<input type="time" value={form.due_time||''} onChange={(event)=>setForm({...form,due_time:event.target.value})}/></label><label>Fim<input type="time" value={form.end_time||''} onChange={(event)=>setForm({...form,end_time:event.target.value})}/></label></div><div className="task-form-row"><label>Horas planejadas<input type="number" min="0" step="0.25" value={form.planned_hours} onChange={(event)=>setForm({...form,planned_hours:event.target.value})}/></label><label>Horas realizadas<input type="number" min="0" step="0.25" value={form.worked_hours} onChange={(event)=>setForm({...form,worked_hours:event.target.value})}/></label></div><div className="task-form-row"><label>Prioridade<select value={form.priority} onChange={(event)=>setForm({...form,priority:event.target.value})}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Tipo<select value={form.task_type} onChange={(event)=>setForm({...form,task_type:event.target.value})}><option value="general">Tarefa</option><option value="follow_up">Follow-up</option><option value="meeting">Reunião</option><option value="delivery">Entrega</option><option value="activity">Atividade</option><option value="commercial">Comercial</option></select></label></div><label>Tags<input value={Array.isArray(form.tags)?form.tags.join(', '):form.tags} onChange={(event)=>setForm({...form,tags:event.target.value})} placeholder="site, cliente"/></label><label>Observações<textarea rows="4" value={form.notes} onChange={(event)=>setForm({...form,notes:event.target.value})}/></label><footer><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="button">Salvar</button></footer></form></section></div>}
  </div>
}
