import {useEffect,useRef} from 'react'
import {ExternalLink,Pencil,X} from 'lucide-react'
import {ContractBadge,ProposalStatusBadge} from './ProposalStatusBadge'
const currency=(value)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0)
const date=(value)=>value?new Date(value).toLocaleDateString('pt-BR'):'Não informado'
export function ProposalDetailsPanel({proposal,onClose,onEdit}){const closeRef=useRef(null);useEffect(()=>{if(!proposal)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const keyboard=(event)=>event.key==='Escape'&&onClose();document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('keydown',keyboard);document.body.style.overflow=overflow}},[proposal,onClose]);if(!proposal)return null
return <div className="details-overlay" role="presentation" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><aside className="proposal-details" role="dialog" aria-modal="true" aria-labelledby="proposal-details-title">
  <header><div><p>{proposal.proposalNumber||'Proposta comercial'}</p><h2 id="proposal-details-title">{proposal.title}</h2></div><button ref={closeRef} type="button" className="icon-button" onClick={onClose} aria-label="Fechar detalhes"><X size={19}/></button></header>
  <div className="details-badges"><ProposalStatusBadge status={proposal.status}/><ContractBadge signed={proposal.hasContract}/></div>
  <section className="details-values"><div><span>Implantação</span><strong>{currency(proposal.setupValue)}</strong></div><div><span>Mensalidade</span><strong>{currency(proposal.monthlyValue)}</strong></div><div><span>Total</span><strong>{currency(proposal.totalValue)}</strong></div></section>
  <dl className="details-list"><div><dt>Cliente</dt><dd>{proposal.clientName}</dd></div><div><dt>Empresa</dt><dd>{proposal.companyName}</dd></div><div><dt>Contato</dt><dd>{proposal.contactName||'Não informado'}</dd></div><div><dt>Responsável</dt><dd>{proposal.responsibleName||'Não informado'}</dd></div><div><dt>Envio</dt><dd>{date(proposal.sentAt)}</dd></div><div><dt>Validade</dt><dd>{date(proposal.validUntil)}</dd></div><div><dt>Prazo</dt><dd>{proposal.contractTermMonths?`${proposal.contractTermMonths} meses`:'Não informado'}</dd></div><div><dt>Origem</dt><dd>{proposal.leadSource||'Não informada'}</dd></div><div className="detail-wide"><dt>Observações</dt><dd>{proposal.notes||'Não informado'}</dd></div></dl>
  <section className="detail-wide"><h3>Serviços</h3><div className="table-scroll"><table className="proposal-list-table"><thead><tr><th>Serviço</th><th>Categoria</th><th>Qtd.</th><th>Unitário</th><th>Implantação</th><th>Mensal</th></tr></thead><tbody>{proposal.services.map((service)=><tr key={service.id||service.name}><td>{service.name}</td><td>{service.category||'—'}</td><td>{service.quantity??'—'}</td><td>{currency(service.unitPrice)}</td><td>{currency(service.oneTimeValue)}</td><td>{currency(service.monthlyValue)}</td></tr>)}</tbody></table></div>{!proposal.services.length&&<p>Nenhum serviço relacionado.</p>}</section>
  <section className="detail-wide"><h3>Documentos</h3>{proposal.documents.map((document)=><p key={document.id}>{document.file_name} <small>v{document.version||1}</small></p>)}{!proposal.documents.length&&<p>Nenhum documento relacionado.</p>}</section>
  <section className="detail-wide"><h3>Linha do tempo comercial</h3>{[...proposal.history].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map((item)=><p key={item.id}><strong>{item.title}</strong> <small>{date(item.created_at)}</small><br/>{item.description}</p>)}{!proposal.history.length&&<p>Nenhum evento registrado.</p>}</section>
  <footer><button type="button" className="button" onClick={()=>onEdit(proposal)}><Pencil size={14}/>Editar</button>{proposal.proposalFile&&<a className="button secondary" href={proposal.proposalFile.public_url||proposal.proposalFile.url||'#'} target="_blank" rel="noreferrer">Abrir proposta<ExternalLink size={13}/></a>}</footer>
</aside></div>}
