import { useEffect, useRef } from 'react'
import { FeedbackMessage } from './FeedbackMessage'
import { callIfFunction } from '../lib/callbackSafety'
import { isValidBrazilianPhone } from '../lib/whatsapp'

const preview=name=>`Olá, ${name}. Tudo bem?\n\nTemos uma informação financeira referente aos serviços da Mugô que precisa da sua atenção.\n\nPara consultar os detalhes e as opções de pagamento, toque no botão abaixo.\n\nCaso já tenha tratado esse assunto com nossa equipe, desconsidere esta mensagem.`
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0))
export function StartWhatsAppConversationModal({ client, installment, phone, canWrite, loading, templateConfigured=true, templateStatus='', templateError='', syncing=false, onClose, onStart, onSync }) {
  const dialog=useRef(null),name=String(client.contact_name||client.trade_name||client.company_name||'Cliente').trim().split(/\s+/)[0]
  useEffect(()=>{dialog.current?.focus()},[])
  const paid=installment.status==='paid',invalid=!isValidBrazilianPhone(phone),disabled=invalid||!templateConfigured||paid||loading||!canWrite
  const templateMessage=templateStatus==='PENDING'?'O template de cobrança ainda está em aprovação na Meta.':templateStatus==='REJECTED'?'O template foi rejeitado pela Meta. Revise o modelo antes de tentar novamente.':templateStatus==='PAUSED'?'O template de cobrança está pausado na Meta.':templateStatus==='DISABLED'?'O template foi desativado na Meta.':templateStatus==='SYNC_ERROR'?(templateError||'Não foi possível consultar o template na Meta.'):'O template não foi encontrado na Meta para o idioma pt_BR.'
  return <div className="modal-overlay" onMouseDown={event=>event.target===event.currentTarget&&callIfFunction(onClose)}><section className="whatsapp-modal start-conversation-modal" role="dialog" aria-modal="true" tabIndex="-1" ref={dialog}><h2>Iniciar conversa</h2><dl><div><dt>Cliente</dt><dd>{client.contact_name||client.company_name}</dd></div><div><dt>Empresa</dt><dd>{client.company_name}</dd></div><div><dt>Telefone</dt><dd>{phone}</dd></div><div><dt>Parcela</dt><dd>{installment.reference_month||installment.id}</dd></div><div><dt>Vencimento</dt><dd>{installment.due_date}</dd></div><div><dt>Valor pendente</dt><dd>{money(installment.amount)}</dd></div><div><dt>Template</dt><dd>mugo_alerta_pagamento_pendente · pt_BR</dd></div></dl><label>Prévia do alerta<textarea rows="9" readOnly value={preview(name)}/></label><FeedbackMessage type="warning">Os detalhes financeiros, valor, vencimento e PIX serão enviados somente após a interação do cliente.</FeedbackMessage>{templateConfigured&&<FeedbackMessage type="success">Template ativo e disponível para envio.</FeedbackMessage>}{paid&&<FeedbackMessage type="error">Esta parcela já foi paga e não pode ser cobrada.</FeedbackMessage>}{!templateConfigured&&<FeedbackMessage type="error">{templateMessage}</FeedbackMessage>}<footer><button className="button secondary" disabled={syncing||loading} onClick={()=>callIfFunction(onSync)}>{syncing?'Sincronizando…':'Sincronizar status'}</button><button className="button secondary" onClick={()=>callIfFunction(onClose)}>Cancelar</button><button className="button" disabled={disabled||syncing} onClick={()=>callIfFunction(onStart)}>{loading?'Enviando…':'Iniciar conversa'}</button></footer></section></div>
}
