import {useEffect,useState} from 'react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {createContract,generateContractInstallments,listContracts,updateContract} from '../services/data/contractsRepository'
import {listClients} from '../services/data/clientsRepository'
import {listProposals} from '../services/data/proposalsRepository'
import {useAuth} from '../contexts/AuthContext'
import {userError} from '../lib/userError'
import {setupStatus} from '../lib/financialMetrics'
import {contractFinancialStatus} from '../lib/contractBilling'
import {ContractBillingPreviewModal} from './ContractBillingPreviewModal'
import {SetupPaymentModal} from './SetupPaymentModal'

const empty={client_id:'',proposal_id:'',contract_number:'',status:'pending_signature',signed:false,signed_at:'',start_date:'',end_date:'',minimum_term_months:'',billing_day:'',setup_value:'',setup_received_amount:0,monthly_value:'',total_value:'',auto_renew:false,notes:''}
const money=(value)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export function SupabaseContractsPage(){
  const {canWrite,isAdmin}=useAuth(),[items,setItems]=useState([]),[clients,setClients]=useState([]),[proposals,setProposals]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[billing,setBilling]=useState(null),[payment,setPayment]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState('')
  const load=()=>listContracts().then(setItems).catch((cause)=>setError(userError(cause)))
  useEffect(()=>{load();listClients().then(setClients);listProposals().then(setProposals)},[])
  async function submit(event){event.preventDefault();try{const values=Object.fromEntries(Object.entries(form).map(([key,value])=>[key,value===''?null:value]));editing?await updateContract(editing,values):await createContract(values);setForm(empty);setEditing(null);await load()}catch(cause){setError(userError(cause))}}
  async function generate(includeHistory){try{const result=await generateContractInstallments(billing.id,includeHistory);setBilling(null);setMessage(`${result.created} cobrança(s) criada(s). Competências existentes foram preservadas.`);await load()}catch(cause){setError(userError(cause))}}
  async function saveSetup(values){try{await updateContract(payment.id,values);setPayment(null);await load()}catch(cause){setError(userError(cause))}}
  function fromProposal(id){const proposal=proposals.find((item)=>item.id===id);setForm(proposal?{...empty,client_id:proposal.clientId,proposal_id:proposal.id,setup_value:proposal.setupValue||'',monthly_value:proposal.monthlyValue||'',total_value:proposal.totalValue||'',notes:'Criado a partir da proposta; revisar antes de salvar.'}:{...form,proposal_id:''})}
  return <div className="contracts-page"><PageHeader eyebrow="Receita contratada" title="Contratos" description="Cobranças só são geradas depois da confirmação humana."/>{message&&<FeedbackMessage type="success">{message}</FeedbackMessage>}{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}
    {canWrite&&<form className="dashboard-panel contract-form" onSubmit={submit}><h2>{editing?'Editar contrato':'Novo contrato'}</h2><div className="form-grid"><label>Cliente<select required value={form.client_id} onChange={(event)=>setForm({...form,client_id:event.target.value})}><option value="">Selecione</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.company_name}</option>)}</select></label><label>Proposta<select value={form.proposal_id||''} onChange={(event)=>fromProposal(event.target.value)}><option value="">Sem proposta</option>{proposals.filter((proposal)=>proposal.status==='won').map((proposal)=><option key={proposal.id} value={proposal.id}>{proposal.title}</option>)}</select></label><label>Número do contrato<input value={form.contract_number||''} onChange={(event)=>setForm({...form,contract_number:event.target.value})}/></label><label>Data inicial<input type="date" value={form.start_date||''} onChange={(event)=>setForm({...form,start_date:event.target.value})}/></label><label>Data final<input type="date" value={form.end_date||''} onChange={(event)=>setForm({...form,end_date:event.target.value})}/></label><label>Prazo mínimo em meses<input type="number" min="1" value={form.minimum_term_months||''} onChange={(event)=>setForm({...form,minimum_term_months:event.target.value})}/></label><label>Dia da cobrança<input type="number" min="1" max="31" value={form.billing_day||''} onChange={(event)=>setForm({...form,billing_day:event.target.value})}/></label><label>Setup contratado<input type="number" min="0" step="0.01" value={form.setup_value||''} onChange={(event)=>setForm({...form,setup_value:event.target.value})}/></label><label>Mensalidade<input type="number" min="0" step="0.01" value={form.monthly_value||''} onChange={(event)=>setForm({...form,monthly_value:event.target.value})}/></label><label>Total contratado<input type="number" min="0" step="0.01" value={form.total_value||''} onChange={(event)=>setForm({...form,total_value:event.target.value})}/></label><label>Status<select value={form.status} onChange={(event)=>setForm({...form,status:event.target.value})}>{['draft','pending_signature','active','expired','terminated','cancelled'].map((status)=><option key={status}>{status}</option>)}</select></label><label>Assinado<select value={String(form.signed)} onChange={(event)=>setForm({...form,signed:event.target.value==='true'})}><option value="false">Não</option><option value="true">Sim</option></select></label><label className="full-width">Observações<textarea value={form.notes||''} onChange={(event)=>setForm({...form,notes:event.target.value})}/></label></div><button className="button">Salvar após revisão</button></form>}
    <div className="contract-groups">{items.map((contract)=>{const finance=contractFinancialStatus(contract),setupPending=Math.max(Number(contract.setup_value||0)-Number(contract.setup_received_amount||0),0);return <section className="dashboard-panel client-section" key={contract.id}><header><div><h2>{contract.contract_number||'Contrato sem número'}</h2><p>{contract.clients?.company_name} · {money(contract.monthly_value)}/mês</p></div><strong>{contract.status}</strong></header><div className="financial-kpi-grid"><article className="business-stat"><span>Status financeiro</span><strong>{finance.status}</strong></article><article className="business-stat"><span>Cobranças geradas</span><strong>{finance.generated}</strong></article><article className="business-stat"><span>Próximo vencimento</span><strong>{finance.nextDue||'Não gerado'}</strong></article><article className="business-stat"><span>Valor a receber</span><strong>{money(finance.balance)}</strong></article><article className="business-stat"><span>Valor recebido</span><strong>{money(finance.received)}</strong></article><article className="business-stat"><span>Setup pendente</span><strong>{money(setupPending)}</strong><small>{setupStatus(contract)}</small></article></div><div className="row-actions">{canWrite&&<button className="button secondary small" onClick={()=>{setEditing(contract.id);setForm({...empty,...contract})}}>Editar</button>}{canWrite&&<button className="button small" onClick={()=>setBilling(contract)}>{finance.generated?'Gerar próximas cobranças':'Ativar contrato e gerar cobranças'}</button>}{canWrite&&setupPending>0&&<button className="button secondary small" onClick={()=>setPayment(contract)}>Registrar recebimento do setup</button>}<button className="button secondary small" onClick={()=>window.dispatchEvent(new CustomEvent('mugo:navigate',{detail:'finance'}))}>Abrir Financeiro</button></div></section>})}</div>
    {billing&&<ContractBillingPreviewModal contract={billing} onClose={()=>setBilling(null)} onConfirm={generate}/>} {payment&&<SetupPaymentModal contract={payment} correction={isAdmin} onClose={()=>setPayment(null)} onSave={saveSetup}/>} </div>
}
