import {useState} from 'react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {useAuth} from '../contexts/AuthContext'
import {dataProvider,getSupabaseClient} from '../lib/supabase/client'
import {organizationSlug} from '../services/data/provider'
import {AI_PROVIDER,AI_PROVIDER_LABEL} from '../config/aiConfig'
import {testMugoAssistantConnection} from '../services/ai/aiAssistantService'
const ok=(label,detail)=>({label,status:'ok',detail}),fail=(label,error)=>({label,status:'error',detail:classify(error)})
function classify(error){const text=String(error?.message||error||'');if(/column|relation|function|schema cache/i.test(text))return 'A atualização estrutural correspondente ainda não foi aplicada.';if(/row-level|permission|42501/i.test(text))return 'A política de acesso precisa ser revisada.';if(/bucket/i.test(text))return 'O armazenamento privado não foi encontrado ou não está acessível.';return text&&!/object Object/i.test(text)?text:'Falha na verificação.'}
export function SupabaseDiagnosticPage(){
  const auth=useAuth(),[checks,setChecks]=useState([]),[running,setRunning]=useState(false),[aiRunning,setAiRunning]=useState(false),[financial,setFinancial]=useState(null)
  async function run(){setRunning(true);const output=[ok('Provider ativo',dataProvider),ok('Provider da Mugô Intelligence',AI_PROVIDER_LABEL)];if(dataProvider!=='supabase'){setChecks([...output,fail('Supabase configurado','Provider incorreto')]);setRunning(false);return}try{const client=getSupabaseClient();output.push(ok('Supabase configurado','Variáveis públicas presentes'));output.push(auth.session?ok('Sessão autenticada','Sessão ativa'):fail('Sessão autenticada','Sessão ausente'));output.push(auth.profile?ok('Perfil encontrado',auth.profile.role):fail('Perfil encontrado','Perfil ausente'));for(const [label,table,columns] of [['Organização','organizations','id'],['Clientes','clients','id,deleted_at'],['Propostas','proposals','id,responsible_id,deleted_at'],['Contratos','contracts','id,billing_day,start_date,monthly_value'],['Parcelas','invoice_installments','id,received_amount,manual_confirmation_at'],['Configurações','organization_settings','organization_id,pix_key'],['Histórico','commercial_events','id,installment_id']]){let query=client.from(table).select(columns).limit(1);if(table==='organizations')query=query.eq('slug',organizationSlug());const {error}=await query;output.push(error?fail(label,error):ok(label,'Estrutura e leitura disponíveis'))}const {error:rpcError}=await client.rpc('financial_integrity_diagnostic');output.push(rpcError?fail('Funções financeiras',rpcError):ok('Funções financeiras','RPC e permissões disponíveis'));if(!rpcError){const {data}=await client.rpc('financial_integrity_diagnostic');setFinancial(data)}const {data:serviceData,error:serviceError}=await client.rpc('service_responsibility_diagnostic');output.push(serviceError?fail('Responsáveis por serviço',serviceError):ok('Responsáveis por serviço',JSON.stringify(serviceData)));const {error:viewError}=await client.from('payments_safe').select('id').limit(1);output.push(viewError?fail('Visão financeira segura',viewError):ok('Visão financeira segura','Disponível'));output.push(ok('Políticas de acesso',`Leituras verificadas para ${auth.profile?.role||'perfil desconhecido'}`))}catch(error){output.push(fail('Conexão',error))}setChecks(output);setRunning(false)}
  async function testAi(){setAiRunning(true);const result=await testMugoAssistantConnection();setChecks((current)=>[...current.filter((item)=>item.label!=='Teste da Mugô Intelligence'),result.ok?ok('Teste da Mugô Intelligence',result.detail):fail('Teste da Mugô Intelligence',result.detail)]);setAiRunning(false)}
  if(!auth.isAdmin)return <div><PageHeader eyebrow="Sistema" title="Diagnóstico Supabase" description="Acesso exclusivo de administradores."/><FeedbackMessage type="error">Você não tem permissão para acessar este diagnóstico.</FeedbackMessage></div>
  return <div><PageHeader eyebrow="Sistema" title="Diagnóstico Supabase" description="Verifica migrations, tabelas, colunas, funções, policies e views sem expor dados sensíveis." actions={<div className="diagnostic-actions"><button className="button secondary" onClick={testAi} disabled={aiRunning||AI_PROVIDER!=='supabase'}>{aiRunning?'Testando IA…':'Testar Mugô Intelligence'}</button><button className="button" onClick={run} disabled={running}>{running?'Verificando…':'Executar diagnóstico'}</button></div>}/><section className="dashboard-panel"><ul className="diagnostic-list" aria-live="polite" aria-busy={running||aiRunning}>{checks.map((check)=><li key={check.label}><span className={`check-status ${check.status}`}>{check.status==='ok'?'Aprovado':'Atenção'}</span><strong>{check.label}</strong><small>{check.detail}</small></li>)}{!checks.length&&<li>Execute o diagnóstico para verificar a configuração atual.</li>}</ul></section>{financial&&<section className="dashboard-panel"><h2>Integridade financeira</h2><pre>{JSON.stringify(financial,null,2)}</pre><p className="data-note">O diagnóstico não altera registros automaticamente.</p></section>}</div>
}
