import {useEffect,useMemo,useState} from 'react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {createTask,listTasks,updateTask} from '../services/data/tasksRepository'
import {useAuth} from '../contexts/AuthContext'

const statusLabel={pending:'Pendente',in_progress:'Em andamento',completed:'Concluída',cancelled:'Cancelada'}
const priorityLabel={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'}
const TODAY=new Date().toISOString().slice(0,10)
const WEEK=new Date(new Date().getTime()+7*86400000).toISOString().slice(0,10)

export function TodayPage({teamMembers=[],onNavigate}){
  const {canWrite,profile}=useAuth(),[result,setResult]=useState({available:true,items:[]}),[scope,setScope]=useState('mine'),[form,setForm]=useState({title:'',assigned_to:'',due_date:TODAY,priority:'medium'}),[creating,setCreating]=useState(false),[error,setError]=useState('')
  const load=()=>listTasks().then(setResult).catch((cause)=>setError(cause.message))
  useEffect(()=>{load()},[])
  const visible=useMemo(()=>result.items.filter((item)=>scope==='mine'?item.assigned_to===profile?.team_member_id||item.assigned_to===profile?.id:scope==='overdue'?item.due_date<TODAY&&!['completed','cancelled'].includes(item.status):scope==='today'?item.due_date===TODAY:scope==='week'?item.due_date>=TODAY&&item.due_date<=WEEK:true),[result.items,scope,profile?.team_member_id,profile?.id])
  async function submit(event){event.preventDefault();setError('');try{await createTask(form);setCreating(false);setForm({...form,title:''});await load()}catch(cause){setError(cause.message)}}
  function destination(item){return item.installment_id?'finance':item.contract_id?'contracts':item.proposal_id?'proposals':item.client_id?'clients':'dashboard'}
  return <div className="today-page"><PageHeader eyebrow="Operação diária" title="Hoje" description="O que cada pessoa precisa fazer agora." actions={canWrite&&result.available?<button className="button" onClick={()=>setCreating(true)}>Nova tarefa</button>:null}/>{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{!result.available&&<FeedbackMessage type="info">Tarefas operacionais estarão disponíveis após a aplicação manual da migration de arquitetura da informação.</FeedbackMessage>}<nav className="today-filters" aria-label="Filtrar tarefas">{[['mine','Minhas tarefas'],['all','Toda a equipe'],['overdue','Atrasadas'],['today','Hoje'],['week','Próximos 7 dias']].map(([id,label])=><button className={scope===id?'active':''} key={id} onClick={()=>setScope(id)}>{label}</button>)}</nav><div className="today-groups">{teamMembers.map((member)=>{const rows=visible.filter((item)=>item.assigned_to===member.id);if(!rows.length)return null;return <section key={member.id}><h2>{member.name}</h2>{rows.map((item)=><article key={item.id}><div><span className={`task-priority ${item.priority}`}>{priorityLabel[item.priority]}</span><h3>{item.title}</h3><p>{item.clients?.company_name||item.proposals?.title||item.contracts?.contract_number||'Tarefa interna'} · prazo {item.due_date||'não informado'}</p></div><footer><button onClick={()=>onNavigate(destination(item))}>Abrir registro</button>{canWrite&&item.status!=='completed'&&<button onClick={async()=>{await updateTask(item.id,{status:'completed'});await load()}}>Concluir</button>}<span>{statusLabel[item.status]}</span></footer></article>)}</section>})}{result.available&&!visible.length&&<p className="empty-state">Nenhuma tarefa encontrada neste filtro.</p>}</div>{creating&&<div className="modal-overlay"><section className="task-form-modal" role="dialog" aria-modal="true" aria-labelledby="task-title"><h2 id="task-title">Nova tarefa</h2><form onSubmit={submit}><label>Ação<input value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})} required/></label><label>Responsável<select value={form.assigned_to} onChange={(event)=>setForm({...form,assigned_to:event.target.value})} required><option value="">Selecione</option>{teamMembers.map((member)=><option value={member.id} key={member.id}>{member.name}</option>)}</select></label><label>Prazo<input type="date" value={form.due_date} onChange={(event)=>setForm({...form,due_date:event.target.value})}/></label><label>Prioridade<select value={form.priority} onChange={(event)=>setForm({...form,priority:event.target.value})}>{Object.entries(priorityLabel).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><footer><button type="button" className="button secondary" onClick={()=>setCreating(false)}>Voltar</button><button className="button">Criar tarefa</button></footer></form></section></div>}</div>
}
