import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,CheckCircle2,Clock3,Inbox,Plug,Zap} from 'lucide-react'
import {PageHeader} from './PageHeader'
import {FeedbackMessage} from './FeedbackMessage'
import {createTask,getOperationalSummary,listTasks,taskShortId,updateTask} from '../services/data/tasksRepository'
import {useAuth} from '../contexts/AuthContext'

const statusLabel={pending:'Pendente',in_progress:'Em andamento',completed:'Concluída',cancelled:'Cancelada'}
const priorityLabel={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'}
const saoPauloDate=(value=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(value)
const TODAY=saoPauloDate()
const WEEK=saoPauloDate(new Date(Date.now()+7*86400000))
const emptyForm={title:'',assigned_to:'',due_date:TODAY,due_time:'',priority:'medium',notes:''}
const greeting=()=>new Date().getHours()<12?'Bom dia':new Date().getHours()<18?'Boa tarde':'Boa noite'

function SyncBadges({links=[]}){return <div className="task-sync" aria-label="Sincronização externa">{['trello','notion'].map((provider)=>{const link=links.find((item)=>item.provider===provider);return <span className={link?.sync_status==='synced'?'synced':link?'retry':'muted'} key={provider}>{provider==='trello'?'Trello':'Notion'} {link?.sync_status==='synced'?'✓':link?'⚠':'—'}</span>})}</div>}

export function TodayPage({teamMembers=[],onNavigate}){
  const {canWrite,profile}=useAuth(),[result,setResult]=useState({available:true,items:[]}),[summary,setSummary]=useState({integrations:[]}),[scope,setScope]=useState('mine'),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[error,setError]=useState('')
  const currentMember=teamMembers.find((member)=>member.auth_profile_id===profile?.id)||teamMembers.find((member)=>member.id===profile?.team_member_id)
  const load=()=>Promise.all([listTasks(),getOperationalSummary()]).then(([tasks,operational])=>{setResult(tasks);setSummary(operational)}).catch((cause)=>setError(cause.message))
  useEffect(()=>{load()},[])
  const metrics=useMemo(()=>{const rows=result.items;return{today:rows.filter((item)=>item.due_date===TODAY&&!['completed','cancelled'].includes(item.status)).length,high:rows.filter((item)=>item.due_date===TODAY&&['high','critical'].includes(item.priority)&&!['completed','cancelled'].includes(item.status)).length,overdue:rows.filter((item)=>item.due_date<TODAY&&!['completed','cancelled'].includes(item.status)).length,completed:rows.filter((item)=>item.due_date===TODAY&&item.status==='completed').length}},[result.items])
  const visible=useMemo(()=>result.items.filter((item)=>scope==='mine'?item.assigned_to===currentMember?.id:scope==='overdue'?item.due_date<TODAY&&!['completed','cancelled'].includes(item.status):scope==='today'?item.due_date===TODAY:scope==='week'?item.due_date>=TODAY&&item.due_date<=WEEK:scope==='completed'?item.status==='completed':true),[result.items,scope,currentMember?.id])
  const integration=(provider)=>summary.integrations?.find((item)=>item.provider===provider)
  async function submit(event){event.preventDefault();setError('');try{if(editing!=='new')await updateTask(editing,form);else await createTask(form);setEditing(null);setForm(emptyForm);await load()}catch(cause){setError(cause.message)}}
  function openEdit(item){setEditing(item.id);setForm({title:item.title||'',assigned_to:item.assigned_to||'',due_date:item.due_date||'',due_time:item.due_time||'',priority:item.priority||'medium',notes:item.notes||''})}
  function destination(item){return item.installment_id?'finance':item.contract_id?'contracts':item.proposal_id?'proposals':item.client_id?'clients':'intelligence-today'}
  async function mutate(item,patch){try{await updateTask(item.id,patch);await load()}catch(cause){setError(cause.message)}}
  return <div className="today-page"><PageHeader eyebrow="Central Operacional Mugô" title={`${greeting()}, ${profile?.name?.split(' ')[0]||currentMember?.name?.split(' ')[0]||'equipe'}.`} description="Seu dia, atendimentos e pendências em um só lugar." actions={canWrite&&result.available?<button className="button" onClick={()=>{setEditing('new');setForm({...emptyForm,assigned_to:currentMember?.id||''})}}>Nova tarefa</button>:null}/>
    {error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{!result.available&&<FeedbackMessage type="info">Tarefas operacionais estarão disponíveis após a aplicação manual da migration.</FeedbackMessage>}
    <section className="operations-snapshot" aria-label="Resumo do dia">
      <article><Clock3/><div><small>Hoje</small><strong>{metrics.today} tarefas</strong><span>{metrics.high} prioridades altas · {metrics.overdue} atrasada{metrics.overdue===1?'':'s'} · {metrics.completed} concluída{metrics.completed===1?'':'s'}</span></div></article>
      <button type="button" onClick={()=>onNavigate('inbox')}><Inbox/><div><small>Atendimento</small><strong>{summary.unread||0} não lidas</strong><span>{summary.waitingHuman||0} aguardando humano · {summary.botActive||0} no bot</span></div><ArrowRight/></button>
      <button type="button" onClick={()=>onNavigate('collections')}><Zap/><div><small>Cobranças</small><strong>{summary.pendingCharges||0} pendentes</strong><span>{summary.overdueCharges||0} vencida{summary.overdueCharges===1?'':'s'}</span></div><ArrowRight/></button>
      <button type="button" onClick={()=>onNavigate('integrations')}><Plug/><div><small>Integrações</small><strong>Estado operacional</strong><span>{['whatsapp','trello','notion'].map((name)=><i className={integration(name)?.enabled&&!integration(name)?.last_error?'online':'offline'} key={name}>{name} ●</i>)}</span></div><ArrowRight/></button>
    </section>
    <section className="team-load" aria-label="Carga da equipe">{teamMembers.map((member)=>{const rows=result.items.filter((item)=>item.assigned_to===member.id&&item.due_date===TODAY&&!['completed','cancelled'].includes(item.status));return <span key={member.id}><b>{member.name}</b>{rows.length} tarefa{rows.length===1?'':'s'}</span>})}</section>
    <section className="commercial-day-link"><button type="button" onClick={()=>onNavigate('commercial')}><b>{summary.newLeads||0}</b> leads novos <span>·</span> <b>{summary.hotLeads||0}</b> leads quentes <ArrowRight size={14}/></button></section>
    <nav className="today-filters" aria-label="Filtrar tarefas">{[['mine','Minhas tarefas'],['all','Equipe'],['overdue','Atrasadas'],['today','Hoje'],['week','Próximos 7 dias'],['completed','Concluídas']].map(([id,label])=><button className={scope===id?'active':''} key={id} onClick={()=>setScope(id)}>{label}</button>)}</nav>
    <div className="today-groups">{teamMembers.map((member)=>{const rows=visible.filter((item)=>item.assigned_to===member.id);if(!rows.length)return null;return <section key={member.id}><h2>{member.name}</h2>{rows.map((item)=><article key={item.id}><div><div className="task-heading"><span className={`task-priority ${item.priority}`}>{priorityLabel[item.priority]}</span><code>{taskShortId(item.id)}</code></div><h3>{item.title}</h3><p>{item.clients?.company_name||item.proposals?.title||item.contracts?.contract_number||'Tarefa interna'} · prazo {item.due_date||'não informado'}{item.due_time?` às ${item.due_time.slice(0,5)}`:''} · origem {item.source||'crm'}</p><SyncBadges links={item.task_external_links}/></div><footer><button onClick={()=>onNavigate(destination(item))}>Abrir</button>{canWrite&&<button onClick={()=>openEdit(item)}>Editar</button>}{canWrite&&item.status==='pending'&&<button onClick={()=>mutate(item,{status:'in_progress'})}>Iniciar</button>}{canWrite&&item.status!=='completed'&&<button onClick={()=>mutate(item,{status:'completed'})}><CheckCircle2 size={13}/> Concluir</button>}<span>{statusLabel[item.status]}</span></footer></article>)}</section>})}{result.available&&!visible.length&&<p className="empty-state">Nenhuma tarefa encontrada neste filtro.</p>}</div>
    {editing&&<div className="modal-overlay"><section className="task-form-modal" role="dialog" aria-modal="true" aria-labelledby="task-title"><h2 id="task-title">{editing==='new'?'Nova tarefa':'Editar tarefa'}</h2><form onSubmit={submit}><label>Ação<input value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})} required/></label><label>Responsável<select value={form.assigned_to} onChange={(event)=>setForm({...form,assigned_to:event.target.value})} required><option value="">Selecione</option>{teamMembers.map((member)=><option value={member.id} key={member.id}>{member.name}</option>)}</select></label><div className="task-form-row"><label>Prazo<input type="date" value={form.due_date} onChange={(event)=>setForm({...form,due_date:event.target.value})}/></label><label>Horário<input type="time" value={form.due_time} onChange={(event)=>setForm({...form,due_time:event.target.value})}/></label></div><label>Prioridade<select value={form.priority} onChange={(event)=>setForm({...form,priority:event.target.value})}>{Object.entries(priorityLabel).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Notas<textarea value={form.notes} onChange={(event)=>setForm({...form,notes:event.target.value})}/></label><footer><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Voltar</button><button className="button">{editing==='new'?'Criar tarefa':'Salvar alterações'}</button></footer></form></section></div>}
  </div>
}
