/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AlertCircle, Bot, CheckCheck, CircleDollarSign, MessageCircle, PauseCircle, RefreshCw, Search, Send, UserRoundCheck, UsersRound } from 'lucide-react'
import { PageHeader } from './PageHeader'
import { FeedbackMessage } from './FeedbackMessage'
import { PageSkeleton } from './PageSkeleton'
import { normalizeBrazilianPhone } from '../lib/whatsapp'
import { assignConversation, closeHandoff, getAttendanceMeta, getWhatsAppSummary, listConversations, listMessages, listWhatsAppUsers, sendManualMessage, updateConversation } from '../services/data/whatsappRepository'

const tabs = [['inbox','Caixa de entrada'],['collections','Cobranças'],['contacts','Contatos'],['templates','Modelos']]
const fmtTime = value => value ? new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'}).format(new Date(value)) : '—'
const money = value => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value || 0))
const samePhone = (a,b) => normalizeBrazilianPhone(a) && normalizeBrazilianPhone(a) === normalizeBrazilianPhone(b)
const modeLabel = item => item?.awaitingHuman ? 'Aguardando atendimento' : item?.automationPaused ? 'Automação pausada' : item?.attendanceMode === 'human' || !item?.botEnabled ? 'Atendimento humano' : 'Bot ativo'

export function WhatsAppPage({ clients = [], contracts = [], installments = [], proposals = [], onNavigate, canWrite = false, isAdmin = false }) {
  const [tab,setTab]=useState('inbox'),[conversations,setConversations]=useState([]),[selectedId,setSelectedId]=useState(''),[messages,setMessages]=useState([])
  const [summary,setSummary]=useState({}),[meta,setMeta]=useState({queues:[],statuses:[]}),[users,setUsers]=useState([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all')
  const [loading,setLoading]=useState(true),[messagesLoading,setMessagesLoading]=useState(false),[sending,setSending]=useState(false),[error,setError]=useState(''),[draft,setDraft]=useState('')
  const sendingRef=useRef(false)

  const refresh = useCallback(async (quiet=false) => {
    if(!quiet)setLoading(true)
    try {
      const [rows,stats,attendance,userRows]=await Promise.all([listConversations(),getWhatsAppSummary(),getAttendanceMeta(),isAdmin?listWhatsAppUsers():Promise.resolve([])])
      setConversations(rows);setSummary(stats);setMeta(attendance);setUsers(userRows);setError('')
      setSelectedId(current=>current&&rows.some(item=>item.waId===current)?current:(rows[0]?.waId||''))
    } catch (cause) { setError(cause.message) } finally { if(!quiet)setLoading(false) }
  },[isAdmin])
  const loadHistory=useCallback(async waId=>{if(!waId){setMessages([]);return}setMessagesLoading(true);try{setMessages(await listMessages(waId));setError('')}catch(cause){setError(cause.message)}finally{setMessagesLoading(false)}},[])
  useEffect(()=>{refresh()},[refresh])
  useEffect(()=>{loadHistory(selectedId)},[selectedId,loadHistory])
  useEffect(()=>{let timer;const schedule=()=>{if(document.visibilityState==='visible'&&tab==='inbox')timer=setInterval(()=>refresh(true),30000)};schedule();const visibility=()=>{clearInterval(timer);schedule()};document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visibility)}},[refresh,tab])

  const selected=conversations.find(item=>item.waId===selectedId)
  const client=clients.find(item=>samePhone(item.phone,selected?.phone)||samePhone(item.billing_contact_phone,selected?.phone))
  const clientContracts=contracts.filter(item=>item.client_id===client?.id),clientProposals=proposals.filter(item=>item.client_id===client?.id)
  const clientInstallments=installments.filter(item=>item.client_id===client?.id),openInstallments=clientInstallments.filter(item=>['pending','overdue'].includes(item.status))
  const overdue=openInstallments.filter(item=>item.status==='overdue'||(item.due_date&&new Date(item.due_date)<new Date()))
  const filtered=useMemo(()=>conversations.filter(item=>{const haystack=`${item.name} ${item.phone} ${item.preview}`.toLowerCase();if(query&&!haystack.includes(query.toLowerCase()))return false;if(filter==='unread'&&!item.unread)return false;if(filter==='human'&&!item.awaitingHuman&&item.attendanceMode!=='human')return false;if(filter==='bot'&&(item.automationPaused||item.attendanceMode==='human'))return false;if(filter==='paused'&&!item.automationPaused)return false;if(filter==='collection'&&!item.collection)return false;return true}),[conversations,query,filter])

  async function mutate(action){if(!selected||!canWrite)return;try{setError('');await action();await refresh(true);await loadHistory(selected.waId)}catch(cause){setError(cause.message)}}
  async function send(event){event.preventDefault();const text=draft.trim();if(!selected||!text||sendingRef.current||!canWrite)return;sendingRef.current=true;setSending(true);try{await sendManualMessage(selected.waId,text);setDraft('');await Promise.all([loadHistory(selected.waId),refresh(true)])}catch(cause){setError(cause.message)}finally{sendingRef.current=false;setSending(false)}}
  const collections=installments.filter(item=>['pending','overdue'].includes(item.status)).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)))

  return <section className="whatsapp-page">
    <PageHeader eyebrow="Operação integrada" title="WhatsApp" description="Atendimento da agência dentro do CRM, com envio e automação executados com segurança pelo MugoZap." actions={<button className="button button-secondary" onClick={()=>refresh()} disabled={loading}><RefreshCw size={15}/>Atualizar</button>}/>
    <div className="whatsapp-summary">
      <article><MessageCircle/><span>Conversas abertas</span><strong>{summary.conversations_open ?? conversations.length}</strong></article>
      <article><UserRoundCheck/><span>Aguardando humano</span><strong>{summary.waiting_human ?? conversations.filter(x=>x.awaitingHuman).length}</strong></article>
      <article><Bot/><span>Bot ativo</span><strong>{summary.bot_active ?? conversations.filter(x=>modeLabel(x)==='Bot ativo').length}</strong></article>
      <article><PauseCircle/><span>Automação pausada</span><strong>{summary.paused_automation ?? conversations.filter(x=>x.automationPaused).length}</strong></article>
    </div>
    <nav className="whatsapp-tabs" aria-label="Áreas do WhatsApp">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}
    {loading?<PageSkeleton type="dashboard"/>:tab==='inbox'?<div className={`whatsapp-workspace${selected?' has-selection':''}`}>
      <aside className="conversation-list">
        <div className="conversation-tools"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar conversa"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="unread">Não lidas</option><option value="human">Aguardando humano</option><option value="bot">Bot ativo</option><option value="paused">Automação pausada</option><option value="collection">Cobrança</option></select></div>
        <div className="conversation-scroll">{filtered.length?filtered.map(item=><button key={item.waId} className={`conversation-item${selectedId===item.waId?' active':''}`} onClick={()=>setSelectedId(item.waId)}><span className="contact-avatar">{item.name.slice(0,1).toUpperCase()}</span><span className="conversation-copy"><span><strong>{item.name}</strong><time>{fmtTime(item.updatedAt)}</time></span><small>{item.phone}</small><p>{item.preview||'Sem prévia de mensagem'}</p><span className="conversation-badges"><i>{modeLabel(item)}</i>{item.owner&&<i>{item.owner}</i>}{item.collection&&<i className="collection">Cobrança</i>}</span></span>{item.unread>0&&<b>{item.unread}</b>}</button>):<div className="whatsapp-empty">Nenhuma conversa encontrada.</div>}</div>
      </aside>
      <main className="chat-panel">{selected?<><header><div><button className="mobile-back" onClick={()=>setSelectedId('')}>Voltar</button><strong>{selected.name}</strong><small>{selected.phone} · {modeLabel(selected)}</small></div><div className="chat-actions">{canWrite&&<><button onClick={()=>mutate(()=>assignConversation(selected.waId,''))}>Assumir conversa</button><button onClick={()=>mutate(()=>updateConversation(selected.waId,{attendance_mode:'human',automation_paused:true,bot_enabled:false}))}>Pausar automação</button><button onClick={()=>mutate(()=>closeHandoff(selected.waId))}>Retomar automação</button></>} </div></header>
        {isAdmin&&users.length>0&&<div className="chat-management"><label>Responsável<select value={selected.owner||''} onChange={e=>mutate(()=>assignConversation(selected.waId,e.target.value))}><option value="">Sem responsável</option>{users.map(user=><option key={user.id||user.email} value={user.name||user.email}>{user.name||user.email}</option>)}</select></label>{meta.statuses?.length>0&&<small>Status disponíveis: {meta.statuses.join(', ')}</small>}</div>}
        <div className="message-history">{messagesLoading?<div className="whatsapp-empty">Carregando histórico…</div>:messages.length?messages.map(message=><article key={message.id} className={message.direction==='out'?'out':'in'}><p>{message.text||'Mensagem sem conteúdo textual'}</p><footer>{message.template&&<span>Template</span>}{message.collection&&<span>Cobrança</span>}<time>{fmtTime(message.createdAt)}</time>{message.direction==='out'&&<CheckCheck size={13} aria-label={message.status||'enviada'}/>}</footer></article>):<div className="whatsapp-empty">Nenhuma mensagem nesta conversa.</div>}</div>
        <form className="message-composer" onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={canWrite?'Escreva uma resposta manual…':'Seu perfil possui acesso somente para leitura.'} disabled={!canWrite||sending} maxLength={4000}/><button className="button button-primary" disabled={!canWrite||sending||!draft.trim()}><Send size={16}/>{sending?'Enviando…':'Enviar'}</button></form></>:<div className="whatsapp-empty">Selecione uma conversa para abrir o atendimento.</div>}</main>
      <aside className="client-context">{selected?<><header><span>Contexto do cliente</span><strong>{client?.trade_name||client?.company_name||selected.name}</strong><small>{client?'Cliente cadastrado':'Contato não vinculado ao CRM'}</small></header>{client?<><dl><div><dt>Contato</dt><dd>{client.contact_name||'Não informado'}</dd></div><div><dt>Status comercial</dt><dd>{client.status||'Não informado'}</dd></div><div><dt>Contratos</dt><dd>{clientContracts.length}</dd></div><div><dt>Propostas</dt><dd>{clientProposals.length}</dd></div><div><dt>Parcelas pendentes</dt><dd>{openInstallments.length}</dd></div><div><dt>Total em atraso</dt><dd>{money(overdue.reduce((sum,item)=>sum+Number(item.amount||0),0))}</dd></div><div><dt>Próximo vencimento</dt><dd>{openInstallments[0]?.due_date||'Nenhum'}</dd></div></dl><div className="context-actions"><button onClick={()=>onNavigate('clients')}>Abrir cliente</button>{clientContracts.length>0&&<button onClick={()=>onNavigate('contracts')}>Abrir contrato</button>}<button onClick={()=>onNavigate('finance')}>Abrir financeiro</button></div></>:<div className="context-empty"><AlertCircle size={18}/><p>O telefone não corresponde a um cliente cadastrado.</p><button onClick={()=>onNavigate('clients')}>Criar cliente</button></div>}</>:null}</aside>
    </div>:tab==='collections'?<div className="whatsapp-table-card"><header><div><CircleDollarSign/><div><strong>Cobranças</strong><small>Base financeira oficial: parcelas do CRM. O envio permanece sujeito à revisão humana.</small></div></div></header>{collections.length?<div className="whatsapp-table">{collections.map(item=><article key={item.id}><div><strong>{item.clients?.company_name||'Cliente não informado'}</strong><small>{item.due_date} · {item.status}</small></div><strong>{money(item.amount)}</strong><button onClick={()=>{const conversation=conversations.find(c=>samePhone(c.phone,item.clients?.billing_contact_phone||item.clients?.phone));if(conversation){setSelectedId(conversation.waId);setTab('inbox')}}} disabled={!conversations.some(c=>samePhone(c.phone,item.clients?.billing_contact_phone||item.clients?.phone))}>Abrir conversa</button><button disabled title="O envio de template será habilitado após configuração e validação do template oficial.">Enviar alerta</button></article>)}</div>:<div className="whatsapp-empty">Nenhuma parcela pendente encontrada.</div>}</div>:tab==='contacts'?<div className="whatsapp-table-card"><header><div><UsersRound/><div><strong>Contatos</strong><small>Clientes do CRM relacionados às conversas pelo telefone normalizado.</small></div></div></header><div className="whatsapp-table">{clients.map(item=>{const conversation=conversations.find(c=>samePhone(c.phone,item.phone)||samePhone(c.phone,item.billing_contact_phone));return <article key={item.id}><div><strong>{item.trade_name||item.company_name}</strong><small>{item.contact_name||'Sem contato'} · {item.phone||item.billing_contact_phone||'Sem telefone'}</small></div><span>{item.status}</span><button disabled={!conversation} onClick={()=>{setSelectedId(conversation.waId);setTab('inbox')}}>Abrir conversa</button><button onClick={()=>onNavigate('clients')}>Abrir cliente</button></article>})}</div></div>:<div className="template-card"><header><strong>mugo_alerta_pagamento_pendente</strong><span>Utilidade · pt_BR</span></header><p>Finalidade: iniciar alerta financeiro. Interação esperada: Consultar cobrança.</p><dl><div><dt>Uso</dt><dd>Alertas financeiros revisados pela equipe</dd></div><div><dt>Variáveis</dt><dd>Conforme configuração oficial do MugoZap</dd></div><div><dt>Ação</dt><dd>Enviar alerta</dd></div></dl><FeedbackMessage type="warning">A aprovação e o status oficial do template continuam sendo gerenciados na Meta.</FeedbackMessage></div>}
  </section>
}
