/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react'
import { AlertCircle, CheckCheck, Clock3, MessageCircle, RefreshCw, WalletCards } from 'lucide-react'
import { FeedbackMessage } from './FeedbackMessage'
import { getWhatsAppUsage } from '../services/data/whatsappRepository'
const money=(value,currency='BRL')=>new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(Number(value||0))
export function WhatsAppUsagePanel(){
  const [days,setDays]=useState(30),[usage,setUsage]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  async function load(){setLoading(true);try{setUsage(await getWhatsAppUsage(days));setError('')}catch(cause){setError(cause.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[days])
  const daily=Object.entries(usage?.daily||{}).sort(([a],[b])=>a.localeCompare(b)),max=Math.max(...daily.map(([,value])=>value),1)
  return <section className="whatsapp-usage-panel"><header className="templates-header"><div><span>Mensuração operacional</span><h2>Uso e custos</h2><p>Contadores reais do MugoZap e estimativa baseada nas tarifas configuradas.</p></div><div><select value={days} onChange={event=>setDays(Number(event.target.value))}><option value="1">Hoje</option><option value="7">7 dias</option><option value="30">Este mês</option><option value="90">90 dias</option></select><button className="button secondary" onClick={load} disabled={loading}><RefreshCw size={14}/>Atualizar</button></div></header>{error&&<FeedbackMessage type="error">{error}</FeedbackMessage>}{loading&&!usage?<div className="whatsapp-empty">Carregando uso real…</div>:<><div className="whatsapp-summary usage-cards">{[['Mensagens enviadas',usage?.sent,MessageCircle],['Mensagens entregues',usage?.delivered,CheckCheck],['Mensagens lidas',usage?.read,CheckCheck],['Mensagens com falha',usage?.failed,AlertCircle],['Templates entregues',usage?.delivered_templates,Clock3],['Utilidade',usage?.utility,WalletCards],['Marketing',usage?.marketing,WalletCards],['Custo estimado',usage?.pricing_configured?money(usage.estimated_cost,usage.currency||'BRL'):'Não configurado',WalletCards]].map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{value??0}</strong></article>)}</div><FeedbackMessage type="warning">Estimativa baseada nas tarifas configuradas. Consulte a Meta para o valor oficial.</FeedbackMessage><div className="usage-grid"><section><h3>Entregues por dia</h3><div className="usage-bars">{daily.map(([day,value])=><div key={day}><span>{day}</span><i><b style={{width:`${value/max*100}%`}}/></i><strong>{value}</strong></div>)}</div></section><section><h3>Distribuição por categoria</h3>{Object.entries(usage?.categories||{}).map(([name,value])=><p key={name}>{name}<strong>{value}</strong></p>)}</section><section><h3>Templates mais enviados</h3>{Object.entries(usage?.templates||{}).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name,value])=><p key={name}>{name}<strong>{value}</strong></p>)}</section><section><h3>Falhas por motivo</h3>{Object.entries(usage?.failures||{}).map(([name,value])=><p key={name}>{name}<strong>{value}</strong></p>)}</section></div></>}</section>
}
