import { useMemo, useRef, useState } from 'react'
import { FeedbackMessage } from './FeedbackMessage'
import { isValidBrazilianPhone, normalizeBrazilianPhone } from '../lib/whatsapp'
import { callIfFunction } from '../lib/callbackSafety'
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0))
export function WhatsAppBatchModal({installments,clients,contracts,alerts,templateStatus,templateAvailable,onClose,onSend}){
  const [scope,setScope]=useState('overdue'),[sending,setSending]=useState(false),[result,setResult]=useState(null),[baseDate]=useState(()=>new Date()),lock=useRef(false),today=baseDate.toISOString().slice(0,10)
  const review=useMemo(()=>{const days=scope==='3'?3:scope==='7'?7:null,target=days?new Date(baseDate.getTime()-days*86400000).toISOString().slice(0,10):null,selected=installments.filter(item=>scope==='today'?item.due_date===today:scope==='overdue'?item.due_date<today:item.due_date===target),eligible=[],reasons=[];selected.forEach(item=>{const client=clients.find(row=>row.id===item.client_id),contract=contracts.find(row=>row.id===item.contract_id),phone=normalizeBrazilianPhone(client?.billing_contact_phone||client?.phone);let reason='';if(!phone)reason='Sem telefone';else if(!isValidBrazilianPhone(phone))reason='Telefone inválido';else if(alerts.some(row=>row.installment_id===item.id&&row.status!=='failed'))reason='Já alertada';else if(item.status==='paid')reason='Parcela paga';else if(contract?.status==='cancelled')reason='Contrato cancelado';if(reason)reasons.push({id:item.id,name:client?.company_name||'Cliente',reason});else eligible.push({item,client,phone})});return{checked:selected.length,eligible:eligible.slice(0,20),reasons,total:eligible.slice(0,20).reduce((sum,row)=>sum+Number(row.item.amount||0),0)}},[scope,installments,clients,contracts,alerts,today,baseDate])
  async function send(){if(lock.current||!templateAvailable||typeof onSend!=='function')return;lock.current=true;setSending(true);try{setResult(await callIfFunction(onSend,review.eligible))}finally{lock.current=false;setSending(false)}}
  return <div className="modal-overlay"><section className="whatsapp-modal" role="dialog" aria-modal="true"><h2>Revisar envio em lote</h2><label>Período<select value={scope} onChange={event=>setScope(event.target.value)}><option value="today">Vencendo hoje</option><option value="overdue">Vencidas</option><option value="3">Vencidas há 3 dias</option><option value="7">Vencidas há 7 dias</option></select></label><dl><div><dt>Verificadas</dt><dd>{review.checked}</dd></div><div><dt>Elegíveis</dt><dd>{review.eligible.length}</dd></div><div><dt>Valor</dt><dd>{money(review.total)}</dd></div><div><dt>Template</dt><dd>{templateStatus}</dd></div></dl>{templateStatus!=='APPROVED'&&<FeedbackMessage type="warning">O template não está ativo. Nenhum envio será realizado.</FeedbackMessage>}<div className="batch-review-list">{review.eligible.map(row=><p key={row.item.id}>{row.client.company_name} · elegível</p>)}{review.reasons.map(row=><p key={row.id}>{row.name} · {row.reason}</p>)}</div>{result&&<FeedbackMessage type={result.failed?'warning':'success'}>{result.sent} enviados, {result.failed} falharam, {result.skipped} ignorados.</FeedbackMessage>}<footer><button className="button secondary" onClick={()=>callIfFunction(onClose)}>Cancelar</button><button className="button" disabled={sending||templateStatus!=='APPROVED'||!review.eligible.length} onClick={send}>{sending?'Enviando…':'Enviar alertas'}</button></footer></section></div>
}
