import { AGENCY_GOALS } from '../../config/agencyGoals.js'
import { calculateCommercialPerformance, groupCommercialPerformance } from '../../lib/commercialMetrics.js'
import { buildForecast } from '../intelligence/forecastEngine.js'
import { buildHealthScore } from '../intelligence/healthEngine.js'
import { buildInsights } from '../intelligence/insightsEngine.js'
import { buildOpportunities } from '../intelligence/opportunityEngine.js'
import { buildTimeline } from '../intelligence/timelineEngine.js'
import { calculateFinancialSummary } from '../../lib/financialMetrics.js'
import { calculateContractsForTarget, calculateServiceMixForTarget, parseCommercialQuestion } from './commercialQuestionParser.js'
import { SERVICE_CATALOG } from '../../config/serviceCatalog.js'

const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0)
const norm = (value) => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
const answer = (text, sources, intention, handled = true, extras = {}) => ({ text, answer:text, sources, mode: 'local', intention, intent:intention, handled, confidence:handled?100:0, ...extras })

export function localBusinessAssistant(question, data = {}) {
  const q = norm(question)
  if (/criar|alterar|excluir|enviar|marcar|ativar|importar/.test(q)) return answer('Posso orientar você, mas nesta versão não realizo alterações no CRM.', ['Política consultiva'], 'consultive_policy')
  const proposals = data.proposals || []
  const contracts = data.contracts || []
  const installments = data.installments || []
  const clients = data.clients || []
  const documents = data.documents || []
  const performance = calculateCommercialPerformance(proposals)
  const active = contracts.filter((contract) => contract.status === 'active' && contract.signed)
  const recurring = active.reduce((sum, contract) => sum + Number(contract.monthly_value || 0), 0)
  const project = contracts.reduce((sum, contract) => sum + Number(contract.setup_value || 0), 0)
  const insights = buildInsights(data)
  const opportunities = buildOpportunities(data)
  const financial = calculateFinancialSummary(contracts, installments)
  const parsed = parseCommercialQuestion(question)
  const documentAnalyses = data.documentAnalyses || []
  const installmentBalance=(item)=>Math.max(Number(item.amount||0)-Number(item.received_amount||0),0)
  const currentMonth=new Date().toISOString().slice(0,7)

  if(q.includes('contratos')&&q.includes('importad')){const confirmed=documentAnalyses.filter((item)=>item.status==='confirmed'&&['signed_contract','unsigned_contract','amendment'].includes(item.document_type));return answer(confirmed.length?`${confirmed.length} contrato(s) foram importados após revisão humana: ${confirmed.slice(0,8).map((item)=>item.file_name).join(', ')}.`:'Nenhum contrato importado após revisão humana foi identificado.',['Análises de documentos','Documentos'],'document_imports')}
  if(q.includes('valor mensal')&&q.includes('extraid')){const rows=contracts.filter((item)=>documents.some((document)=>document.contract_id===item.id));return answer(rows.length?rows.slice(0,8).map((item)=>`${item.clients?.company_name||'Cliente'}: ${item.monthly_value==null?'valor mensal não identificado':money(item.monthly_value)}`).join(' · '):'Nenhum valor mensal confirmado por importação foi identificado.',['Contratos','Documentos analisados'],'document_imports')}
  if(q.includes('documentos')&&q.includes('baixa confianca')){const rows=documentAnalyses.filter((item)=>item.low_confidence_fields?.length);return answer(rows.length?`${rows.length} documento(s) possuem campos com baixa confiança: ${rows.slice(0,8).map((item)=>`${item.file_name} (${item.low_confidence_fields.length})`).join(', ')}.`:'Nenhum documento com baixa confiança foi identificado.',['Análises de documentos'],'document_review')}
  if(q.includes('contratos')&&q.includes('revisao')){const rows=documentAnalyses.filter((item)=>['signed_contract','unsigned_contract','amendment'].includes(item.document_type)&&(item.status!=='confirmed'||item.low_confidence_fields?.length));return answer(rows.length?`${rows.length} contrato(s) precisam de revisão: ${rows.slice(0,8).map((item)=>item.file_name).join(', ')}.`:'Nenhum contrato pendente de revisão foi identificado.',['Análises de documentos'],'document_review')}
  if(q.includes('propostas')&&(q.includes('sem data de envio')||q.includes('nao possuem data de envio'))){const rows=proposals.filter((item)=>!item.sentAt&&!item.sent_at);return answer(rows.length?`${rows.length} proposta(s) ainda não possuem data de envio: ${rows.slice(0,8).map((item)=>item.title).join(', ')}.`:'Todas as propostas cadastradas possuem data de envio.',['Propostas'],'proposal_dates')}
  if(q.includes('propostas')&&(q.includes('sem responsavel')||q.includes('nao atribuid'))){const rows=proposals.filter((item)=>!item.responsibleName&&!item.responsible);return answer(rows.length?`${rows.length} proposta(s) estão sem responsável: ${rows.slice(0,8).map((item)=>item.title).join(', ')}.`:'Não há propostas sem responsável.',['Propostas'],'proposal_assignment')}
  if(q.includes('propostas abertas')){const rows=proposals.filter((item)=>!['won','lost','cancelled','expired'].includes(item.status));return answer(rows.length?`${rows.length} proposta(s) abertas: ${rows.slice(0,8).map((item)=>`${item.companyName} — ${item.mainService||'serviço não informado'}`).join(' · ')}.`:'Não há propostas abertas.',['Propostas'],'pipeline_summary')}
  if(q.includes('clientes')&&q.includes('sem contrato')){const linked=new Set(contracts.map((item)=>item.client_id));const rows=clients.filter((item)=>!linked.has(item.id));return answer(rows.length?`${rows.length} cliente(s) sem contrato: ${rows.slice(0,8).map((item)=>item.company_name||item.trade_name).join(', ')}.`:'Todos os clientes cadastrados possuem contrato.',['Clientes','Contratos'],'client_contracts')}
  if(q.includes('maior contrato')){const row=[...contracts].sort((a,b)=>Number(b.total_value||b.setup_value||0)-Number(a.total_value||a.setup_value||0))[0];return answer(row?`${row.clients?.company_name||'Cliente'} possui o maior contrato: ${money(row.total_value||row.setup_value)}.`:'Nenhum contrato foi identificado.',['Contratos'],'contract_summary')}
  if(q.includes('ticket medio'))return answer(`O ticket médio das propostas enviadas é ${money(performance.averageSent)}; entre as ganhas, ${money(performance.averageWon)}.`,['Propostas'],'commercial_summary')
  if(q.includes('maior mrr')||q.includes('maior receita mensal')){const row=[...active].sort((a,b)=>Number(b.monthly_value||0)-Number(a.monthly_value||0))[0];return answer(row?`${row.clients?.company_name||'Cliente'} possui o maior MRR: ${money(row.monthly_value)}.`:'Nenhum contrato ativo e assinado foi identificado.',['Contratos'],'revenue_projection')}
  if(q.includes('a receber')&&q.includes('este mes')){const rows=installments.filter((item)=>String(item.reference_month).startsWith(currentMonth));return answer(`Há ${money(rows.reduce((sum,item)=>sum+installmentBalance(item),0))} a receber neste mês em ${rows.filter((item)=>installmentBalance(item)>0).length} parcela(s).`,['Financeiro'],'financial_attention')}
  if(q.includes('quanto')&&q.includes('deve')&&q.includes('este mes')){const client=clients.find((item)=>q.includes(norm(item.company_name||item.trade_name)));if(!client)return answer('Informe o nome do cliente para consultar o saldo do mês.',['Clientes'],'financial_attention');const rows=installments.filter((item)=>item.client_id===client.id&&String(item.reference_month).startsWith(currentMonth));return answer(`${client.company_name||client.trade_name} possui ${money(rows.reduce((sum,item)=>sum+installmentBalance(item),0))} a receber neste mês.`,['Clientes','Financeiro'],'financial_attention')}
  if(q.includes('quem pagou')&&q.includes('este mes')){const rows=installments.filter((item)=>Number(item.received_amount)>0&&String(item.manual_confirmation_at||item.paid_at).startsWith(currentMonth));return answer(rows.length?rows.map((item)=>`${item.clients?.company_name||clients.find((client)=>client.id===item.client_id)?.company_name||'Cliente'}: ${money(item.received_amount)}`).join(' · '):'Nenhum recebimento de mensalidade foi confirmado neste mês.',['Financeiro'],'financial_attention')}
  if(q.includes('quanto recebemos de mensalidade')){const rows=installments.filter((item)=>String(item.manual_confirmation_at||item.paid_at).startsWith(currentMonth));return answer(`Foram confirmados ${money(rows.reduce((sum,item)=>sum+Number(item.received_amount||0),0))} em mensalidades neste mês.`,['Financeiro'],'financial_attention')}
  if(q.includes('proximo vencimento')){const client=clients.find((item)=>q.includes(norm(item.company_name||item.trade_name)));const rows=installments.filter((item)=>(!client||item.client_id===client.id)&&installmentBalance(item)>0&&item.due_date>=new Date().toISOString().slice(0,10)).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));return answer(rows[0]?`O próximo vencimento${client?` de ${client.company_name||client.trade_name}`:''} é ${rows[0].due_date}, no valor de ${money(installmentBalance(rows[0]))}.`:'Nenhum próximo vencimento foi identificado.',['Financeiro'],'financial_attention')}
  if(q.includes('contratos')&&q.includes('nao geraram cobrancas')){const rows=active.filter((contract)=>!installments.some((item)=>item.contract_id===contract.id));return answer(rows.length?`${rows.length} contrato(s) ativo(s) ainda não geraram cobranças: ${rows.map((item)=>item.clients?.company_name||item.contract_number||item.id).join(', ')}.`:'Todos os contratos ativos possuem cobranças.',['Contratos','Financeiro'],'financial_diagnostic')}
  if(q.includes('contratos ativos')&&q.includes('sem dia de cobranca')){const rows=active.filter((contract)=>!contract.billing_day);return answer(rows.length?`${rows.length} contrato(s) ativo(s) estão sem dia de cobrança: ${rows.map((item)=>item.clients?.company_name||item.contract_number||item.id).join(', ')}.`:'Nenhum contrato ativo está sem dia de cobrança.',['Contratos'],'financial_diagnostic')}

  if(parsed.target&&parsed.service&&parsed.asksContractCount){const scenarios=calculateContractsForTarget(parsed.target,parsed.service.services),mix=calculateServiceMixForTarget(parsed.target,parsed.service.services);if(!scenarios.length)return answer(`O catálogo atual não possui preço recomendado suficiente para simular ${parsed.service.label}.`,['Catálogo de serviços da Mugô'],'service_target');const lines=scenarios.slice(0,4).map((item)=>`• ${item.quantity} contratos de ${item.service}: ${item.quantity} × ${money(item.unitPrice)} = ${money(item.total)}`),mixText=mix?.items?.length?`\n\nCombinação com menor excedente: ${mix.items.map((item)=>`${item.quantity} ${item.service}`).join(' + ')} = ${money(mix.total)}.`:'';return answer(`Para alcançar ${money(parsed.target)} com ${parsed.service.label}, considerando os preços recomendados do catálogo:\n\n${lines.join('\n')}${mixText}\n\nEssa é uma simulação comercial e não altera os dados do CRM.`,['Catálogo de serviços da Mugô'],'service_target',true,{structuredData:{type:'service_target',target:parsed.target,service:parsed.service.label,scenarios:scenarios.slice(0,4),mix}})}
  if(parsed.asksGoal&&parsed.target){const available=parsed.service?.services?.length?parsed.service.services:SERVICE_CATALOG.filter((service)=>service.billingType==='recurring');const mix=calculateServiceMixForTarget(parsed.target,available);if(mix)return answer(`Uma combinação estimada para alcançar ${money(parsed.target)} é ${mix.items.map((item)=>`${item.quantity} ${item.service}`).join(' + ')}, totalizando ${money(mix.total)}. Essa é uma simulação baseada no catálogo e não altera o CRM.`,['Catálogo de serviços da Mugô'],'goal_service_mix',true,{structuredData:{type:'service_mix',target:parsed.target,mix}})}
  if(q.includes('social')&&(/nao tem|sem/.test(q))&&(/trafego|midia paga/.test(q))){const rows=clients.filter((client)=>{const services=contracts.filter((contract)=>contract.client_id===client.id).flatMap((contract)=>contract.contract_services||[]).map((service)=>norm(service.service_name)).join(' ');return /social|redes sociais/.test(services)&&!/trafego|midia paga/.test(services)});return answer(rows.length?`${rows.map((client)=>client.company_name||client.trade_name).join(', ')} possuem Social cadastrado e não possuem Tráfego Pago identificado.`:'Nenhum cliente corresponde a esse critério com os dados cadastrados.',['Clientes','Contratos','Serviços'],'cross_sell')}

  if ((q.includes('falta') && q.includes('meta')) || q.includes('goal_projection')) return answer(`Faltam ${money(Math.max(AGENCY_GOALS.monthlyAgencyGoal - recurring, 0))} para a meta mensal de ${money(AGENCY_GOALS.monthlyAgencyGoal)}.`, ['Contratos ativos e assinados', 'Meta da agência'], 'goal_projection')
  if (q.includes('forecast') || q.includes('projecao') || q.includes('receita futura')) { const forecast = buildForecast(data); return answer(forecast.map((item) => `${item.days} dias: ${money(item.total)}`).join(' · '), ['Contratos ativos', 'Renovações cadastradas'], 'sales_forecast') }
  if (q.includes('saude') || q.includes('score')) { const health = buildHealthScore(data, AGENCY_GOALS.monthlyAgencyGoal); return answer(`A saúde comercial calculada é ${health.score}/100. ${health.components.map((item) => `${item.label}: ${item.score}`).join(' · ')}.`, ['Receita', 'Conversão', 'Contratos', 'Documentação', 'Financeiro'], 'health_score') }
  if (q.includes('esquecid') || q.includes('parad')) { const list = insights.filter((item) => item.title === 'Proposta esquecida'); return answer(list.length ? list.slice(0, 5).map((item) => item.description).join(' ') : 'Não há propostas esquecidas identificadas.', ['Radar Comercial', 'Propostas'], 'forgotten_proposals') }
  if (q.includes('contratos') && q.includes('venc')) { const list = insights.filter((item) => item.title.includes('Contrato')); return answer(list.length ? list.slice(0, 6).map((item) => item.description).join(' ') : 'Nenhum contrato vencido ou vencendo em até 60 dias foi identificado.', ['Radar Comercial', 'Contratos'], 'expiring_contracts') }
  if (q.includes('renov')) { const list = opportunities.filter((item) => item.type === 'Renovação'); return answer(list.length ? list.slice(0, 6).map((item) => `${item.client}: ${item.reason} Valor estimado ${money(item.estimatedValue)}.`).join(' ') : 'Nenhuma renovação foi identificada para os próximos 90 dias.', ['Oportunidades', 'Contratos'], 'renewal_prediction') }
  if (q.includes('quem devo ligar') || q.includes('risco') && q.includes('cliente')) { const list = insights.filter((item) => item.clientId).slice(0, 6); return answer(list.length ? list.map((item) => item.description).join(' ') : 'Nenhum cliente prioritário foi identificado.', ['Radar Comercial'], 'risk_clients') }
  if (q.includes('upsell') || q.includes('cross') || q.includes('podem comprar') || q.includes('oportunidade')) { const list = opportunities.filter((item) => !q.includes('ia') || item.type === 'IA'); return answer(list.length ? list.slice(0, 6).map((item) => `${item.client}: ${item.service}, ${money(item.estimatedValue)}, confiança ${item.confidence}%.`).join(' ') : 'Nenhuma oportunidade compatível foi identificada.', ['Oportunidades', 'Catálogo de serviços'], q.includes('cross') ? 'cross_sell' : 'upsell') }
  if (q.includes('quanto recebemos de setup') || q.includes('setup recebido')) return answer(`Recebemos ${money(financial.setupReceived)} de setup.`, ['Contratos', 'Recebimentos manuais de setup'], 'financial_attention')
  if (q.includes('falta receber de setup') || q.includes('setup pendente')) { const pending=contracts.filter((contract)=>Number(contract.setup_value||0)>Number(contract.setup_received_amount||0)),names=[...new Set(pending.map((contract)=>contract.clients?.company_name||clients.find((client)=>client.id===contract.client_id)?.company_name).filter(Boolean))]; return answer(`${money(financial.setupPending)} de setup permanece pendente. ${pending.length} contrato(s) possuem saldo${names.length?`: ${names.join(', ')}`:'.'}`, ['Contratos', 'Recebimentos manuais de setup'], 'financial_attention') }
  if (q.includes('quanto temos em aberto') || q.includes('total em aberto')) return answer(`O saldo total em aberto é ${money(financial.totalOpen)}: ${money(financial.setupPending)} de setup e ${money(financial.monthlyPending)} de mensalidades.`, ['Contratos', 'Financeiro'], 'financial_attention')
  if (q.includes('maior saldo em aberto')) { const rows=clients.map((client)=>{const clientContracts=contracts.filter((contract)=>contract.client_id===client.id),clientInstallments=installments.filter((item)=>item.client_id===client.id);return {name:client.company_name||client.trade_name||'Cliente',value:calculateFinancialSummary(clientContracts,clientInstallments).totalOpen}}).sort((a,b)=>b.value-a.value);return answer(rows[0]?.value?`${rows[0].name} possui o maior saldo em aberto: ${money(rows[0].value)}.`:'Nenhum saldo em aberto foi identificado.',['Clientes','Contratos','Financeiro'],'financial_attention') }
  if (q.includes('quanto ja recebemos')) { const client=clients.find((item)=>q.includes(norm(item.company_name||item.trade_name)));if(!client)return answer('Informe o nome do cliente para consultar o total recebido.',['Clientes'],'financial_attention');const value=calculateFinancialSummary(contracts.filter((contract)=>contract.client_id===client.id),installments.filter((item)=>item.client_id===client.id)).totalReceived;return answer(`Já recebemos ${money(value)} de ${client.company_name||client.trade_name}.`,['Cliente','Contratos','Financeiro'],'financial_attention') }
  if (q.includes('financeir') || q.includes('nao paga') || q.includes('parcelas') && q.includes('venc')) { const overdue = installments.filter((item) => item.status === 'overdue').sort((a, b) => String(a.due_date).localeCompare(String(b.due_date))); return answer(overdue.length ? `${overdue.length} parcelas vencidas, totalizando ${money(overdue.reduce((sum, item) => sum + Number(item.amount || 0), 0))}. A mais antiga vence em ${overdue[0].due_date}.` : 'Não há parcelas vencidas cadastradas.', ['Financeiro', 'Parcelas'], 'financial_attention') }
  if (q.includes('servico') && q.includes('converte')) { const rows = groupCommercialPerformance(proposals, 'service').sort((a, b) => b.outcomeConversion - a.outcomeConversion); return answer(rows.length ? `${rows[0].label} possui a maior conversão por desfecho: ${rows[0].outcomeConversion.toFixed(1)}%.` : 'Não há propostas suficientes para comparar serviços.', ['Performance comercial', 'Propostas'], 'pipeline_summary') }
  if (q.includes('responsavel')) { const rows = groupCommercialPerformance(proposals, 'responsible').sort((a,b)=>b.wonValue-a.wonValue); return answer(rows.length?`${rows[0].label} gerou o maior valor ganho: ${money(rows[0].wonValue)}. ${rows.map((row) => `${row.label}: ${row.won} ganhas de ${row.sent} enviadas`).join(' · ')}`:'Não há dados por responsável.', ['Performance comercial'], 'responsible_summary') }
  if (q.includes('pipeline')) return answer(`${performance.open} propostas abertas, ${performance.negotiating} em negociação, ${performance.won} ganhas e ${performance.lost} perdidas. Valor proposto: ${money(performance.proposedValue)}.`, ['Propostas', 'Performance comercial'], 'pipeline_summary')
  if (q.includes('timeline') || q.includes('historico')) { const timeline = buildTimeline(data); return answer(timeline.length ? timeline.slice(0, 8).map((item) => `${item.type}: ${item.title} em ${new Date(item.date).toLocaleDateString('pt-BR')}.`).join(' ') : 'Não há eventos disponíveis na timeline comercial.', ['Timeline Comercial'], 'commercial_timeline') }
  if (q.includes('receita recorrente')) return answer(`A receita recorrente registrada é ${money(recurring)}.`, ['Contratos ativos e assinados'], 'revenue_projection')
  if (q.includes('receita de projetos')) return answer(`A receita de projetos registrada é ${money(project)}.`, ['Contratos'], 'revenue_projection')
  if (q.includes('conversao')) return answer(`A conversão por desfecho é ${performance.outcomeConversion.toFixed(1)}%.`, ['Propostas ganhas e perdidas'], 'commercial_summary')
  if (q.includes('clientes') && q.includes('ativos')) return answer(`${clients.filter((client) => client.status === 'active').length} clientes estão ativos.`, ['Clientes'], 'commercial_summary')
  if (q.includes('resumo') || q.includes('aumentar a receita')) return answer(`MRR ${money(recurring)}; meta ${money(AGENCY_GOALS.monthlyAgencyGoal)}; conversão ${performance.outcomeConversion.toFixed(1)}%; ${insights.filter((item) => item.severity === 'Alta').length} alertas de alta criticidade; ${opportunities.length} oportunidades identificadas.`, ['Resumo Executivo', 'Radar Comercial', 'Oportunidades'], 'commercial_summary')
  return answer('Não consegui entender completamente. Você quer consultar metas, clientes, propostas, contratos, serviços ou financeiro?', [], undefined, false, {suggestions:['Quanto falta para a meta?','Quais contratos vencem este mês?','Quanto temos em aberto?']})
}
